#pragma line 1 "black_scholes.c" ::: 0
#pragma line 1 "black_scholes.c" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 149 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 12
#pragma line 278 "/opt/xilinx/Vivado_HLS/2014.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 65
#pragma line 8 "<command line>" 2 ::: 191
#pragma line 1 "<built-in>" 2 ::: 192
#pragma line 1 "black_scholes.c" 2 ::: 193
#pragma line 1 "./black_scholes.h" 1 ::: 194
#pragma line 1 "./gaussian.h" 1 ::: 198
#pragma line 1 "./util.h" 1 ::: 211
#pragma line 13 "./gaussian.h" 2 ::: 261
#pragma line 5 "./black_scholes.h" 2 ::: 283
#pragma line 1 "/usr/include/math.h" 1 3 4 ::: 284
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 313
#pragma line 115 "/usr/include/features.h" 3 4 ::: 406
#pragma line 139 "/usr/include/features.h" 3 4 ::: 423
#pragma line 169 "/usr/include/features.h" 3 4 ::: 433
#pragma line 179 "/usr/include/features.h" 3 4 ::: 436
#pragma line 294 "/usr/include/features.h" 3 4 ::: 448
#pragma line 1 "/usr/include/sys/cdefs.h" 1 3 4 ::: 485
#pragma line 72 "/usr/include/sys/cdefs.h" 3 4 ::: 531
#pragma line 98 "/usr/include/sys/cdefs.h" 3 4 ::: 549
#pragma line 111 "/usr/include/sys/cdefs.h" 3 4 ::: 555
#pragma line 123 "/usr/include/sys/cdefs.h" 3 4 ::: 559
#pragma line 155 "/usr/include/sys/cdefs.h" 3 4 ::: 577
#pragma line 178 "/usr/include/sys/cdefs.h" 3 4 ::: 587
#pragma line 222 "/usr/include/sys/cdefs.h" 3 4 ::: 624
#pragma line 275 "/usr/include/sys/cdefs.h" 3 4 ::: 665
#pragma line 313 "/usr/include/sys/cdefs.h" 3 4 ::: 689
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 690
#pragma line 314 "/usr/include/sys/cdefs.h" 2 3 4 ::: 692
#pragma line 330 "/usr/include/features.h" 2 3 4 ::: 693
#pragma line 1 "/usr/include/gnu/stubs.h" 1 3 4 ::: 717
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 722
#pragma line 5 "/usr/include/gnu/stubs.h" 2 3 4 ::: 724
#pragma line 1 "/usr/include/gnu/stubs-64.h" 1 3 4 ::: 729
#pragma line 10 "/usr/include/gnu/stubs.h" 2 3 4 ::: 734
#pragma line 353 "/usr/include/features.h" 2 3 4 ::: 735
#pragma line 29 "/usr/include/math.h" 2 3 4 ::: 736
#pragma line 1 "/usr/include/bits/huge_val.h" 1 3 4 ::: 743
#pragma line 35 "/usr/include/math.h" 2 3 4 ::: 770
#pragma line 46 "/usr/include/math.h" 3 4 ::: 771
#pragma line 1 "/usr/include/bits/mathdef.h" 1 3 4 ::: 774
#pragma line 48 "/usr/include/math.h" 2 3 4 ::: 792
#pragma line 71 "/usr/include/math.h" 3 4 ::: 798
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 799
#pragma line 88 "/usr/include/bits/mathcalls.h" 3 4 ::: 877
#pragma line 128 "/usr/include/bits/mathcalls.h" 3 4 ::: 907
#pragma line 150 "/usr/include/bits/mathcalls.h" 3 4 ::: 916
#pragma line 230 "/usr/include/bits/mathcalls.h" 3 4 ::: 986
#pragma line 264 "/usr/include/bits/mathcalls.h" 3 4 ::: 1010
#pragma line 363 "/usr/include/bits/mathcalls.h" 3 4 ::: 1045
#pragma line 72 "/usr/include/math.h" 2 3 4 ::: 1048
#pragma line 94 "/usr/include/math.h" 3 4 ::: 1059
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 1060
#pragma line 88 "/usr/include/bits/mathcalls.h" 3 4 ::: 1138
#pragma line 128 "/usr/include/bits/mathcalls.h" 3 4 ::: 1168
#pragma line 150 "/usr/include/bits/mathcalls.h" 3 4 ::: 1177
#pragma line 230 "/usr/include/bits/mathcalls.h" 3 4 ::: 1247
#pragma line 264 "/usr/include/bits/mathcalls.h" 3 4 ::: 1271
#pragma line 363 "/usr/include/bits/mathcalls.h" 3 4 ::: 1306
#pragma line 95 "/usr/include/math.h" 2 3 4 ::: 1309
#pragma line 141 "/usr/include/math.h" 3 4 ::: 1310
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 1311
#pragma line 88 "/usr/include/bits/mathcalls.h" 3 4 ::: 1389
#pragma line 128 "/usr/include/bits/mathcalls.h" 3 4 ::: 1419
#pragma line 150 "/usr/include/bits/mathcalls.h" 3 4 ::: 1428
#pragma line 230 "/usr/include/bits/mathcalls.h" 3 4 ::: 1498
#pragma line 264 "/usr/include/bits/mathcalls.h" 3 4 ::: 1522
#pragma line 363 "/usr/include/bits/mathcalls.h" 3 4 ::: 1557
#pragma line 142 "/usr/include/math.h" 2 3 4 ::: 1560
#pragma line 156 "/usr/include/math.h" 3 4 ::: 1561
#pragma line 283 "/usr/include/math.h" 3 4 ::: 1568
#pragma line 348 "/usr/include/math.h" 3 4 ::: 1622
#pragma line 365 "/usr/include/math.h" 3 4 ::: 1624
#pragma line 385 "/usr/include/math.h" 3 4 ::: 1628
#pragma line 407 "/usr/include/math.h" 3 4 ::: 1632
#pragma line 6 "./black_scholes.h" 2 ::: 1634
#pragma line 1 "/usr/include/assert.h" 1 3 4 ::: 1636
#pragma line 44 "/usr/include/assert.h" 3 4 ::: 1658
#pragma line 67 "/usr/include/assert.h" 3 4 ::: 1663
#pragma line 101 "/usr/include/assert.h" 3 4 ::: 1680
#pragma line 8 "./black_scholes.h" 2 ::: 1686
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 1687
#pragma line 34 "/usr/include/stdio.h" 3 4 ::: 1710
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1711
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1752
#pragma line 35 "/usr/include/stdio.h" 2 3 4 ::: 1755
#pragma line 1 "/usr/include/bits/types.h" 1 3 4 ::: 1757
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 1786
#pragma line 29 "/usr/include/bits/types.h" 2 3 4 ::: 1788
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1791
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1816
#pragma line 32 "/usr/include/bits/types.h" 2 3 4 ::: 1819
#pragma line 73 "/usr/include/bits/types.h" 3 4 ::: 1846
#pragma line 129 "/usr/include/bits/types.h" 3 4 ::: 1875
#pragma line 1 "/usr/include/bits/typesizes.h" 1 3 4 ::: 1882
#pragma line 27 "/usr/include/bits/typesizes.h" 3 4 ::: 1901
#pragma line 62 "/usr/include/bits/typesizes.h" 3 4 ::: 1904
#pragma line 135 "/usr/include/bits/types.h" 2 3 4 ::: 1906
#pragma line 37 "/usr/include/stdio.h" 2 3 4 ::: 1968
#pragma line 61 "/usr/include/stdio.h" 3 4 ::: 1979
#pragma line 72 "/usr/include/stdio.h" 3 4 ::: 1982
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 1983
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 2016
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2031
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2056
#pragma line 15 "/usr/include/_G_config.h" 2 3 4 ::: 2063
#pragma line 24 "/usr/include/_G_config.h" 3 4 ::: 2064
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 2065
#pragma line 48 "/usr/include/wchar.h" 3 4 ::: 2088
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2089
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2114
#pragma line 49 "/usr/include/wchar.h" 2 3 4 ::: 2117
#pragma line 1 "/usr/include/bits/wchar.h" 1 3 4 ::: 2119
#pragma line 51 "/usr/include/wchar.h" 2 3 4 ::: 2138
#pragma line 62 "/usr/include/wchar.h" 3 4 ::: 2142
#pragma line 75 "/usr/include/wchar.h" 3 4 ::: 2145
#pragma line 25 "/usr/include/_G_config.h" 2 3 4 ::: 2162
#pragma line 44 "/usr/include/_G_config.h" 3 4 ::: 2174
#pragma line 1 "/usr/include/gconv.h" 1 3 4 ::: 2175
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 2204
#pragma line 48 "/usr/include/wchar.h" 3 4 ::: 2227
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2228
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2253
#pragma line 49 "/usr/include/wchar.h" 2 3 4 ::: 2256
#pragma line 62 "/usr/include/wchar.h" 3 4 ::: 2262
#pragma line 89 "/usr/include/wchar.h" 3 4 ::: 2265
#pragma line 29 "/usr/include/gconv.h" 2 3 4 ::: 2268
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2271
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2296
#pragma line 32 "/usr/include/gconv.h" 2 3 4 ::: 2299
#pragma line 45 "/usr/include/_G_config.h" 2 3 4 ::: 2446
#pragma line 84 "/usr/include/_G_config.h" 3 4 ::: 2466
#pragma line 33 "/usr/include/libio.h" 2 3 4 ::: 2473
#pragma line 51 "/usr/include/libio.h" 3 4 ::: 2475
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 2479
#pragma line 54 "/usr/include/libio.h" 2 3 4 ::: 2528
#pragma line 74 "/usr/include/libio.h" 3 4 ::: 2529
#pragma line 114 "/usr/include/libio.h" 3 4 ::: 2531
#pragma line 147 "/usr/include/libio.h" 3 4 ::: 2537
#pragma line 167 "/usr/include/libio.h" 3 4 ::: 2539
#pragma line 200 "/usr/include/libio.h" 3 4 ::: 2563
#pragma line 268 "/usr/include/libio.h" 3 4 ::: 2574
#pragma line 316 "/usr/include/libio.h" 3 4 ::: 2615
#pragma line 325 "/usr/include/libio.h" 3 4 ::: 2617
#pragma line 357 "/usr/include/libio.h" 3 4 ::: 2639
#pragma line 413 "/usr/include/libio.h" 3 4 ::: 2665
#pragma line 451 "/usr/include/libio.h" 3 4 ::: 2672
#pragma line 481 "/usr/include/libio.h" 3 4 ::: 2687
#pragma line 73 "/usr/include/stdio.h" 2 3 4 ::: 2699
#pragma line 85 "/usr/include/stdio.h" 3 4 ::: 2700
#pragma line 97 "/usr/include/stdio.h" 3 4 ::: 2705
#pragma line 1 "/usr/include/bits/stdio_lim.h" 1 3 4 ::: 2748
#pragma line 139 "/usr/include/stdio.h" 2 3 4 ::: 2766
#pragma line 166 "/usr/include/stdio.h" 3 4 ::: 2785
#pragma line 184 "/usr/include/stdio.h" 3 4 ::: 2792
#pragma line 244 "/usr/include/stdio.h" 3 4 ::: 2838
#pragma line 279 "/usr/include/stdio.h" 3 4 ::: 2852
#pragma line 301 "/usr/include/stdio.h" 3 4 ::: 2855
#pragma line 395 "/usr/include/stdio.h" 3 4 ::: 2919
#pragma line 437 "/usr/include/stdio.h" 3 4 ::: 2934
#pragma line 586 "/usr/include/stdio.h" 3 4 ::: 3039
#pragma line 632 "/usr/include/stdio.h" 3 4 ::: 3072
#pragma line 695 "/usr/include/stdio.h" 3 4 ::: 3121
#pragma line 726 "/usr/include/stdio.h" 3 4 ::: 3132
#pragma line 1 "/usr/include/bits/sys_errlist.h" 1 3 4 ::: 3162
#pragma line 755 "/usr/include/stdio.h" 2 3 4 ::: 3191
#pragma line 811 "/usr/include/stdio.h" 3 4 ::: 3224
#pragma line 832 "/usr/include/stdio.h" 3 4 ::: 3236
#pragma line 9 "./black_scholes.h" 2 ::: 3239
#pragma line 1 "/usr/include/stdlib.h" 1 3 4 ::: 3240
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3274
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3299
#pragma line 34 "/usr/include/stdlib.h" 2 3 4 ::: 3302
#pragma line 97 "/usr/include/stdlib.h" 3 4 ::: 3303
#pragma line 128 "/usr/include/stdlib.h" 3 4 ::: 3318
#pragma line 183 "/usr/include/stdlib.h" 3 4 ::: 3359
#pragma line 276 "/usr/include/stdlib.h" 3 4 ::: 3395
#pragma line 426 "/usr/include/stdlib.h" 3 4 ::: 3439
#pragma line 1 "/usr/include/sys/types.h" 1 3 4 ::: 3453
#pragma line 35 "/usr/include/sys/types.h" 3 4 ::: 3476
#pragma line 62 "/usr/include/sys/types.h" 3 4 ::: 3493
#pragma line 100 "/usr/include/sys/types.h" 3 4 ::: 3521
#pragma line 133 "/usr/include/sys/types.h" 3 4 ::: 3546
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 3547
#pragma line 76 "/usr/include/time.h" 3 4 ::: 3570
#pragma line 92 "/usr/include/time.h" 3 4 ::: 3573
#pragma line 104 "/usr/include/time.h" 3 4 ::: 3576
#pragma line 134 "/usr/include/sys/types.h" 2 3 4 ::: 3579
#pragma line 147 "/usr/include/sys/types.h" 3 4 ::: 3580
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3581
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3606
#pragma line 148 "/usr/include/sys/types.h" 2 3 4 ::: 3609
#pragma line 187 "/usr/include/sys/types.h" 3 4 ::: 3619
#pragma line 1 "/usr/include/endian.h" 1 3 4 ::: 3651
#pragma line 1 "/usr/include/bits/endian.h" 1 3 4 ::: 3689
#pragma line 38 "/usr/include/endian.h" 2 3 4 ::: 3691
#pragma line 218 "/usr/include/sys/types.h" 2 3 4 ::: 3695
#pragma line 1 "/usr/include/sys/select.h" 1 3 4 ::: 3699
#pragma line 1 "/usr/include/bits/select.h" 1 3 4 ::: 3731
#pragma line 32 "/usr/include/sys/select.h" 2 3 4 ::: 3757
#pragma line 1 "/usr/include/bits/sigset.h" 1 3 4 ::: 3761
#pragma line 35 "/usr/include/sys/select.h" 2 3 4 ::: 3802
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 3813
#pragma line 119 "/usr/include/time.h" 3 4 ::: 3836
#pragma line 45 "/usr/include/sys/select.h" 2 3 4 ::: 3844
#pragma line 1 "/usr/include/bits/time.h" 1 3 4 ::: 3846
#pragma line 67 "/usr/include/bits/time.h" 3 4 ::: 3869
#pragma line 47 "/usr/include/sys/select.h" 2 3 4 ::: 3877
#pragma line 101 "/usr/include/sys/select.h" 3 4 ::: 3924
#pragma line 221 "/usr/include/sys/types.h" 2 3 4 ::: 3950
#pragma line 1 "/usr/include/sys/sysmacros.h" 1 3 4 ::: 3954
#pragma line 224 "/usr/include/sys/types.h" 2 3 4 ::: 4018
#pragma line 268 "/usr/include/sys/types.h" 3 4 ::: 4039
#pragma line 1 "/usr/include/bits/pthreadtypes.h" 1 3 4 ::: 4043
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 4067
#pragma line 24 "/usr/include/bits/pthreadtypes.h" 2 3 4 ::: 4069
#pragma line 48 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 4070
#pragma line 74 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 4089
#pragma line 101 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 4108
#pragma line 187 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 4177
#pragma line 271 "/usr/include/sys/types.h" 2 3 4 ::: 4208
#pragma line 439 "/usr/include/stdlib.h" 2 3 4 ::: 4209
#pragma line 588 "/usr/include/stdlib.h" 3 4 ::: 4351
#pragma line 1 "/usr/include/alloca.h" 1 3 4 ::: 4377
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 4403
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 4428
#pragma line 26 "/usr/include/alloca.h" 2 3 4 ::: 4431
#pragma line 613 "/usr/include/stdlib.h" 2 3 4 ::: 4440
#pragma line 659 "/usr/include/stdlib.h" 3 4 ::: 4475
#pragma line 724 "/usr/include/stdlib.h" 3 4 ::: 4527
#pragma line 751 "/usr/include/stdlib.h" 3 4 ::: 4543
#pragma line 796 "/usr/include/stdlib.h" 3 4 ::: 4580
#pragma line 815 "/usr/include/stdlib.h" 3 4 ::: 4588
#pragma line 922 "/usr/include/stdlib.h" 3 4 ::: 4673
#pragma line 958 "/usr/include/stdlib.h" 3 4 ::: 4679
#pragma line 10 "./black_scholes.h" 2 ::: 4689
#pragma line 2 "black_scholes.c" 2 ::: 4737
#pragma line 1 "/usr/include/assert.h" 1 3 4 ::: 4741
#pragma line 44 "/usr/include/assert.h" 3 4 ::: 4763
#pragma line 67 "/usr/include/assert.h" 3 4 ::: 4768
#pragma line 101 "/usr/include/assert.h" 3 4 ::: 4785
#pragma line 6 "black_scholes.c" 2 ::: 4791
