#pragma line 1 "black_scholes.c" ::: -10
#pragma line 1 "black_scholes.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 149 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 2
#pragma line 278 "/opt/xilinx/Vivado_HLS/2014.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 55
#pragma line 8 "<command line>" 2 ::: 181
#pragma line 1 "<built-in>" 2 ::: 182
#pragma line 1 "black_scholes.c" 2 ::: 183
#pragma line 1 "./black_scholes.h" 1 ::: 184
#pragma line 1 "./gaussian.h" 1 ::: 188
#pragma line 1 "./util.h" 1 ::: 201
#pragma line 13 "./gaussian.h" 2 ::: 251
#pragma line 5 "./black_scholes.h" 2 ::: 273
#pragma line 1 "/usr/include/math.h" 1 3 4 ::: 274
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 303
#pragma line 115 "/usr/include/features.h" 3 4 ::: 396
#pragma line 139 "/usr/include/features.h" 3 4 ::: 413
#pragma line 169 "/usr/include/features.h" 3 4 ::: 423
#pragma line 179 "/usr/include/features.h" 3 4 ::: 426
#pragma line 294 "/usr/include/features.h" 3 4 ::: 438
#pragma line 1 "/usr/include/sys/cdefs.h" 1 3 4 ::: 475
#pragma line 72 "/usr/include/sys/cdefs.h" 3 4 ::: 521
#pragma line 98 "/usr/include/sys/cdefs.h" 3 4 ::: 539
#pragma line 111 "/usr/include/sys/cdefs.h" 3 4 ::: 545
#pragma line 123 "/usr/include/sys/cdefs.h" 3 4 ::: 549
#pragma line 155 "/usr/include/sys/cdefs.h" 3 4 ::: 567
#pragma line 178 "/usr/include/sys/cdefs.h" 3 4 ::: 577
#pragma line 222 "/usr/include/sys/cdefs.h" 3 4 ::: 614
#pragma line 275 "/usr/include/sys/cdefs.h" 3 4 ::: 655
#pragma line 313 "/usr/include/sys/cdefs.h" 3 4 ::: 679
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 680
#pragma line 314 "/usr/include/sys/cdefs.h" 2 3 4 ::: 682
#pragma line 330 "/usr/include/features.h" 2 3 4 ::: 683
#pragma line 1 "/usr/include/gnu/stubs.h" 1 3 4 ::: 707
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 712
#pragma line 5 "/usr/include/gnu/stubs.h" 2 3 4 ::: 714
#pragma line 1 "/usr/include/gnu/stubs-64.h" 1 3 4 ::: 719
#pragma line 10 "/usr/include/gnu/stubs.h" 2 3 4 ::: 724
#pragma line 353 "/usr/include/features.h" 2 3 4 ::: 725
#pragma line 29 "/usr/include/math.h" 2 3 4 ::: 726
#pragma line 1 "/usr/include/bits/huge_val.h" 1 3 4 ::: 733
#pragma line 35 "/usr/include/math.h" 2 3 4 ::: 760
#pragma line 46 "/usr/include/math.h" 3 4 ::: 761
#pragma line 1 "/usr/include/bits/mathdef.h" 1 3 4 ::: 764
#pragma line 48 "/usr/include/math.h" 2 3 4 ::: 782
#pragma line 71 "/usr/include/math.h" 3 4 ::: 788
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 789
#pragma line 88 "/usr/include/bits/mathcalls.h" 3 4 ::: 867
#pragma line 128 "/usr/include/bits/mathcalls.h" 3 4 ::: 897
#pragma line 150 "/usr/include/bits/mathcalls.h" 3 4 ::: 906
#pragma line 230 "/usr/include/bits/mathcalls.h" 3 4 ::: 976
#pragma line 264 "/usr/include/bits/mathcalls.h" 3 4 ::: 1000
#pragma line 363 "/usr/include/bits/mathcalls.h" 3 4 ::: 1035
#pragma line 72 "/usr/include/math.h" 2 3 4 ::: 1038
#pragma line 94 "/usr/include/math.h" 3 4 ::: 1049
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 1050
#pragma line 88 "/usr/include/bits/mathcalls.h" 3 4 ::: 1128
#pragma line 128 "/usr/include/bits/mathcalls.h" 3 4 ::: 1158
#pragma line 150 "/usr/include/bits/mathcalls.h" 3 4 ::: 1167
#pragma line 230 "/usr/include/bits/mathcalls.h" 3 4 ::: 1237
#pragma line 264 "/usr/include/bits/mathcalls.h" 3 4 ::: 1261
#pragma line 363 "/usr/include/bits/mathcalls.h" 3 4 ::: 1296
#pragma line 95 "/usr/include/math.h" 2 3 4 ::: 1299
#pragma line 141 "/usr/include/math.h" 3 4 ::: 1300
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 1301
#pragma line 88 "/usr/include/bits/mathcalls.h" 3 4 ::: 1379
#pragma line 128 "/usr/include/bits/mathcalls.h" 3 4 ::: 1409
#pragma line 150 "/usr/include/bits/mathcalls.h" 3 4 ::: 1418
#pragma line 230 "/usr/include/bits/mathcalls.h" 3 4 ::: 1488
#pragma line 264 "/usr/include/bits/mathcalls.h" 3 4 ::: 1512
#pragma line 363 "/usr/include/bits/mathcalls.h" 3 4 ::: 1547
#pragma line 142 "/usr/include/math.h" 2 3 4 ::: 1550
#pragma line 156 "/usr/include/math.h" 3 4 ::: 1551
#pragma line 283 "/usr/include/math.h" 3 4 ::: 1558
#pragma line 348 "/usr/include/math.h" 3 4 ::: 1612
#pragma line 365 "/usr/include/math.h" 3 4 ::: 1614
#pragma line 385 "/usr/include/math.h" 3 4 ::: 1618
#pragma line 407 "/usr/include/math.h" 3 4 ::: 1622
#pragma line 6 "./black_scholes.h" 2 ::: 1624
#pragma line 1 "/usr/include/assert.h" 1 3 4 ::: 1626
#pragma line 44 "/usr/include/assert.h" 3 4 ::: 1648
#pragma line 67 "/usr/include/assert.h" 3 4 ::: 1653
#pragma line 101 "/usr/include/assert.h" 3 4 ::: 1670
#pragma line 8 "./black_scholes.h" 2 ::: 1676
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 1677
#pragma line 34 "/usr/include/stdio.h" 3 4 ::: 1700
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1701
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1742
#pragma line 35 "/usr/include/stdio.h" 2 3 4 ::: 1745
#pragma line 1 "/usr/include/bits/types.h" 1 3 4 ::: 1747
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 1776
#pragma line 29 "/usr/include/bits/types.h" 2 3 4 ::: 1778
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1781
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1806
#pragma line 32 "/usr/include/bits/types.h" 2 3 4 ::: 1809
#pragma line 73 "/usr/include/bits/types.h" 3 4 ::: 1836
#pragma line 129 "/usr/include/bits/types.h" 3 4 ::: 1865
#pragma line 1 "/usr/include/bits/typesizes.h" 1 3 4 ::: 1872
#pragma line 27 "/usr/include/bits/typesizes.h" 3 4 ::: 1891
#pragma line 62 "/usr/include/bits/typesizes.h" 3 4 ::: 1894
#pragma line 135 "/usr/include/bits/types.h" 2 3 4 ::: 1896
#pragma line 37 "/usr/include/stdio.h" 2 3 4 ::: 1958
#pragma line 61 "/usr/include/stdio.h" 3 4 ::: 1969
#pragma line 72 "/usr/include/stdio.h" 3 4 ::: 1972
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 1973
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 2006
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2021
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2046
#pragma line 15 "/usr/include/_G_config.h" 2 3 4 ::: 2053
#pragma line 24 "/usr/include/_G_config.h" 3 4 ::: 2054
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 2055
#pragma line 48 "/usr/include/wchar.h" 3 4 ::: 2078
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2079
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2104
#pragma line 49 "/usr/include/wchar.h" 2 3 4 ::: 2107
#pragma line 1 "/usr/include/bits/wchar.h" 1 3 4 ::: 2109
#pragma line 51 "/usr/include/wchar.h" 2 3 4 ::: 2128
#pragma line 62 "/usr/include/wchar.h" 3 4 ::: 2132
#pragma line 75 "/usr/include/wchar.h" 3 4 ::: 2135
#pragma line 25 "/usr/include/_G_config.h" 2 3 4 ::: 2152
#pragma line 44 "/usr/include/_G_config.h" 3 4 ::: 2164
#pragma line 1 "/usr/include/gconv.h" 1 3 4 ::: 2165
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 2194
#pragma line 48 "/usr/include/wchar.h" 3 4 ::: 2217
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2218
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2243
#pragma line 49 "/usr/include/wchar.h" 2 3 4 ::: 2246
#pragma line 62 "/usr/include/wchar.h" 3 4 ::: 2252
#pragma line 89 "/usr/include/wchar.h" 3 4 ::: 2255
#pragma line 29 "/usr/include/gconv.h" 2 3 4 ::: 2258
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2261
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2286
#pragma line 32 "/usr/include/gconv.h" 2 3 4 ::: 2289
#pragma line 45 "/usr/include/_G_config.h" 2 3 4 ::: 2436
#pragma line 84 "/usr/include/_G_config.h" 3 4 ::: 2456
#pragma line 33 "/usr/include/libio.h" 2 3 4 ::: 2463
#pragma line 51 "/usr/include/libio.h" 3 4 ::: 2465
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 2469
#pragma line 54 "/usr/include/libio.h" 2 3 4 ::: 2518
#pragma line 74 "/usr/include/libio.h" 3 4 ::: 2519
#pragma line 114 "/usr/include/libio.h" 3 4 ::: 2521
#pragma line 147 "/usr/include/libio.h" 3 4 ::: 2527
#pragma line 167 "/usr/include/libio.h" 3 4 ::: 2529
#pragma line 200 "/usr/include/libio.h" 3 4 ::: 2553
#pragma line 268 "/usr/include/libio.h" 3 4 ::: 2564
#pragma line 316 "/usr/include/libio.h" 3 4 ::: 2605
#pragma line 325 "/usr/include/libio.h" 3 4 ::: 2607
#pragma line 357 "/usr/include/libio.h" 3 4 ::: 2629
#pragma line 413 "/usr/include/libio.h" 3 4 ::: 2655
#pragma line 451 "/usr/include/libio.h" 3 4 ::: 2662
#pragma line 481 "/usr/include/libio.h" 3 4 ::: 2677
#pragma line 73 "/usr/include/stdio.h" 2 3 4 ::: 2689
#pragma line 85 "/usr/include/stdio.h" 3 4 ::: 2690
#pragma line 97 "/usr/include/stdio.h" 3 4 ::: 2695
#pragma line 1 "/usr/include/bits/stdio_lim.h" 1 3 4 ::: 2738
#pragma line 139 "/usr/include/stdio.h" 2 3 4 ::: 2756
#pragma line 166 "/usr/include/stdio.h" 3 4 ::: 2775
#pragma line 184 "/usr/include/stdio.h" 3 4 ::: 2782
#pragma line 244 "/usr/include/stdio.h" 3 4 ::: 2828
#pragma line 279 "/usr/include/stdio.h" 3 4 ::: 2842
#pragma line 301 "/usr/include/stdio.h" 3 4 ::: 2845
#pragma line 395 "/usr/include/stdio.h" 3 4 ::: 2909
#pragma line 437 "/usr/include/stdio.h" 3 4 ::: 2924
#pragma line 586 "/usr/include/stdio.h" 3 4 ::: 3029
#pragma line 632 "/usr/include/stdio.h" 3 4 ::: 3062
#pragma line 695 "/usr/include/stdio.h" 3 4 ::: 3111
#pragma line 726 "/usr/include/stdio.h" 3 4 ::: 3122
#pragma line 1 "/usr/include/bits/sys_errlist.h" 1 3 4 ::: 3152
#pragma line 755 "/usr/include/stdio.h" 2 3 4 ::: 3181
#pragma line 811 "/usr/include/stdio.h" 3 4 ::: 3214
#pragma line 832 "/usr/include/stdio.h" 3 4 ::: 3226
#pragma line 9 "./black_scholes.h" 2 ::: 3229
#pragma line 1 "/usr/include/stdlib.h" 1 3 4 ::: 3230
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3264
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3289
#pragma line 34 "/usr/include/stdlib.h" 2 3 4 ::: 3292
#pragma line 97 "/usr/include/stdlib.h" 3 4 ::: 3293
#pragma line 128 "/usr/include/stdlib.h" 3 4 ::: 3308
#pragma line 183 "/usr/include/stdlib.h" 3 4 ::: 3349
#pragma line 276 "/usr/include/stdlib.h" 3 4 ::: 3385
#pragma line 426 "/usr/include/stdlib.h" 3 4 ::: 3429
#pragma line 1 "/usr/include/sys/types.h" 1 3 4 ::: 3443
#pragma line 35 "/usr/include/sys/types.h" 3 4 ::: 3466
#pragma line 62 "/usr/include/sys/types.h" 3 4 ::: 3483
#pragma line 100 "/usr/include/sys/types.h" 3 4 ::: 3511
#pragma line 133 "/usr/include/sys/types.h" 3 4 ::: 3536
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 3537
#pragma line 76 "/usr/include/time.h" 3 4 ::: 3560
#pragma line 92 "/usr/include/time.h" 3 4 ::: 3563
#pragma line 104 "/usr/include/time.h" 3 4 ::: 3566
#pragma line 134 "/usr/include/sys/types.h" 2 3 4 ::: 3569
#pragma line 147 "/usr/include/sys/types.h" 3 4 ::: 3570
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3571
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3596
#pragma line 148 "/usr/include/sys/types.h" 2 3 4 ::: 3599
#pragma line 187 "/usr/include/sys/types.h" 3 4 ::: 3609
#pragma line 1 "/usr/include/endian.h" 1 3 4 ::: 3641
#pragma line 1 "/usr/include/bits/endian.h" 1 3 4 ::: 3679
#pragma line 38 "/usr/include/endian.h" 2 3 4 ::: 3681
#pragma line 218 "/usr/include/sys/types.h" 2 3 4 ::: 3685
#pragma line 1 "/usr/include/sys/select.h" 1 3 4 ::: 3689
#pragma line 1 "/usr/include/bits/select.h" 1 3 4 ::: 3721
#pragma line 32 "/usr/include/sys/select.h" 2 3 4 ::: 3747
#pragma line 1 "/usr/include/bits/sigset.h" 1 3 4 ::: 3751
#pragma line 35 "/usr/include/sys/select.h" 2 3 4 ::: 3792
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 3803
#pragma line 119 "/usr/include/time.h" 3 4 ::: 3826
#pragma line 45 "/usr/include/sys/select.h" 2 3 4 ::: 3834
#pragma line 1 "/usr/include/bits/time.h" 1 3 4 ::: 3836
#pragma line 67 "/usr/include/bits/time.h" 3 4 ::: 3859
#pragma line 47 "/usr/include/sys/select.h" 2 3 4 ::: 3867
#pragma line 101 "/usr/include/sys/select.h" 3 4 ::: 3914
#pragma line 221 "/usr/include/sys/types.h" 2 3 4 ::: 3940
#pragma line 1 "/usr/include/sys/sysmacros.h" 1 3 4 ::: 3944
#pragma line 224 "/usr/include/sys/types.h" 2 3 4 ::: 4008
#pragma line 268 "/usr/include/sys/types.h" 3 4 ::: 4029
#pragma line 1 "/usr/include/bits/pthreadtypes.h" 1 3 4 ::: 4033
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 4057
#pragma line 24 "/usr/include/bits/pthreadtypes.h" 2 3 4 ::: 4059
#pragma line 48 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 4060
#pragma line 74 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 4079
#pragma line 101 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 4098
#pragma line 187 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 4167
#pragma line 271 "/usr/include/sys/types.h" 2 3 4 ::: 4198
#pragma line 439 "/usr/include/stdlib.h" 2 3 4 ::: 4199
#pragma line 588 "/usr/include/stdlib.h" 3 4 ::: 4341
#pragma line 1 "/usr/include/alloca.h" 1 3 4 ::: 4367
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 4393
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 4418
#pragma line 26 "/usr/include/alloca.h" 2 3 4 ::: 4421
#pragma line 613 "/usr/include/stdlib.h" 2 3 4 ::: 4430
#pragma line 659 "/usr/include/stdlib.h" 3 4 ::: 4465
#pragma line 724 "/usr/include/stdlib.h" 3 4 ::: 4517
#pragma line 751 "/usr/include/stdlib.h" 3 4 ::: 4533
#pragma line 796 "/usr/include/stdlib.h" 3 4 ::: 4570
#pragma line 815 "/usr/include/stdlib.h" 3 4 ::: 4578
#pragma line 922 "/usr/include/stdlib.h" 3 4 ::: 4663
#pragma line 958 "/usr/include/stdlib.h" 3 4 ::: 4669
#pragma line 10 "./black_scholes.h" 2 ::: 4679
#pragma line 2 "black_scholes.c" 2 ::: 4727
#pragma line 1 "/usr/include/assert.h" 1 3 4 ::: 4731
#pragma line 44 "/usr/include/assert.h" 3 4 ::: 4753
#pragma line 67 "/usr/include/assert.h" 3 4 ::: 4758
#pragma line 101 "/usr/include/assert.h" 3 4 ::: 4775
#pragma line 6 "black_scholes.c" 2 ::: 4781
