#pragma line 1 "gaussian.c" ::: -10
#pragma line 1 "gaussian.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 149 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 2
#pragma line 278 "/opt/xilinx/Vivado_HLS/2014.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 55
#pragma line 8 "<command line>" 2 ::: 181
#pragma line 1 "<built-in>" 2 ::: 182
#pragma line 1 "gaussian.c" 2 ::: 183
#pragma line 1 "./gaussian.h" 1 ::: 184
#pragma line 1 "./util.h" 1 ::: 197
#pragma line 13 "./gaussian.h" 2 ::: 247
#pragma line 2 "gaussian.c" 2 ::: 269
#pragma line 1 "/usr/include/math.h" 1 3 4 ::: 270
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 299
#pragma line 115 "/usr/include/features.h" 3 4 ::: 392
#pragma line 139 "/usr/include/features.h" 3 4 ::: 409
#pragma line 169 "/usr/include/features.h" 3 4 ::: 419
#pragma line 179 "/usr/include/features.h" 3 4 ::: 422
#pragma line 294 "/usr/include/features.h" 3 4 ::: 434
#pragma line 1 "/usr/include/sys/cdefs.h" 1 3 4 ::: 471
#pragma line 72 "/usr/include/sys/cdefs.h" 3 4 ::: 517
#pragma line 98 "/usr/include/sys/cdefs.h" 3 4 ::: 535
#pragma line 111 "/usr/include/sys/cdefs.h" 3 4 ::: 541
#pragma line 123 "/usr/include/sys/cdefs.h" 3 4 ::: 545
#pragma line 155 "/usr/include/sys/cdefs.h" 3 4 ::: 563
#pragma line 178 "/usr/include/sys/cdefs.h" 3 4 ::: 573
#pragma line 222 "/usr/include/sys/cdefs.h" 3 4 ::: 610
#pragma line 275 "/usr/include/sys/cdefs.h" 3 4 ::: 651
#pragma line 313 "/usr/include/sys/cdefs.h" 3 4 ::: 675
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 676
#pragma line 314 "/usr/include/sys/cdefs.h" 2 3 4 ::: 678
#pragma line 330 "/usr/include/features.h" 2 3 4 ::: 679
#pragma line 1 "/usr/include/gnu/stubs.h" 1 3 4 ::: 703
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 708
#pragma line 5 "/usr/include/gnu/stubs.h" 2 3 4 ::: 710
#pragma line 1 "/usr/include/gnu/stubs-64.h" 1 3 4 ::: 715
#pragma line 10 "/usr/include/gnu/stubs.h" 2 3 4 ::: 720
#pragma line 353 "/usr/include/features.h" 2 3 4 ::: 721
#pragma line 29 "/usr/include/math.h" 2 3 4 ::: 722
#pragma line 1 "/usr/include/bits/huge_val.h" 1 3 4 ::: 729
#pragma line 35 "/usr/include/math.h" 2 3 4 ::: 756
#pragma line 46 "/usr/include/math.h" 3 4 ::: 757
#pragma line 1 "/usr/include/bits/mathdef.h" 1 3 4 ::: 760
#pragma line 48 "/usr/include/math.h" 2 3 4 ::: 778
#pragma line 71 "/usr/include/math.h" 3 4 ::: 784
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 785
#pragma line 88 "/usr/include/bits/mathcalls.h" 3 4 ::: 863
#pragma line 128 "/usr/include/bits/mathcalls.h" 3 4 ::: 893
#pragma line 150 "/usr/include/bits/mathcalls.h" 3 4 ::: 902
#pragma line 230 "/usr/include/bits/mathcalls.h" 3 4 ::: 972
#pragma line 264 "/usr/include/bits/mathcalls.h" 3 4 ::: 996
#pragma line 363 "/usr/include/bits/mathcalls.h" 3 4 ::: 1031
#pragma line 72 "/usr/include/math.h" 2 3 4 ::: 1034
#pragma line 94 "/usr/include/math.h" 3 4 ::: 1045
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 1046
#pragma line 88 "/usr/include/bits/mathcalls.h" 3 4 ::: 1124
#pragma line 128 "/usr/include/bits/mathcalls.h" 3 4 ::: 1154
#pragma line 150 "/usr/include/bits/mathcalls.h" 3 4 ::: 1163
#pragma line 230 "/usr/include/bits/mathcalls.h" 3 4 ::: 1233
#pragma line 264 "/usr/include/bits/mathcalls.h" 3 4 ::: 1257
#pragma line 363 "/usr/include/bits/mathcalls.h" 3 4 ::: 1292
#pragma line 95 "/usr/include/math.h" 2 3 4 ::: 1295
#pragma line 141 "/usr/include/math.h" 3 4 ::: 1296
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 1297
#pragma line 88 "/usr/include/bits/mathcalls.h" 3 4 ::: 1375
#pragma line 128 "/usr/include/bits/mathcalls.h" 3 4 ::: 1405
#pragma line 150 "/usr/include/bits/mathcalls.h" 3 4 ::: 1414
#pragma line 230 "/usr/include/bits/mathcalls.h" 3 4 ::: 1484
#pragma line 264 "/usr/include/bits/mathcalls.h" 3 4 ::: 1508
#pragma line 363 "/usr/include/bits/mathcalls.h" 3 4 ::: 1543
#pragma line 142 "/usr/include/math.h" 2 3 4 ::: 1546
#pragma line 156 "/usr/include/math.h" 3 4 ::: 1547
#pragma line 283 "/usr/include/math.h" 3 4 ::: 1554
#pragma line 348 "/usr/include/math.h" 3 4 ::: 1608
#pragma line 365 "/usr/include/math.h" 3 4 ::: 1610
#pragma line 385 "/usr/include/math.h" 3 4 ::: 1614
#pragma line 407 "/usr/include/math.h" 3 4 ::: 1618
#pragma line 3 "gaussian.c" 2 ::: 1620
#pragma line 1 "./mt19937ar.h" 1 ::: 1621
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 1666
#pragma line 34 "/usr/include/stdio.h" 3 4 ::: 1689
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1690
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1731
#pragma line 35 "/usr/include/stdio.h" 2 3 4 ::: 1734
#pragma line 1 "/usr/include/bits/types.h" 1 3 4 ::: 1736
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 1765
#pragma line 29 "/usr/include/bits/types.h" 2 3 4 ::: 1767
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1770
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1795
#pragma line 32 "/usr/include/bits/types.h" 2 3 4 ::: 1798
#pragma line 73 "/usr/include/bits/types.h" 3 4 ::: 1825
#pragma line 129 "/usr/include/bits/types.h" 3 4 ::: 1854
#pragma line 1 "/usr/include/bits/typesizes.h" 1 3 4 ::: 1861
#pragma line 27 "/usr/include/bits/typesizes.h" 3 4 ::: 1880
#pragma line 62 "/usr/include/bits/typesizes.h" 3 4 ::: 1883
#pragma line 135 "/usr/include/bits/types.h" 2 3 4 ::: 1885
#pragma line 37 "/usr/include/stdio.h" 2 3 4 ::: 1947
#pragma line 61 "/usr/include/stdio.h" 3 4 ::: 1958
#pragma line 72 "/usr/include/stdio.h" 3 4 ::: 1961
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 1962
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 1995
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2010
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2035
#pragma line 15 "/usr/include/_G_config.h" 2 3 4 ::: 2042
#pragma line 24 "/usr/include/_G_config.h" 3 4 ::: 2043
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 2044
#pragma line 48 "/usr/include/wchar.h" 3 4 ::: 2067
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2068
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2093
#pragma line 49 "/usr/include/wchar.h" 2 3 4 ::: 2096
#pragma line 1 "/usr/include/bits/wchar.h" 1 3 4 ::: 2098
#pragma line 51 "/usr/include/wchar.h" 2 3 4 ::: 2117
#pragma line 62 "/usr/include/wchar.h" 3 4 ::: 2121
#pragma line 75 "/usr/include/wchar.h" 3 4 ::: 2124
#pragma line 25 "/usr/include/_G_config.h" 2 3 4 ::: 2141
#pragma line 44 "/usr/include/_G_config.h" 3 4 ::: 2153
#pragma line 1 "/usr/include/gconv.h" 1 3 4 ::: 2154
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 2183
#pragma line 48 "/usr/include/wchar.h" 3 4 ::: 2206
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2207
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2232
#pragma line 49 "/usr/include/wchar.h" 2 3 4 ::: 2235
#pragma line 62 "/usr/include/wchar.h" 3 4 ::: 2241
#pragma line 89 "/usr/include/wchar.h" 3 4 ::: 2244
#pragma line 29 "/usr/include/gconv.h" 2 3 4 ::: 2247
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2250
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2275
#pragma line 32 "/usr/include/gconv.h" 2 3 4 ::: 2278
#pragma line 45 "/usr/include/_G_config.h" 2 3 4 ::: 2425
#pragma line 84 "/usr/include/_G_config.h" 3 4 ::: 2445
#pragma line 33 "/usr/include/libio.h" 2 3 4 ::: 2452
#pragma line 51 "/usr/include/libio.h" 3 4 ::: 2454
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 2458
#pragma line 54 "/usr/include/libio.h" 2 3 4 ::: 2507
#pragma line 74 "/usr/include/libio.h" 3 4 ::: 2508
#pragma line 114 "/usr/include/libio.h" 3 4 ::: 2510
#pragma line 147 "/usr/include/libio.h" 3 4 ::: 2516
#pragma line 167 "/usr/include/libio.h" 3 4 ::: 2518
#pragma line 200 "/usr/include/libio.h" 3 4 ::: 2542
#pragma line 268 "/usr/include/libio.h" 3 4 ::: 2553
#pragma line 316 "/usr/include/libio.h" 3 4 ::: 2594
#pragma line 325 "/usr/include/libio.h" 3 4 ::: 2596
#pragma line 357 "/usr/include/libio.h" 3 4 ::: 2618
#pragma line 413 "/usr/include/libio.h" 3 4 ::: 2644
#pragma line 451 "/usr/include/libio.h" 3 4 ::: 2651
#pragma line 481 "/usr/include/libio.h" 3 4 ::: 2666
#pragma line 73 "/usr/include/stdio.h" 2 3 4 ::: 2678
#pragma line 85 "/usr/include/stdio.h" 3 4 ::: 2679
#pragma line 97 "/usr/include/stdio.h" 3 4 ::: 2684
#pragma line 1 "/usr/include/bits/stdio_lim.h" 1 3 4 ::: 2727
#pragma line 139 "/usr/include/stdio.h" 2 3 4 ::: 2745
#pragma line 166 "/usr/include/stdio.h" 3 4 ::: 2764
#pragma line 184 "/usr/include/stdio.h" 3 4 ::: 2771
#pragma line 244 "/usr/include/stdio.h" 3 4 ::: 2817
#pragma line 279 "/usr/include/stdio.h" 3 4 ::: 2831
#pragma line 301 "/usr/include/stdio.h" 3 4 ::: 2834
#pragma line 395 "/usr/include/stdio.h" 3 4 ::: 2898
#pragma line 437 "/usr/include/stdio.h" 3 4 ::: 2913
#pragma line 586 "/usr/include/stdio.h" 3 4 ::: 3018
#pragma line 632 "/usr/include/stdio.h" 3 4 ::: 3051
#pragma line 695 "/usr/include/stdio.h" 3 4 ::: 3100
#pragma line 726 "/usr/include/stdio.h" 3 4 ::: 3111
#pragma line 1 "/usr/include/bits/sys_errlist.h" 1 3 4 ::: 3141
#pragma line 755 "/usr/include/stdio.h" 2 3 4 ::: 3170
#pragma line 811 "/usr/include/stdio.h" 3 4 ::: 3203
#pragma line 832 "/usr/include/stdio.h" 3 4 ::: 3215
#pragma line 45 "./mt19937ar.h" 2 ::: 3218
#pragma line 4 "gaussian.c" 2 ::: 3233
