#pragma line 1 "gaussian.c" ::: 0
#pragma line 1 "gaussian.c" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 149 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 12
#pragma line 278 "/opt/xilinx/Vivado_HLS/2014.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 65
#pragma line 8 "<command line>" 2 ::: 191
#pragma line 1 "<built-in>" 2 ::: 192
#pragma line 1 "gaussian.c" 2 ::: 193
#pragma line 1 "./gaussian.h" 1 ::: 194
#pragma line 1 "./util.h" 1 ::: 207
#pragma line 13 "./gaussian.h" 2 ::: 257
#pragma line 2 "gaussian.c" 2 ::: 279
#pragma line 1 "/usr/include/math.h" 1 3 4 ::: 280
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 309
#pragma line 115 "/usr/include/features.h" 3 4 ::: 402
#pragma line 139 "/usr/include/features.h" 3 4 ::: 419
#pragma line 169 "/usr/include/features.h" 3 4 ::: 429
#pragma line 179 "/usr/include/features.h" 3 4 ::: 432
#pragma line 294 "/usr/include/features.h" 3 4 ::: 444
#pragma line 1 "/usr/include/sys/cdefs.h" 1 3 4 ::: 481
#pragma line 72 "/usr/include/sys/cdefs.h" 3 4 ::: 527
#pragma line 98 "/usr/include/sys/cdefs.h" 3 4 ::: 545
#pragma line 111 "/usr/include/sys/cdefs.h" 3 4 ::: 551
#pragma line 123 "/usr/include/sys/cdefs.h" 3 4 ::: 555
#pragma line 155 "/usr/include/sys/cdefs.h" 3 4 ::: 573
#pragma line 178 "/usr/include/sys/cdefs.h" 3 4 ::: 583
#pragma line 222 "/usr/include/sys/cdefs.h" 3 4 ::: 620
#pragma line 275 "/usr/include/sys/cdefs.h" 3 4 ::: 661
#pragma line 313 "/usr/include/sys/cdefs.h" 3 4 ::: 685
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 686
#pragma line 314 "/usr/include/sys/cdefs.h" 2 3 4 ::: 688
#pragma line 330 "/usr/include/features.h" 2 3 4 ::: 689
#pragma line 1 "/usr/include/gnu/stubs.h" 1 3 4 ::: 713
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 718
#pragma line 5 "/usr/include/gnu/stubs.h" 2 3 4 ::: 720
#pragma line 1 "/usr/include/gnu/stubs-64.h" 1 3 4 ::: 725
#pragma line 10 "/usr/include/gnu/stubs.h" 2 3 4 ::: 730
#pragma line 353 "/usr/include/features.h" 2 3 4 ::: 731
#pragma line 29 "/usr/include/math.h" 2 3 4 ::: 732
#pragma line 1 "/usr/include/bits/huge_val.h" 1 3 4 ::: 739
#pragma line 35 "/usr/include/math.h" 2 3 4 ::: 766
#pragma line 46 "/usr/include/math.h" 3 4 ::: 767
#pragma line 1 "/usr/include/bits/mathdef.h" 1 3 4 ::: 770
#pragma line 48 "/usr/include/math.h" 2 3 4 ::: 788
#pragma line 71 "/usr/include/math.h" 3 4 ::: 794
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 795
#pragma line 88 "/usr/include/bits/mathcalls.h" 3 4 ::: 873
#pragma line 128 "/usr/include/bits/mathcalls.h" 3 4 ::: 903
#pragma line 150 "/usr/include/bits/mathcalls.h" 3 4 ::: 912
#pragma line 230 "/usr/include/bits/mathcalls.h" 3 4 ::: 982
#pragma line 264 "/usr/include/bits/mathcalls.h" 3 4 ::: 1006
#pragma line 363 "/usr/include/bits/mathcalls.h" 3 4 ::: 1041
#pragma line 72 "/usr/include/math.h" 2 3 4 ::: 1044
#pragma line 94 "/usr/include/math.h" 3 4 ::: 1055
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 1056
#pragma line 88 "/usr/include/bits/mathcalls.h" 3 4 ::: 1134
#pragma line 128 "/usr/include/bits/mathcalls.h" 3 4 ::: 1164
#pragma line 150 "/usr/include/bits/mathcalls.h" 3 4 ::: 1173
#pragma line 230 "/usr/include/bits/mathcalls.h" 3 4 ::: 1243
#pragma line 264 "/usr/include/bits/mathcalls.h" 3 4 ::: 1267
#pragma line 363 "/usr/include/bits/mathcalls.h" 3 4 ::: 1302
#pragma line 95 "/usr/include/math.h" 2 3 4 ::: 1305
#pragma line 141 "/usr/include/math.h" 3 4 ::: 1306
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 1307
#pragma line 88 "/usr/include/bits/mathcalls.h" 3 4 ::: 1385
#pragma line 128 "/usr/include/bits/mathcalls.h" 3 4 ::: 1415
#pragma line 150 "/usr/include/bits/mathcalls.h" 3 4 ::: 1424
#pragma line 230 "/usr/include/bits/mathcalls.h" 3 4 ::: 1494
#pragma line 264 "/usr/include/bits/mathcalls.h" 3 4 ::: 1518
#pragma line 363 "/usr/include/bits/mathcalls.h" 3 4 ::: 1553
#pragma line 142 "/usr/include/math.h" 2 3 4 ::: 1556
#pragma line 156 "/usr/include/math.h" 3 4 ::: 1557
#pragma line 283 "/usr/include/math.h" 3 4 ::: 1564
#pragma line 348 "/usr/include/math.h" 3 4 ::: 1618
#pragma line 365 "/usr/include/math.h" 3 4 ::: 1620
#pragma line 385 "/usr/include/math.h" 3 4 ::: 1624
#pragma line 407 "/usr/include/math.h" 3 4 ::: 1628
#pragma line 3 "gaussian.c" 2 ::: 1630
#pragma line 1 "./mt19937ar.h" 1 ::: 1631
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 1676
#pragma line 34 "/usr/include/stdio.h" 3 4 ::: 1699
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1700
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1741
#pragma line 35 "/usr/include/stdio.h" 2 3 4 ::: 1744
#pragma line 1 "/usr/include/bits/types.h" 1 3 4 ::: 1746
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 1775
#pragma line 29 "/usr/include/bits/types.h" 2 3 4 ::: 1777
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1780
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1805
#pragma line 32 "/usr/include/bits/types.h" 2 3 4 ::: 1808
#pragma line 73 "/usr/include/bits/types.h" 3 4 ::: 1835
#pragma line 129 "/usr/include/bits/types.h" 3 4 ::: 1864
#pragma line 1 "/usr/include/bits/typesizes.h" 1 3 4 ::: 1871
#pragma line 27 "/usr/include/bits/typesizes.h" 3 4 ::: 1890
#pragma line 62 "/usr/include/bits/typesizes.h" 3 4 ::: 1893
#pragma line 135 "/usr/include/bits/types.h" 2 3 4 ::: 1895
#pragma line 37 "/usr/include/stdio.h" 2 3 4 ::: 1957
#pragma line 61 "/usr/include/stdio.h" 3 4 ::: 1968
#pragma line 72 "/usr/include/stdio.h" 3 4 ::: 1971
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 1972
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 2005
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2020
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2045
#pragma line 15 "/usr/include/_G_config.h" 2 3 4 ::: 2052
#pragma line 24 "/usr/include/_G_config.h" 3 4 ::: 2053
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 2054
#pragma line 48 "/usr/include/wchar.h" 3 4 ::: 2077
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2078
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2103
#pragma line 49 "/usr/include/wchar.h" 2 3 4 ::: 2106
#pragma line 1 "/usr/include/bits/wchar.h" 1 3 4 ::: 2108
#pragma line 51 "/usr/include/wchar.h" 2 3 4 ::: 2127
#pragma line 62 "/usr/include/wchar.h" 3 4 ::: 2131
#pragma line 75 "/usr/include/wchar.h" 3 4 ::: 2134
#pragma line 25 "/usr/include/_G_config.h" 2 3 4 ::: 2151
#pragma line 44 "/usr/include/_G_config.h" 3 4 ::: 2163
#pragma line 1 "/usr/include/gconv.h" 1 3 4 ::: 2164
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 2193
#pragma line 48 "/usr/include/wchar.h" 3 4 ::: 2216
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2217
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2242
#pragma line 49 "/usr/include/wchar.h" 2 3 4 ::: 2245
#pragma line 62 "/usr/include/wchar.h" 3 4 ::: 2251
#pragma line 89 "/usr/include/wchar.h" 3 4 ::: 2254
#pragma line 29 "/usr/include/gconv.h" 2 3 4 ::: 2257
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2260
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2285
#pragma line 32 "/usr/include/gconv.h" 2 3 4 ::: 2288
#pragma line 45 "/usr/include/_G_config.h" 2 3 4 ::: 2435
#pragma line 84 "/usr/include/_G_config.h" 3 4 ::: 2455
#pragma line 33 "/usr/include/libio.h" 2 3 4 ::: 2462
#pragma line 51 "/usr/include/libio.h" 3 4 ::: 2464
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 2468
#pragma line 54 "/usr/include/libio.h" 2 3 4 ::: 2517
#pragma line 74 "/usr/include/libio.h" 3 4 ::: 2518
#pragma line 114 "/usr/include/libio.h" 3 4 ::: 2520
#pragma line 147 "/usr/include/libio.h" 3 4 ::: 2526
#pragma line 167 "/usr/include/libio.h" 3 4 ::: 2528
#pragma line 200 "/usr/include/libio.h" 3 4 ::: 2552
#pragma line 268 "/usr/include/libio.h" 3 4 ::: 2563
#pragma line 316 "/usr/include/libio.h" 3 4 ::: 2604
#pragma line 325 "/usr/include/libio.h" 3 4 ::: 2606
#pragma line 357 "/usr/include/libio.h" 3 4 ::: 2628
#pragma line 413 "/usr/include/libio.h" 3 4 ::: 2654
#pragma line 451 "/usr/include/libio.h" 3 4 ::: 2661
#pragma line 481 "/usr/include/libio.h" 3 4 ::: 2676
#pragma line 73 "/usr/include/stdio.h" 2 3 4 ::: 2688
#pragma line 85 "/usr/include/stdio.h" 3 4 ::: 2689
#pragma line 97 "/usr/include/stdio.h" 3 4 ::: 2694
#pragma line 1 "/usr/include/bits/stdio_lim.h" 1 3 4 ::: 2737
#pragma line 139 "/usr/include/stdio.h" 2 3 4 ::: 2755
#pragma line 166 "/usr/include/stdio.h" 3 4 ::: 2774
#pragma line 184 "/usr/include/stdio.h" 3 4 ::: 2781
#pragma line 244 "/usr/include/stdio.h" 3 4 ::: 2827
#pragma line 279 "/usr/include/stdio.h" 3 4 ::: 2841
#pragma line 301 "/usr/include/stdio.h" 3 4 ::: 2844
#pragma line 395 "/usr/include/stdio.h" 3 4 ::: 2908
#pragma line 437 "/usr/include/stdio.h" 3 4 ::: 2923
#pragma line 586 "/usr/include/stdio.h" 3 4 ::: 3028
#pragma line 632 "/usr/include/stdio.h" 3 4 ::: 3061
#pragma line 695 "/usr/include/stdio.h" 3 4 ::: 3110
#pragma line 726 "/usr/include/stdio.h" 3 4 ::: 3121
#pragma line 1 "/usr/include/bits/sys_errlist.h" 1 3 4 ::: 3151
#pragma line 755 "/usr/include/stdio.h" 2 3 4 ::: 3180
#pragma line 811 "/usr/include/stdio.h" 3 4 ::: 3213
#pragma line 832 "/usr/include/stdio.h" 3 4 ::: 3225
#pragma line 45 "./mt19937ar.h" 2 ::: 3228
#pragma line 4 "gaussian.c" 2 ::: 3243
