#!/bin/bash

# Xilinx 
# Vivado System Edition 2013.2
export XILINXD_LICENSE_FILE=2100@flex.ece.cornell.edu
#source /opt/xilinx/Vivado/2013.2/settings64.sh
# ISE 14.3 
IDS_VER=3
source /opt/xilinx/14.$IDS_VER/ISE_DS/settings64.sh

