#pragma line 1 "BlackScholesWrapper.cpp" ::: 0
#pragma line 1 "BlackScholesWrapper.cpp" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 155 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 12
#pragma line 145 "/opt/xilinx/Vivado_HLS/2014.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 65
#pragma line 401 "/opt/xilinx/Vivado_HLS/2014.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 195
#pragma line 8 "<command line>" 2 ::: 198
#pragma line 1 "<built-in>" 2 ::: 199
#pragma line 1 "BlackScholesWrapper.cpp" 2 ::: 200
#pragma line 1 "./BlackScholesWrapper.h" 1 ::: 201
#pragma line 2 "BlackScholesWrapper.cpp" 2 ::: 205
#pragma line 1 "./BlackScholes.h" 1 ::: 206
#pragma line 1 "/usr/include/math.h" 1 3 4 ::: 207
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 236
#pragma line 115 "/usr/include/features.h" 3 4 ::: 329
#pragma line 139 "/usr/include/features.h" 3 4 ::: 346
#pragma line 169 "/usr/include/features.h" 3 4 ::: 356
#pragma line 179 "/usr/include/features.h" 3 4 ::: 359
#pragma line 294 "/usr/include/features.h" 3 4 ::: 371
#pragma line 1 "/usr/include/sys/cdefs.h" 1 3 4 ::: 408
#pragma line 72 "/usr/include/sys/cdefs.h" 3 4 ::: 454
#pragma line 98 "/usr/include/sys/cdefs.h" 3 4 ::: 472
#pragma line 111 "/usr/include/sys/cdefs.h" 3 4 ::: 478
#pragma line 123 "/usr/include/sys/cdefs.h" 3 4 ::: 482
#pragma line 155 "/usr/include/sys/cdefs.h" 3 4 ::: 500
#pragma line 178 "/usr/include/sys/cdefs.h" 3 4 ::: 510
#pragma line 222 "/usr/include/sys/cdefs.h" 3 4 ::: 547
#pragma line 275 "/usr/include/sys/cdefs.h" 3 4 ::: 588
#pragma line 313 "/usr/include/sys/cdefs.h" 3 4 ::: 612
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 613
#pragma line 314 "/usr/include/sys/cdefs.h" 2 3 4 ::: 615
#pragma line 330 "/usr/include/features.h" 2 3 4 ::: 616
#pragma line 1 "/usr/include/gnu/stubs.h" 1 3 4 ::: 640
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 645
#pragma line 5 "/usr/include/gnu/stubs.h" 2 3 4 ::: 647
#pragma line 1 "/usr/include/gnu/stubs-64.h" 1 3 4 ::: 652
#pragma line 10 "/usr/include/gnu/stubs.h" 2 3 4 ::: 657
#pragma line 353 "/usr/include/features.h" 2 3 4 ::: 658
#pragma line 29 "/usr/include/math.h" 2 3 4 ::: 659
#pragma line 1 "/usr/include/bits/huge_val.h" 1 3 4 ::: 666
#pragma line 35 "/usr/include/math.h" 2 3 4 ::: 693
#pragma line 1 "/usr/include/bits/huge_valf.h" 1 3 4 ::: 695
#pragma line 37 "/usr/include/math.h" 2 3 4 ::: 722
#pragma line 1 "/usr/include/bits/huge_vall.h" 1 3 4 ::: 723
#pragma line 38 "/usr/include/math.h" 2 3 4 ::: 743
#pragma line 1 "/usr/include/bits/inf.h" 1 3 4 ::: 747
#pragma line 41 "/usr/include/math.h" 2 3 4 ::: 772
#pragma line 1 "/usr/include/bits/nan.h" 1 3 4 ::: 776
#pragma line 44 "/usr/include/math.h" 2 3 4 ::: 802
#pragma line 1 "/usr/include/bits/mathdef.h" 1 3 4 ::: 807
#pragma line 26 "/usr/include/bits/mathdef.h" 3 4 ::: 825
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 826
#pragma line 27 "/usr/include/bits/mathdef.h" 2 3 4 ::: 828
#pragma line 44 "/usr/include/bits/mathdef.h" 3 4 ::: 836
#pragma line 48 "/usr/include/math.h" 2 3 4 ::: 838
#pragma line 71 "/usr/include/math.h" 3 4 ::: 844
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 845
#pragma line 72 "/usr/include/math.h" 2 3 4 ::: 1210
#pragma line 94 "/usr/include/math.h" 3 4 ::: 1221
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 1222
#pragma line 95 "/usr/include/math.h" 2 3 4 ::: 1587
#pragma line 141 "/usr/include/math.h" 3 4 ::: 1588
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 1589
#pragma line 142 "/usr/include/math.h" 2 3 4 ::: 1954
#pragma line 156 "/usr/include/math.h" 3 4 ::: 1955
#pragma line 224 "/usr/include/math.h" 3 4 ::: 2013
#pragma line 236 "/usr/include/math.h" 3 4 ::: 2015
#pragma line 248 "/usr/include/math.h" 3 4 ::: 2017
#pragma line 264 "/usr/include/math.h" 3 4 ::: 2023
#pragma line 276 "/usr/include/math.h" 3 4 ::: 2025
#pragma line 348 "/usr/include/math.h" 3 4 ::: 2086
#pragma line 365 "/usr/include/math.h" 3 4 ::: 2088
#pragma line 385 "/usr/include/math.h" 3 4 ::: 2092
#pragma line 407 "/usr/include/math.h" 3 4 ::: 2107
#pragma line 465 "/usr/include/math.h" 3 4 ::: 2157
#pragma line 2 "./BlackScholes.h" 2 ::: 2159
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 2160
#pragma line 31 "/usr/include/time.h" 3 4 ::: 2183
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2193
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2229
#pragma line 40 "/usr/include/time.h" 2 3 4 ::: 2232
#pragma line 1 "/usr/include/bits/time.h" 1 3 4 ::: 2237
#pragma line 45 "/usr/include/bits/time.h" 3 4 ::: 2271
#pragma line 44 "/usr/include/time.h" 2 3 4 ::: 2282
#pragma line 57 "/usr/include/time.h" 3 4 ::: 2285
#pragma line 1 "/usr/include/bits/types.h" 1 3 4 ::: 2286
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 2315
#pragma line 29 "/usr/include/bits/types.h" 2 3 4 ::: 2317
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2320
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2345
#pragma line 32 "/usr/include/bits/types.h" 2 3 4 ::: 2348
#pragma line 73 "/usr/include/bits/types.h" 3 4 ::: 2375
#pragma line 129 "/usr/include/bits/types.h" 3 4 ::: 2404
#pragma line 1 "/usr/include/bits/typesizes.h" 1 3 4 ::: 2411
#pragma line 27 "/usr/include/bits/typesizes.h" 3 4 ::: 2430
#pragma line 62 "/usr/include/bits/typesizes.h" 3 4 ::: 2433
#pragma line 135 "/usr/include/bits/types.h" 2 3 4 ::: 2435
#pragma line 58 "/usr/include/time.h" 2 3 4 ::: 2497
#pragma line 76 "/usr/include/time.h" 3 4 ::: 2502
#pragma line 92 "/usr/include/time.h" 3 4 ::: 2505
#pragma line 104 "/usr/include/time.h" 3 4 ::: 2508
#pragma line 119 "/usr/include/time.h" 3 4 ::: 2511
#pragma line 1 "/usr/include/xlocale.h" 1 3 4 ::: 2610
#pragma line 217 "/usr/include/time.h" 2 3 4 ::: 2651
#pragma line 3 "./BlackScholes.h" 2 ::: 2852
#pragma line 1 "/usr/include/stdlib.h" 1 3 4 ::: 2853
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2887
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2912
#pragma line 34 "/usr/include/stdlib.h" 2 3 4 ::: 2915
#pragma line 1 "/usr/include/bits/waitflags.h" 1 3 4 ::: 2925
#pragma line 43 "/usr/include/stdlib.h" 2 3 4 ::: 2955
#pragma line 1 "/usr/include/bits/waitstatus.h" 1 3 4 ::: 2956
#pragma line 65 "/usr/include/bits/waitstatus.h" 3 4 ::: 3013
#pragma line 1 "/usr/include/endian.h" 1 3 4 ::: 3014
#pragma line 1 "/usr/include/bits/endian.h" 1 3 4 ::: 3052
#pragma line 38 "/usr/include/endian.h" 2 3 4 ::: 3054
#pragma line 66 "/usr/include/bits/waitstatus.h" 2 3 4 ::: 3058
#pragma line 44 "/usr/include/stdlib.h" 2 3 4 ::: 3092
#pragma line 58 "/usr/include/stdlib.h" 3 4 ::: 3098
#pragma line 84 "/usr/include/stdlib.h" 3 4 ::: 3103
#pragma line 97 "/usr/include/stdlib.h" 3 4 ::: 3105
#pragma line 426 "/usr/include/stdlib.h" 3 4 ::: 3328
#pragma line 1 "/usr/include/sys/types.h" 1 3 4 ::: 3342
#pragma line 105 "/usr/include/sys/types.h" 3 4 ::: 3438
#pragma line 137 "/usr/include/sys/types.h" 3 4 ::: 3458
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3470
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3495
#pragma line 148 "/usr/include/sys/types.h" 2 3 4 ::: 3498
#pragma line 187 "/usr/include/sys/types.h" 3 4 ::: 3508
#pragma line 1 "/usr/include/sys/select.h" 1 3 4 ::: 3543
#pragma line 1 "/usr/include/bits/select.h" 1 3 4 ::: 3575
#pragma line 32 "/usr/include/sys/select.h" 2 3 4 ::: 3601
#pragma line 1 "/usr/include/bits/sigset.h" 1 3 4 ::: 3605
#pragma line 35 "/usr/include/sys/select.h" 2 3 4 ::: 3646
#pragma line 1 "/usr/include/bits/time.h" 1 3 4 ::: 3659
#pragma line 67 "/usr/include/bits/time.h" 3 4 ::: 3682
#pragma line 47 "/usr/include/sys/select.h" 2 3 4 ::: 3690
#pragma line 221 "/usr/include/sys/types.h" 2 3 4 ::: 3773
#pragma line 1 "/usr/include/sys/sysmacros.h" 1 3 4 ::: 3777
#pragma line 224 "/usr/include/sys/types.h" 2 3 4 ::: 3841
#pragma line 262 "/usr/include/sys/types.h" 3 4 ::: 3862
#pragma line 1 "/usr/include/bits/pthreadtypes.h" 1 3 4 ::: 3872
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 3896
#pragma line 24 "/usr/include/bits/pthreadtypes.h" 2 3 4 ::: 3898
#pragma line 48 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 3899
#pragma line 74 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 3918
#pragma line 101 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 3937
#pragma line 187 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 4006
#pragma line 271 "/usr/include/sys/types.h" 2 3 4 ::: 4037
#pragma line 439 "/usr/include/stdlib.h" 2 3 4 ::: 4041
#pragma line 588 "/usr/include/stdlib.h" 3 4 ::: 4183
#pragma line 1 "/usr/include/alloca.h" 1 3 4 ::: 4209
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 4235
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 4260
#pragma line 26 "/usr/include/alloca.h" 2 3 4 ::: 4263
#pragma line 613 "/usr/include/stdlib.h" 2 3 4 ::: 4278
#pragma line 719 "/usr/include/stdlib.h" 3 4 ::: 4376
#pragma line 977 "/usr/include/stdlib.h" 3 4 ::: 4625
#pragma line 4 "./BlackScholes.h" 2 ::: 4627
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 4628
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 4663
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 4688
#pragma line 35 "/usr/include/stdio.h" 2 3 4 ::: 4691
#pragma line 45 "/usr/include/stdio.h" 3 4 ::: 4692
#pragma line 61 "/usr/include/stdio.h" 3 4 ::: 4695
#pragma line 72 "/usr/include/stdio.h" 3 4 ::: 4698
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 4699
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 4732
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 4747
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 4772
#pragma line 15 "/usr/include/_G_config.h" 2 3 4 ::: 4779
#pragma line 24 "/usr/include/_G_config.h" 3 4 ::: 4780
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 4781
#pragma line 48 "/usr/include/wchar.h" 3 4 ::: 4804
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 4805
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 4830
#pragma line 49 "/usr/include/wchar.h" 2 3 4 ::: 4833
#pragma line 1 "/usr/include/bits/wchar.h" 1 3 4 ::: 4835
#pragma line 51 "/usr/include/wchar.h" 2 3 4 ::: 4854
#pragma line 62 "/usr/include/wchar.h" 3 4 ::: 4858
#pragma line 75 "/usr/include/wchar.h" 3 4 ::: 4861
#pragma line 25 "/usr/include/_G_config.h" 2 3 4 ::: 4878
#pragma line 44 "/usr/include/_G_config.h" 3 4 ::: 4890
#pragma line 1 "/usr/include/gconv.h" 1 3 4 ::: 4891
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 4920
#pragma line 48 "/usr/include/wchar.h" 3 4 ::: 4943
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 4944
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 4969
#pragma line 49 "/usr/include/wchar.h" 2 3 4 ::: 4972
#pragma line 62 "/usr/include/wchar.h" 3 4 ::: 4978
#pragma line 89 "/usr/include/wchar.h" 3 4 ::: 4981
#pragma line 29 "/usr/include/gconv.h" 2 3 4 ::: 4984
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 4987
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 5012
#pragma line 32 "/usr/include/gconv.h" 2 3 4 ::: 5015
#pragma line 45 "/usr/include/_G_config.h" 2 3 4 ::: 5162
#pragma line 84 "/usr/include/_G_config.h" 3 4 ::: 5182
#pragma line 33 "/usr/include/libio.h" 2 3 4 ::: 5189
#pragma line 51 "/usr/include/libio.h" 3 4 ::: 5191
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 5195
#pragma line 54 "/usr/include/libio.h" 2 3 4 ::: 5244
#pragma line 74 "/usr/include/libio.h" 3 4 ::: 5245
#pragma line 114 "/usr/include/libio.h" 3 4 ::: 5247
#pragma line 147 "/usr/include/libio.h" 3 4 ::: 5253
#pragma line 167 "/usr/include/libio.h" 3 4 ::: 5255
#pragma line 200 "/usr/include/libio.h" 3 4 ::: 5279
#pragma line 268 "/usr/include/libio.h" 3 4 ::: 5290
#pragma line 316 "/usr/include/libio.h" 3 4 ::: 5331
#pragma line 325 "/usr/include/libio.h" 3 4 ::: 5333
#pragma line 357 "/usr/include/libio.h" 3 4 ::: 5355
#pragma line 451 "/usr/include/libio.h" 3 4 ::: 5418
#pragma line 481 "/usr/include/libio.h" 3 4 ::: 5433
#pragma line 543 "/usr/include/libio.h" 3 4 ::: 5445
#pragma line 73 "/usr/include/stdio.h" 2 3 4 ::: 5447
#pragma line 1 "/usr/include/bits/stdio_lim.h" 1 3 4 ::: 5514
#pragma line 139 "/usr/include/stdio.h" 2 3 4 ::: 5532
#pragma line 181 "/usr/include/stdio.h" 3 4 ::: 5566
#pragma line 271 "/usr/include/stdio.h" 3 4 ::: 5643
#pragma line 695 "/usr/include/stdio.h" 3 4 ::: 6053
#pragma line 719 "/usr/include/stdio.h" 3 4 ::: 6064
#pragma line 1 "/usr/include/bits/sys_errlist.h" 1 3 4 ::: 6101
#pragma line 755 "/usr/include/stdio.h" 2 3 4 ::: 6134
#pragma line 832 "/usr/include/stdio.h" 3 4 ::: 6202
#pragma line 844 "/usr/include/stdio.h" 3 4 ::: 6205
#pragma line 5 "./BlackScholes.h" 2 ::: 6207
#pragma line 1 "./mt19937ar.h" 1 ::: 6208
#pragma line 6 "./BlackScholes.h" 2 ::: 6267
#pragma line 1 "./CND.h" 1 ::: 6268
#pragma line 7 "./BlackScholes.h" 2 ::: 6275
#pragma line 3 "BlackScholesWrapper.cpp" 2 ::: 6278
