#pragma line 1 "CND.c" ::: -10
#pragma line 1 "CND.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 149 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 2
#pragma line 278 "/opt/xilinx/Vivado_HLS/2014.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 55
#pragma line 8 "<command line>" 2 ::: 181
#pragma line 1 "<built-in>" 2 ::: 182
#pragma line 1 "CND.c" 2 ::: 183
#pragma line 1 "./CND.h" 1 ::: 184
#pragma line 1 "/usr/include/math.h" 1 3 4 ::: 185
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 214
#pragma line 115 "/usr/include/features.h" 3 4 ::: 307
#pragma line 139 "/usr/include/features.h" 3 4 ::: 324
#pragma line 169 "/usr/include/features.h" 3 4 ::: 334
#pragma line 179 "/usr/include/features.h" 3 4 ::: 337
#pragma line 294 "/usr/include/features.h" 3 4 ::: 349
#pragma line 1 "/usr/include/sys/cdefs.h" 1 3 4 ::: 386
#pragma line 72 "/usr/include/sys/cdefs.h" 3 4 ::: 432
#pragma line 98 "/usr/include/sys/cdefs.h" 3 4 ::: 450
#pragma line 111 "/usr/include/sys/cdefs.h" 3 4 ::: 456
#pragma line 123 "/usr/include/sys/cdefs.h" 3 4 ::: 460
#pragma line 155 "/usr/include/sys/cdefs.h" 3 4 ::: 478
#pragma line 178 "/usr/include/sys/cdefs.h" 3 4 ::: 488
#pragma line 222 "/usr/include/sys/cdefs.h" 3 4 ::: 525
#pragma line 275 "/usr/include/sys/cdefs.h" 3 4 ::: 566
#pragma line 313 "/usr/include/sys/cdefs.h" 3 4 ::: 590
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 591
#pragma line 314 "/usr/include/sys/cdefs.h" 2 3 4 ::: 593
#pragma line 330 "/usr/include/features.h" 2 3 4 ::: 594
#pragma line 1 "/usr/include/gnu/stubs.h" 1 3 4 ::: 618
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 623
#pragma line 5 "/usr/include/gnu/stubs.h" 2 3 4 ::: 625
#pragma line 1 "/usr/include/gnu/stubs-64.h" 1 3 4 ::: 630
#pragma line 10 "/usr/include/gnu/stubs.h" 2 3 4 ::: 635
#pragma line 353 "/usr/include/features.h" 2 3 4 ::: 636
#pragma line 29 "/usr/include/math.h" 2 3 4 ::: 637
#pragma line 1 "/usr/include/bits/huge_val.h" 1 3 4 ::: 644
#pragma line 35 "/usr/include/math.h" 2 3 4 ::: 671
#pragma line 46 "/usr/include/math.h" 3 4 ::: 672
#pragma line 1 "/usr/include/bits/mathdef.h" 1 3 4 ::: 675
#pragma line 48 "/usr/include/math.h" 2 3 4 ::: 693
#pragma line 71 "/usr/include/math.h" 3 4 ::: 699
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 700
#pragma line 88 "/usr/include/bits/mathcalls.h" 3 4 ::: 778
#pragma line 128 "/usr/include/bits/mathcalls.h" 3 4 ::: 808
#pragma line 150 "/usr/include/bits/mathcalls.h" 3 4 ::: 817
#pragma line 230 "/usr/include/bits/mathcalls.h" 3 4 ::: 887
#pragma line 264 "/usr/include/bits/mathcalls.h" 3 4 ::: 911
#pragma line 363 "/usr/include/bits/mathcalls.h" 3 4 ::: 946
#pragma line 72 "/usr/include/math.h" 2 3 4 ::: 949
#pragma line 94 "/usr/include/math.h" 3 4 ::: 960
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 961
#pragma line 88 "/usr/include/bits/mathcalls.h" 3 4 ::: 1039
#pragma line 128 "/usr/include/bits/mathcalls.h" 3 4 ::: 1069
#pragma line 150 "/usr/include/bits/mathcalls.h" 3 4 ::: 1078
#pragma line 230 "/usr/include/bits/mathcalls.h" 3 4 ::: 1148
#pragma line 264 "/usr/include/bits/mathcalls.h" 3 4 ::: 1172
#pragma line 363 "/usr/include/bits/mathcalls.h" 3 4 ::: 1207
#pragma line 95 "/usr/include/math.h" 2 3 4 ::: 1210
#pragma line 141 "/usr/include/math.h" 3 4 ::: 1211
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 1212
#pragma line 88 "/usr/include/bits/mathcalls.h" 3 4 ::: 1290
#pragma line 128 "/usr/include/bits/mathcalls.h" 3 4 ::: 1320
#pragma line 150 "/usr/include/bits/mathcalls.h" 3 4 ::: 1329
#pragma line 230 "/usr/include/bits/mathcalls.h" 3 4 ::: 1399
#pragma line 264 "/usr/include/bits/mathcalls.h" 3 4 ::: 1423
#pragma line 363 "/usr/include/bits/mathcalls.h" 3 4 ::: 1458
#pragma line 142 "/usr/include/math.h" 2 3 4 ::: 1461
#pragma line 156 "/usr/include/math.h" 3 4 ::: 1462
#pragma line 283 "/usr/include/math.h" 3 4 ::: 1469
#pragma line 348 "/usr/include/math.h" 3 4 ::: 1523
#pragma line 365 "/usr/include/math.h" 3 4 ::: 1525
#pragma line 385 "/usr/include/math.h" 3 4 ::: 1529
#pragma line 407 "/usr/include/math.h" 3 4 ::: 1533
#pragma line 2 "./CND.h" 2 ::: 1535
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 1536
#pragma line 36 "/usr/include/time.h" 3 4 ::: 1559
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1564
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1605
#pragma line 40 "/usr/include/time.h" 2 3 4 ::: 1608
#pragma line 1 "/usr/include/bits/time.h" 1 3 4 ::: 1613
#pragma line 45 "/usr/include/bits/time.h" 3 4 ::: 1647
#pragma line 44 "/usr/include/time.h" 2 3 4 ::: 1658
#pragma line 57 "/usr/include/time.h" 3 4 ::: 1661
#pragma line 1 "/usr/include/bits/types.h" 1 3 4 ::: 1662
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 1691
#pragma line 29 "/usr/include/bits/types.h" 2 3 4 ::: 1693
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1696
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1721
#pragma line 32 "/usr/include/bits/types.h" 2 3 4 ::: 1724
#pragma line 73 "/usr/include/bits/types.h" 3 4 ::: 1751
#pragma line 129 "/usr/include/bits/types.h" 3 4 ::: 1780
#pragma line 1 "/usr/include/bits/typesizes.h" 1 3 4 ::: 1787
#pragma line 27 "/usr/include/bits/typesizes.h" 3 4 ::: 1806
#pragma line 62 "/usr/include/bits/typesizes.h" 3 4 ::: 1809
#pragma line 135 "/usr/include/bits/types.h" 2 3 4 ::: 1811
#pragma line 58 "/usr/include/time.h" 2 3 4 ::: 1873
#pragma line 76 "/usr/include/time.h" 3 4 ::: 1878
#pragma line 92 "/usr/include/time.h" 3 4 ::: 1881
#pragma line 104 "/usr/include/time.h" 3 4 ::: 1884
#pragma line 119 "/usr/include/time.h" 3 4 ::: 1887
#pragma line 230 "/usr/include/time.h" 3 4 ::: 1972
#pragma line 3 "./CND.h" 2 ::: 2117
#pragma line 1 "/usr/include/stdlib.h" 1 3 4 ::: 2118
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2152
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2177
#pragma line 34 "/usr/include/stdlib.h" 2 3 4 ::: 2180
#pragma line 97 "/usr/include/stdlib.h" 3 4 ::: 2181
#pragma line 128 "/usr/include/stdlib.h" 3 4 ::: 2196
#pragma line 183 "/usr/include/stdlib.h" 3 4 ::: 2237
#pragma line 276 "/usr/include/stdlib.h" 3 4 ::: 2273
#pragma line 426 "/usr/include/stdlib.h" 3 4 ::: 2317
#pragma line 1 "/usr/include/sys/types.h" 1 3 4 ::: 2331
#pragma line 35 "/usr/include/sys/types.h" 3 4 ::: 2354
#pragma line 62 "/usr/include/sys/types.h" 3 4 ::: 2371
#pragma line 105 "/usr/include/sys/types.h" 3 4 ::: 2399
#pragma line 147 "/usr/include/sys/types.h" 3 4 ::: 2419
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2420
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2445
#pragma line 148 "/usr/include/sys/types.h" 2 3 4 ::: 2448
#pragma line 187 "/usr/include/sys/types.h" 3 4 ::: 2458
#pragma line 1 "/usr/include/endian.h" 1 3 4 ::: 2490
#pragma line 1 "/usr/include/bits/endian.h" 1 3 4 ::: 2528
#pragma line 38 "/usr/include/endian.h" 2 3 4 ::: 2530
#pragma line 218 "/usr/include/sys/types.h" 2 3 4 ::: 2534
#pragma line 1 "/usr/include/sys/select.h" 1 3 4 ::: 2538
#pragma line 1 "/usr/include/bits/select.h" 1 3 4 ::: 2570
#pragma line 32 "/usr/include/sys/select.h" 2 3 4 ::: 2596
#pragma line 1 "/usr/include/bits/sigset.h" 1 3 4 ::: 2600
#pragma line 35 "/usr/include/sys/select.h" 2 3 4 ::: 2641
#pragma line 1 "/usr/include/bits/time.h" 1 3 4 ::: 2654
#pragma line 67 "/usr/include/bits/time.h" 3 4 ::: 2677
#pragma line 47 "/usr/include/sys/select.h" 2 3 4 ::: 2685
#pragma line 101 "/usr/include/sys/select.h" 3 4 ::: 2732
#pragma line 221 "/usr/include/sys/types.h" 2 3 4 ::: 2758
#pragma line 1 "/usr/include/sys/sysmacros.h" 1 3 4 ::: 2762
#pragma line 224 "/usr/include/sys/types.h" 2 3 4 ::: 2826
#pragma line 268 "/usr/include/sys/types.h" 3 4 ::: 2847
#pragma line 1 "/usr/include/bits/pthreadtypes.h" 1 3 4 ::: 2851
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 2875
#pragma line 24 "/usr/include/bits/pthreadtypes.h" 2 3 4 ::: 2877
#pragma line 48 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 2878
#pragma line 74 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 2897
#pragma line 101 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 2916
#pragma line 187 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 2985
#pragma line 271 "/usr/include/sys/types.h" 2 3 4 ::: 3016
#pragma line 439 "/usr/include/stdlib.h" 2 3 4 ::: 3017
#pragma line 588 "/usr/include/stdlib.h" 3 4 ::: 3159
#pragma line 1 "/usr/include/alloca.h" 1 3 4 ::: 3185
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3211
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3236
#pragma line 26 "/usr/include/alloca.h" 2 3 4 ::: 3239
#pragma line 613 "/usr/include/stdlib.h" 2 3 4 ::: 3248
#pragma line 659 "/usr/include/stdlib.h" 3 4 ::: 3283
#pragma line 724 "/usr/include/stdlib.h" 3 4 ::: 3335
#pragma line 751 "/usr/include/stdlib.h" 3 4 ::: 3351
#pragma line 796 "/usr/include/stdlib.h" 3 4 ::: 3388
#pragma line 815 "/usr/include/stdlib.h" 3 4 ::: 3396
#pragma line 922 "/usr/include/stdlib.h" 3 4 ::: 3481
#pragma line 958 "/usr/include/stdlib.h" 3 4 ::: 3487
#pragma line 4 "./CND.h" 2 ::: 3497
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 3498
#pragma line 34 "/usr/include/stdio.h" 3 4 ::: 3521
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3522
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3547
#pragma line 35 "/usr/include/stdio.h" 2 3 4 ::: 3550
#pragma line 45 "/usr/include/stdio.h" 3 4 ::: 3551
#pragma line 61 "/usr/include/stdio.h" 3 4 ::: 3554
#pragma line 72 "/usr/include/stdio.h" 3 4 ::: 3557
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 3558
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 3591
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3606
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3631
#pragma line 15 "/usr/include/_G_config.h" 2 3 4 ::: 3638
#pragma line 24 "/usr/include/_G_config.h" 3 4 ::: 3639
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 3640
#pragma line 48 "/usr/include/wchar.h" 3 4 ::: 3663
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3664
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3689
#pragma line 49 "/usr/include/wchar.h" 2 3 4 ::: 3692
#pragma line 1 "/usr/include/bits/wchar.h" 1 3 4 ::: 3694
#pragma line 51 "/usr/include/wchar.h" 2 3 4 ::: 3713
#pragma line 62 "/usr/include/wchar.h" 3 4 ::: 3717
#pragma line 75 "/usr/include/wchar.h" 3 4 ::: 3720
#pragma line 25 "/usr/include/_G_config.h" 2 3 4 ::: 3737
#pragma line 44 "/usr/include/_G_config.h" 3 4 ::: 3749
#pragma line 1 "/usr/include/gconv.h" 1 3 4 ::: 3750
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 3779
#pragma line 48 "/usr/include/wchar.h" 3 4 ::: 3802
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3803
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3828
#pragma line 49 "/usr/include/wchar.h" 2 3 4 ::: 3831
#pragma line 62 "/usr/include/wchar.h" 3 4 ::: 3837
#pragma line 89 "/usr/include/wchar.h" 3 4 ::: 3840
#pragma line 29 "/usr/include/gconv.h" 2 3 4 ::: 3843
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3846
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3871
#pragma line 32 "/usr/include/gconv.h" 2 3 4 ::: 3874
#pragma line 45 "/usr/include/_G_config.h" 2 3 4 ::: 4021
#pragma line 84 "/usr/include/_G_config.h" 3 4 ::: 4041
#pragma line 33 "/usr/include/libio.h" 2 3 4 ::: 4048
#pragma line 51 "/usr/include/libio.h" 3 4 ::: 4050
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 4054
#pragma line 54 "/usr/include/libio.h" 2 3 4 ::: 4103
#pragma line 74 "/usr/include/libio.h" 3 4 ::: 4104
#pragma line 114 "/usr/include/libio.h" 3 4 ::: 4106
#pragma line 147 "/usr/include/libio.h" 3 4 ::: 4112
#pragma line 167 "/usr/include/libio.h" 3 4 ::: 4114
#pragma line 200 "/usr/include/libio.h" 3 4 ::: 4138
#pragma line 268 "/usr/include/libio.h" 3 4 ::: 4149
#pragma line 316 "/usr/include/libio.h" 3 4 ::: 4190
#pragma line 325 "/usr/include/libio.h" 3 4 ::: 4192
#pragma line 357 "/usr/include/libio.h" 3 4 ::: 4214
#pragma line 413 "/usr/include/libio.h" 3 4 ::: 4240
#pragma line 451 "/usr/include/libio.h" 3 4 ::: 4247
#pragma line 481 "/usr/include/libio.h" 3 4 ::: 4262
#pragma line 73 "/usr/include/stdio.h" 2 3 4 ::: 4274
#pragma line 85 "/usr/include/stdio.h" 3 4 ::: 4275
#pragma line 97 "/usr/include/stdio.h" 3 4 ::: 4280
#pragma line 1 "/usr/include/bits/stdio_lim.h" 1 3 4 ::: 4323
#pragma line 139 "/usr/include/stdio.h" 2 3 4 ::: 4341
#pragma line 166 "/usr/include/stdio.h" 3 4 ::: 4360
#pragma line 184 "/usr/include/stdio.h" 3 4 ::: 4367
#pragma line 244 "/usr/include/stdio.h" 3 4 ::: 4413
#pragma line 279 "/usr/include/stdio.h" 3 4 ::: 4427
#pragma line 301 "/usr/include/stdio.h" 3 4 ::: 4430
#pragma line 395 "/usr/include/stdio.h" 3 4 ::: 4494
#pragma line 437 "/usr/include/stdio.h" 3 4 ::: 4509
#pragma line 586 "/usr/include/stdio.h" 3 4 ::: 4614
#pragma line 632 "/usr/include/stdio.h" 3 4 ::: 4647
#pragma line 695 "/usr/include/stdio.h" 3 4 ::: 4696
#pragma line 726 "/usr/include/stdio.h" 3 4 ::: 4707
#pragma line 1 "/usr/include/bits/sys_errlist.h" 1 3 4 ::: 4737
#pragma line 755 "/usr/include/stdio.h" 2 3 4 ::: 4766
#pragma line 811 "/usr/include/stdio.h" 3 4 ::: 4799
#pragma line 832 "/usr/include/stdio.h" 3 4 ::: 4811
#pragma line 5 "./CND.h" 2 ::: 4814
#pragma line 2 "CND.c" 2 ::: 4817
#pragma line 12 "CND.c" ::: 4818
