#pragma line 1 "CND.c" ::: 0
#pragma line 1 "CND.c" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 149 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 12
#pragma line 278 "/opt/xilinx/Vivado_HLS/2014.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 65
#pragma line 8 "<command line>" 2 ::: 191
#pragma line 1 "<built-in>" 2 ::: 192
#pragma line 1 "CND.c" 2 ::: 193
#pragma line 1 "./CND.h" 1 ::: 194
#pragma line 1 "/usr/include/math.h" 1 3 4 ::: 195
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 224
#pragma line 115 "/usr/include/features.h" 3 4 ::: 317
#pragma line 139 "/usr/include/features.h" 3 4 ::: 334
#pragma line 169 "/usr/include/features.h" 3 4 ::: 344
#pragma line 179 "/usr/include/features.h" 3 4 ::: 347
#pragma line 294 "/usr/include/features.h" 3 4 ::: 359
#pragma line 1 "/usr/include/sys/cdefs.h" 1 3 4 ::: 396
#pragma line 72 "/usr/include/sys/cdefs.h" 3 4 ::: 442
#pragma line 98 "/usr/include/sys/cdefs.h" 3 4 ::: 460
#pragma line 111 "/usr/include/sys/cdefs.h" 3 4 ::: 466
#pragma line 123 "/usr/include/sys/cdefs.h" 3 4 ::: 470
#pragma line 155 "/usr/include/sys/cdefs.h" 3 4 ::: 488
#pragma line 178 "/usr/include/sys/cdefs.h" 3 4 ::: 498
#pragma line 222 "/usr/include/sys/cdefs.h" 3 4 ::: 535
#pragma line 275 "/usr/include/sys/cdefs.h" 3 4 ::: 576
#pragma line 313 "/usr/include/sys/cdefs.h" 3 4 ::: 600
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 601
#pragma line 314 "/usr/include/sys/cdefs.h" 2 3 4 ::: 603
#pragma line 330 "/usr/include/features.h" 2 3 4 ::: 604
#pragma line 1 "/usr/include/gnu/stubs.h" 1 3 4 ::: 628
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 633
#pragma line 5 "/usr/include/gnu/stubs.h" 2 3 4 ::: 635
#pragma line 1 "/usr/include/gnu/stubs-64.h" 1 3 4 ::: 640
#pragma line 10 "/usr/include/gnu/stubs.h" 2 3 4 ::: 645
#pragma line 353 "/usr/include/features.h" 2 3 4 ::: 646
#pragma line 29 "/usr/include/math.h" 2 3 4 ::: 647
#pragma line 1 "/usr/include/bits/huge_val.h" 1 3 4 ::: 654
#pragma line 35 "/usr/include/math.h" 2 3 4 ::: 681
#pragma line 46 "/usr/include/math.h" 3 4 ::: 682
#pragma line 1 "/usr/include/bits/mathdef.h" 1 3 4 ::: 685
#pragma line 48 "/usr/include/math.h" 2 3 4 ::: 703
#pragma line 71 "/usr/include/math.h" 3 4 ::: 709
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 710
#pragma line 88 "/usr/include/bits/mathcalls.h" 3 4 ::: 788
#pragma line 128 "/usr/include/bits/mathcalls.h" 3 4 ::: 818
#pragma line 150 "/usr/include/bits/mathcalls.h" 3 4 ::: 827
#pragma line 230 "/usr/include/bits/mathcalls.h" 3 4 ::: 897
#pragma line 264 "/usr/include/bits/mathcalls.h" 3 4 ::: 921
#pragma line 363 "/usr/include/bits/mathcalls.h" 3 4 ::: 956
#pragma line 72 "/usr/include/math.h" 2 3 4 ::: 959
#pragma line 94 "/usr/include/math.h" 3 4 ::: 970
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 971
#pragma line 88 "/usr/include/bits/mathcalls.h" 3 4 ::: 1049
#pragma line 128 "/usr/include/bits/mathcalls.h" 3 4 ::: 1079
#pragma line 150 "/usr/include/bits/mathcalls.h" 3 4 ::: 1088
#pragma line 230 "/usr/include/bits/mathcalls.h" 3 4 ::: 1158
#pragma line 264 "/usr/include/bits/mathcalls.h" 3 4 ::: 1182
#pragma line 363 "/usr/include/bits/mathcalls.h" 3 4 ::: 1217
#pragma line 95 "/usr/include/math.h" 2 3 4 ::: 1220
#pragma line 141 "/usr/include/math.h" 3 4 ::: 1221
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 1222
#pragma line 88 "/usr/include/bits/mathcalls.h" 3 4 ::: 1300
#pragma line 128 "/usr/include/bits/mathcalls.h" 3 4 ::: 1330
#pragma line 150 "/usr/include/bits/mathcalls.h" 3 4 ::: 1339
#pragma line 230 "/usr/include/bits/mathcalls.h" 3 4 ::: 1409
#pragma line 264 "/usr/include/bits/mathcalls.h" 3 4 ::: 1433
#pragma line 363 "/usr/include/bits/mathcalls.h" 3 4 ::: 1468
#pragma line 142 "/usr/include/math.h" 2 3 4 ::: 1471
#pragma line 156 "/usr/include/math.h" 3 4 ::: 1472
#pragma line 283 "/usr/include/math.h" 3 4 ::: 1479
#pragma line 348 "/usr/include/math.h" 3 4 ::: 1533
#pragma line 365 "/usr/include/math.h" 3 4 ::: 1535
#pragma line 385 "/usr/include/math.h" 3 4 ::: 1539
#pragma line 407 "/usr/include/math.h" 3 4 ::: 1543
#pragma line 2 "./CND.h" 2 ::: 1545
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 1546
#pragma line 36 "/usr/include/time.h" 3 4 ::: 1569
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1574
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1615
#pragma line 40 "/usr/include/time.h" 2 3 4 ::: 1618
#pragma line 1 "/usr/include/bits/time.h" 1 3 4 ::: 1623
#pragma line 45 "/usr/include/bits/time.h" 3 4 ::: 1657
#pragma line 44 "/usr/include/time.h" 2 3 4 ::: 1668
#pragma line 57 "/usr/include/time.h" 3 4 ::: 1671
#pragma line 1 "/usr/include/bits/types.h" 1 3 4 ::: 1672
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 1701
#pragma line 29 "/usr/include/bits/types.h" 2 3 4 ::: 1703
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1706
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1731
#pragma line 32 "/usr/include/bits/types.h" 2 3 4 ::: 1734
#pragma line 73 "/usr/include/bits/types.h" 3 4 ::: 1761
#pragma line 129 "/usr/include/bits/types.h" 3 4 ::: 1790
#pragma line 1 "/usr/include/bits/typesizes.h" 1 3 4 ::: 1797
#pragma line 27 "/usr/include/bits/typesizes.h" 3 4 ::: 1816
#pragma line 62 "/usr/include/bits/typesizes.h" 3 4 ::: 1819
#pragma line 135 "/usr/include/bits/types.h" 2 3 4 ::: 1821
#pragma line 58 "/usr/include/time.h" 2 3 4 ::: 1883
#pragma line 76 "/usr/include/time.h" 3 4 ::: 1888
#pragma line 92 "/usr/include/time.h" 3 4 ::: 1891
#pragma line 104 "/usr/include/time.h" 3 4 ::: 1894
#pragma line 119 "/usr/include/time.h" 3 4 ::: 1897
#pragma line 230 "/usr/include/time.h" 3 4 ::: 1982
#pragma line 3 "./CND.h" 2 ::: 2127
#pragma line 1 "/usr/include/stdlib.h" 1 3 4 ::: 2128
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2162
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2187
#pragma line 34 "/usr/include/stdlib.h" 2 3 4 ::: 2190
#pragma line 97 "/usr/include/stdlib.h" 3 4 ::: 2191
#pragma line 128 "/usr/include/stdlib.h" 3 4 ::: 2206
#pragma line 183 "/usr/include/stdlib.h" 3 4 ::: 2247
#pragma line 276 "/usr/include/stdlib.h" 3 4 ::: 2283
#pragma line 426 "/usr/include/stdlib.h" 3 4 ::: 2327
#pragma line 1 "/usr/include/sys/types.h" 1 3 4 ::: 2341
#pragma line 35 "/usr/include/sys/types.h" 3 4 ::: 2364
#pragma line 62 "/usr/include/sys/types.h" 3 4 ::: 2381
#pragma line 105 "/usr/include/sys/types.h" 3 4 ::: 2409
#pragma line 147 "/usr/include/sys/types.h" 3 4 ::: 2429
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2430
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2455
#pragma line 148 "/usr/include/sys/types.h" 2 3 4 ::: 2458
#pragma line 187 "/usr/include/sys/types.h" 3 4 ::: 2468
#pragma line 1 "/usr/include/endian.h" 1 3 4 ::: 2500
#pragma line 1 "/usr/include/bits/endian.h" 1 3 4 ::: 2538
#pragma line 38 "/usr/include/endian.h" 2 3 4 ::: 2540
#pragma line 218 "/usr/include/sys/types.h" 2 3 4 ::: 2544
#pragma line 1 "/usr/include/sys/select.h" 1 3 4 ::: 2548
#pragma line 1 "/usr/include/bits/select.h" 1 3 4 ::: 2580
#pragma line 32 "/usr/include/sys/select.h" 2 3 4 ::: 2606
#pragma line 1 "/usr/include/bits/sigset.h" 1 3 4 ::: 2610
#pragma line 35 "/usr/include/sys/select.h" 2 3 4 ::: 2651
#pragma line 1 "/usr/include/bits/time.h" 1 3 4 ::: 2664
#pragma line 67 "/usr/include/bits/time.h" 3 4 ::: 2687
#pragma line 47 "/usr/include/sys/select.h" 2 3 4 ::: 2695
#pragma line 101 "/usr/include/sys/select.h" 3 4 ::: 2742
#pragma line 221 "/usr/include/sys/types.h" 2 3 4 ::: 2768
#pragma line 1 "/usr/include/sys/sysmacros.h" 1 3 4 ::: 2772
#pragma line 224 "/usr/include/sys/types.h" 2 3 4 ::: 2836
#pragma line 268 "/usr/include/sys/types.h" 3 4 ::: 2857
#pragma line 1 "/usr/include/bits/pthreadtypes.h" 1 3 4 ::: 2861
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 2885
#pragma line 24 "/usr/include/bits/pthreadtypes.h" 2 3 4 ::: 2887
#pragma line 48 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 2888
#pragma line 74 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 2907
#pragma line 101 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 2926
#pragma line 187 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 2995
#pragma line 271 "/usr/include/sys/types.h" 2 3 4 ::: 3026
#pragma line 439 "/usr/include/stdlib.h" 2 3 4 ::: 3027
#pragma line 588 "/usr/include/stdlib.h" 3 4 ::: 3169
#pragma line 1 "/usr/include/alloca.h" 1 3 4 ::: 3195
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3221
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3246
#pragma line 26 "/usr/include/alloca.h" 2 3 4 ::: 3249
#pragma line 613 "/usr/include/stdlib.h" 2 3 4 ::: 3258
#pragma line 659 "/usr/include/stdlib.h" 3 4 ::: 3293
#pragma line 724 "/usr/include/stdlib.h" 3 4 ::: 3345
#pragma line 751 "/usr/include/stdlib.h" 3 4 ::: 3361
#pragma line 796 "/usr/include/stdlib.h" 3 4 ::: 3398
#pragma line 815 "/usr/include/stdlib.h" 3 4 ::: 3406
#pragma line 922 "/usr/include/stdlib.h" 3 4 ::: 3491
#pragma line 958 "/usr/include/stdlib.h" 3 4 ::: 3497
#pragma line 4 "./CND.h" 2 ::: 3507
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 3508
#pragma line 34 "/usr/include/stdio.h" 3 4 ::: 3531
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3532
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3557
#pragma line 35 "/usr/include/stdio.h" 2 3 4 ::: 3560
#pragma line 45 "/usr/include/stdio.h" 3 4 ::: 3561
#pragma line 61 "/usr/include/stdio.h" 3 4 ::: 3564
#pragma line 72 "/usr/include/stdio.h" 3 4 ::: 3567
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 3568
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 3601
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3616
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3641
#pragma line 15 "/usr/include/_G_config.h" 2 3 4 ::: 3648
#pragma line 24 "/usr/include/_G_config.h" 3 4 ::: 3649
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 3650
#pragma line 48 "/usr/include/wchar.h" 3 4 ::: 3673
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3674
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3699
#pragma line 49 "/usr/include/wchar.h" 2 3 4 ::: 3702
#pragma line 1 "/usr/include/bits/wchar.h" 1 3 4 ::: 3704
#pragma line 51 "/usr/include/wchar.h" 2 3 4 ::: 3723
#pragma line 62 "/usr/include/wchar.h" 3 4 ::: 3727
#pragma line 75 "/usr/include/wchar.h" 3 4 ::: 3730
#pragma line 25 "/usr/include/_G_config.h" 2 3 4 ::: 3747
#pragma line 44 "/usr/include/_G_config.h" 3 4 ::: 3759
#pragma line 1 "/usr/include/gconv.h" 1 3 4 ::: 3760
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 3789
#pragma line 48 "/usr/include/wchar.h" 3 4 ::: 3812
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3813
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3838
#pragma line 49 "/usr/include/wchar.h" 2 3 4 ::: 3841
#pragma line 62 "/usr/include/wchar.h" 3 4 ::: 3847
#pragma line 89 "/usr/include/wchar.h" 3 4 ::: 3850
#pragma line 29 "/usr/include/gconv.h" 2 3 4 ::: 3853
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3856
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3881
#pragma line 32 "/usr/include/gconv.h" 2 3 4 ::: 3884
#pragma line 45 "/usr/include/_G_config.h" 2 3 4 ::: 4031
#pragma line 84 "/usr/include/_G_config.h" 3 4 ::: 4051
#pragma line 33 "/usr/include/libio.h" 2 3 4 ::: 4058
#pragma line 51 "/usr/include/libio.h" 3 4 ::: 4060
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 4064
#pragma line 54 "/usr/include/libio.h" 2 3 4 ::: 4113
#pragma line 74 "/usr/include/libio.h" 3 4 ::: 4114
#pragma line 114 "/usr/include/libio.h" 3 4 ::: 4116
#pragma line 147 "/usr/include/libio.h" 3 4 ::: 4122
#pragma line 167 "/usr/include/libio.h" 3 4 ::: 4124
#pragma line 200 "/usr/include/libio.h" 3 4 ::: 4148
#pragma line 268 "/usr/include/libio.h" 3 4 ::: 4159
#pragma line 316 "/usr/include/libio.h" 3 4 ::: 4200
#pragma line 325 "/usr/include/libio.h" 3 4 ::: 4202
#pragma line 357 "/usr/include/libio.h" 3 4 ::: 4224
#pragma line 413 "/usr/include/libio.h" 3 4 ::: 4250
#pragma line 451 "/usr/include/libio.h" 3 4 ::: 4257
#pragma line 481 "/usr/include/libio.h" 3 4 ::: 4272
#pragma line 73 "/usr/include/stdio.h" 2 3 4 ::: 4284
#pragma line 85 "/usr/include/stdio.h" 3 4 ::: 4285
#pragma line 97 "/usr/include/stdio.h" 3 4 ::: 4290
#pragma line 1 "/usr/include/bits/stdio_lim.h" 1 3 4 ::: 4333
#pragma line 139 "/usr/include/stdio.h" 2 3 4 ::: 4351
#pragma line 166 "/usr/include/stdio.h" 3 4 ::: 4370
#pragma line 184 "/usr/include/stdio.h" 3 4 ::: 4377
#pragma line 244 "/usr/include/stdio.h" 3 4 ::: 4423
#pragma line 279 "/usr/include/stdio.h" 3 4 ::: 4437
#pragma line 301 "/usr/include/stdio.h" 3 4 ::: 4440
#pragma line 395 "/usr/include/stdio.h" 3 4 ::: 4504
#pragma line 437 "/usr/include/stdio.h" 3 4 ::: 4519
#pragma line 586 "/usr/include/stdio.h" 3 4 ::: 4624
#pragma line 632 "/usr/include/stdio.h" 3 4 ::: 4657
#pragma line 695 "/usr/include/stdio.h" 3 4 ::: 4706
#pragma line 726 "/usr/include/stdio.h" 3 4 ::: 4717
#pragma line 1 "/usr/include/bits/sys_errlist.h" 1 3 4 ::: 4747
#pragma line 755 "/usr/include/stdio.h" 2 3 4 ::: 4776
#pragma line 811 "/usr/include/stdio.h" 3 4 ::: 4809
#pragma line 832 "/usr/include/stdio.h" 3 4 ::: 4821
#pragma line 5 "./CND.h" 2 ::: 4824
#pragma line 2 "CND.c" 2 ::: 4827
#pragma line 12 "CND.c" ::: 4828
