#pragma line 1 "CND.cpp" ::: 0
#pragma line 1 "CND.cpp" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 155 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 12
#pragma line 145 "/opt/xilinx/Vivado_HLS/2014.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 65
#pragma line 401 "/opt/xilinx/Vivado_HLS/2014.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 195
#pragma line 8 "<command line>" 2 ::: 198
#pragma line 1 "<built-in>" 2 ::: 199
#pragma line 1 "CND.cpp" 2 ::: 200
#pragma line 1 "./CND.h" 1 ::: 201
#pragma line 1 "/usr/include/math.h" 1 3 4 ::: 202
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 231
#pragma line 115 "/usr/include/features.h" 3 4 ::: 324
#pragma line 139 "/usr/include/features.h" 3 4 ::: 341
#pragma line 169 "/usr/include/features.h" 3 4 ::: 351
#pragma line 179 "/usr/include/features.h" 3 4 ::: 354
#pragma line 294 "/usr/include/features.h" 3 4 ::: 366
#pragma line 1 "/usr/include/sys/cdefs.h" 1 3 4 ::: 403
#pragma line 72 "/usr/include/sys/cdefs.h" 3 4 ::: 449
#pragma line 98 "/usr/include/sys/cdefs.h" 3 4 ::: 467
#pragma line 111 "/usr/include/sys/cdefs.h" 3 4 ::: 473
#pragma line 123 "/usr/include/sys/cdefs.h" 3 4 ::: 477
#pragma line 155 "/usr/include/sys/cdefs.h" 3 4 ::: 495
#pragma line 178 "/usr/include/sys/cdefs.h" 3 4 ::: 505
#pragma line 222 "/usr/include/sys/cdefs.h" 3 4 ::: 542
#pragma line 275 "/usr/include/sys/cdefs.h" 3 4 ::: 583
#pragma line 313 "/usr/include/sys/cdefs.h" 3 4 ::: 607
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 608
#pragma line 314 "/usr/include/sys/cdefs.h" 2 3 4 ::: 610
#pragma line 330 "/usr/include/features.h" 2 3 4 ::: 611
#pragma line 1 "/usr/include/gnu/stubs.h" 1 3 4 ::: 635
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 640
#pragma line 5 "/usr/include/gnu/stubs.h" 2 3 4 ::: 642
#pragma line 1 "/usr/include/gnu/stubs-64.h" 1 3 4 ::: 647
#pragma line 10 "/usr/include/gnu/stubs.h" 2 3 4 ::: 652
#pragma line 353 "/usr/include/features.h" 2 3 4 ::: 653
#pragma line 29 "/usr/include/math.h" 2 3 4 ::: 654
#pragma line 1 "/usr/include/bits/huge_val.h" 1 3 4 ::: 661
#pragma line 35 "/usr/include/math.h" 2 3 4 ::: 688
#pragma line 1 "/usr/include/bits/huge_valf.h" 1 3 4 ::: 690
#pragma line 37 "/usr/include/math.h" 2 3 4 ::: 717
#pragma line 1 "/usr/include/bits/huge_vall.h" 1 3 4 ::: 718
#pragma line 38 "/usr/include/math.h" 2 3 4 ::: 738
#pragma line 1 "/usr/include/bits/inf.h" 1 3 4 ::: 742
#pragma line 41 "/usr/include/math.h" 2 3 4 ::: 767
#pragma line 1 "/usr/include/bits/nan.h" 1 3 4 ::: 771
#pragma line 44 "/usr/include/math.h" 2 3 4 ::: 797
#pragma line 1 "/usr/include/bits/mathdef.h" 1 3 4 ::: 802
#pragma line 26 "/usr/include/bits/mathdef.h" 3 4 ::: 820
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 821
#pragma line 27 "/usr/include/bits/mathdef.h" 2 3 4 ::: 823
#pragma line 44 "/usr/include/bits/mathdef.h" 3 4 ::: 831
#pragma line 48 "/usr/include/math.h" 2 3 4 ::: 833
#pragma line 71 "/usr/include/math.h" 3 4 ::: 839
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 840
#pragma line 72 "/usr/include/math.h" 2 3 4 ::: 1205
#pragma line 94 "/usr/include/math.h" 3 4 ::: 1216
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 1217
#pragma line 95 "/usr/include/math.h" 2 3 4 ::: 1582
#pragma line 141 "/usr/include/math.h" 3 4 ::: 1583
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 1584
#pragma line 142 "/usr/include/math.h" 2 3 4 ::: 1949
#pragma line 156 "/usr/include/math.h" 3 4 ::: 1950
#pragma line 224 "/usr/include/math.h" 3 4 ::: 2008
#pragma line 236 "/usr/include/math.h" 3 4 ::: 2010
#pragma line 248 "/usr/include/math.h" 3 4 ::: 2012
#pragma line 264 "/usr/include/math.h" 3 4 ::: 2018
#pragma line 276 "/usr/include/math.h" 3 4 ::: 2020
#pragma line 348 "/usr/include/math.h" 3 4 ::: 2081
#pragma line 365 "/usr/include/math.h" 3 4 ::: 2083
#pragma line 385 "/usr/include/math.h" 3 4 ::: 2087
#pragma line 407 "/usr/include/math.h" 3 4 ::: 2102
#pragma line 465 "/usr/include/math.h" 3 4 ::: 2152
#pragma line 2 "./CND.h" 2 ::: 2154
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 2155
#pragma line 31 "/usr/include/time.h" 3 4 ::: 2178
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2188
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2224
#pragma line 40 "/usr/include/time.h" 2 3 4 ::: 2227
#pragma line 1 "/usr/include/bits/time.h" 1 3 4 ::: 2232
#pragma line 45 "/usr/include/bits/time.h" 3 4 ::: 2266
#pragma line 44 "/usr/include/time.h" 2 3 4 ::: 2277
#pragma line 57 "/usr/include/time.h" 3 4 ::: 2280
#pragma line 1 "/usr/include/bits/types.h" 1 3 4 ::: 2281
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 2310
#pragma line 29 "/usr/include/bits/types.h" 2 3 4 ::: 2312
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2315
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2340
#pragma line 32 "/usr/include/bits/types.h" 2 3 4 ::: 2343
#pragma line 73 "/usr/include/bits/types.h" 3 4 ::: 2370
#pragma line 129 "/usr/include/bits/types.h" 3 4 ::: 2399
#pragma line 1 "/usr/include/bits/typesizes.h" 1 3 4 ::: 2406
#pragma line 27 "/usr/include/bits/typesizes.h" 3 4 ::: 2425
#pragma line 62 "/usr/include/bits/typesizes.h" 3 4 ::: 2428
#pragma line 135 "/usr/include/bits/types.h" 2 3 4 ::: 2430
#pragma line 58 "/usr/include/time.h" 2 3 4 ::: 2492
#pragma line 76 "/usr/include/time.h" 3 4 ::: 2497
#pragma line 92 "/usr/include/time.h" 3 4 ::: 2500
#pragma line 104 "/usr/include/time.h" 3 4 ::: 2503
#pragma line 119 "/usr/include/time.h" 3 4 ::: 2506
#pragma line 1 "/usr/include/xlocale.h" 1 3 4 ::: 2605
#pragma line 217 "/usr/include/time.h" 2 3 4 ::: 2646
#pragma line 3 "./CND.h" 2 ::: 2847
#pragma line 1 "/usr/include/stdlib.h" 1 3 4 ::: 2848
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2882
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2907
#pragma line 34 "/usr/include/stdlib.h" 2 3 4 ::: 2910
#pragma line 1 "/usr/include/bits/waitflags.h" 1 3 4 ::: 2920
#pragma line 43 "/usr/include/stdlib.h" 2 3 4 ::: 2950
#pragma line 1 "/usr/include/bits/waitstatus.h" 1 3 4 ::: 2951
#pragma line 65 "/usr/include/bits/waitstatus.h" 3 4 ::: 3008
#pragma line 1 "/usr/include/endian.h" 1 3 4 ::: 3009
#pragma line 1 "/usr/include/bits/endian.h" 1 3 4 ::: 3047
#pragma line 38 "/usr/include/endian.h" 2 3 4 ::: 3049
#pragma line 66 "/usr/include/bits/waitstatus.h" 2 3 4 ::: 3053
#pragma line 44 "/usr/include/stdlib.h" 2 3 4 ::: 3087
#pragma line 58 "/usr/include/stdlib.h" 3 4 ::: 3093
#pragma line 84 "/usr/include/stdlib.h" 3 4 ::: 3098
#pragma line 97 "/usr/include/stdlib.h" 3 4 ::: 3100
#pragma line 426 "/usr/include/stdlib.h" 3 4 ::: 3323
#pragma line 1 "/usr/include/sys/types.h" 1 3 4 ::: 3337
#pragma line 105 "/usr/include/sys/types.h" 3 4 ::: 3433
#pragma line 137 "/usr/include/sys/types.h" 3 4 ::: 3453
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3465
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3490
#pragma line 148 "/usr/include/sys/types.h" 2 3 4 ::: 3493
#pragma line 187 "/usr/include/sys/types.h" 3 4 ::: 3503
#pragma line 1 "/usr/include/sys/select.h" 1 3 4 ::: 3538
#pragma line 1 "/usr/include/bits/select.h" 1 3 4 ::: 3570
#pragma line 32 "/usr/include/sys/select.h" 2 3 4 ::: 3596
#pragma line 1 "/usr/include/bits/sigset.h" 1 3 4 ::: 3600
#pragma line 35 "/usr/include/sys/select.h" 2 3 4 ::: 3641
#pragma line 1 "/usr/include/bits/time.h" 1 3 4 ::: 3654
#pragma line 67 "/usr/include/bits/time.h" 3 4 ::: 3677
#pragma line 47 "/usr/include/sys/select.h" 2 3 4 ::: 3685
#pragma line 221 "/usr/include/sys/types.h" 2 3 4 ::: 3768
#pragma line 1 "/usr/include/sys/sysmacros.h" 1 3 4 ::: 3772
#pragma line 224 "/usr/include/sys/types.h" 2 3 4 ::: 3836
#pragma line 262 "/usr/include/sys/types.h" 3 4 ::: 3857
#pragma line 1 "/usr/include/bits/pthreadtypes.h" 1 3 4 ::: 3867
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 3891
#pragma line 24 "/usr/include/bits/pthreadtypes.h" 2 3 4 ::: 3893
#pragma line 48 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 3894
#pragma line 74 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 3913
#pragma line 101 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 3932
#pragma line 187 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 4001
#pragma line 271 "/usr/include/sys/types.h" 2 3 4 ::: 4032
#pragma line 439 "/usr/include/stdlib.h" 2 3 4 ::: 4036
#pragma line 588 "/usr/include/stdlib.h" 3 4 ::: 4178
#pragma line 1 "/usr/include/alloca.h" 1 3 4 ::: 4204
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 4230
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 4255
#pragma line 26 "/usr/include/alloca.h" 2 3 4 ::: 4258
#pragma line 613 "/usr/include/stdlib.h" 2 3 4 ::: 4273
#pragma line 719 "/usr/include/stdlib.h" 3 4 ::: 4371
#pragma line 977 "/usr/include/stdlib.h" 3 4 ::: 4620
#pragma line 4 "./CND.h" 2 ::: 4622
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 4623
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 4658
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 4683
#pragma line 35 "/usr/include/stdio.h" 2 3 4 ::: 4686
#pragma line 45 "/usr/include/stdio.h" 3 4 ::: 4687
#pragma line 61 "/usr/include/stdio.h" 3 4 ::: 4690
#pragma line 72 "/usr/include/stdio.h" 3 4 ::: 4693
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 4694
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 4727
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 4742
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 4767
#pragma line 15 "/usr/include/_G_config.h" 2 3 4 ::: 4774
#pragma line 24 "/usr/include/_G_config.h" 3 4 ::: 4775
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 4776
#pragma line 48 "/usr/include/wchar.h" 3 4 ::: 4799
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 4800
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 4825
#pragma line 49 "/usr/include/wchar.h" 2 3 4 ::: 4828
#pragma line 1 "/usr/include/bits/wchar.h" 1 3 4 ::: 4830
#pragma line 51 "/usr/include/wchar.h" 2 3 4 ::: 4849
#pragma line 62 "/usr/include/wchar.h" 3 4 ::: 4853
#pragma line 75 "/usr/include/wchar.h" 3 4 ::: 4856
#pragma line 25 "/usr/include/_G_config.h" 2 3 4 ::: 4873
#pragma line 44 "/usr/include/_G_config.h" 3 4 ::: 4885
#pragma line 1 "/usr/include/gconv.h" 1 3 4 ::: 4886
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 4915
#pragma line 48 "/usr/include/wchar.h" 3 4 ::: 4938
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 4939
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 4964
#pragma line 49 "/usr/include/wchar.h" 2 3 4 ::: 4967
#pragma line 62 "/usr/include/wchar.h" 3 4 ::: 4973
#pragma line 89 "/usr/include/wchar.h" 3 4 ::: 4976
#pragma line 29 "/usr/include/gconv.h" 2 3 4 ::: 4979
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 4982
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 5007
#pragma line 32 "/usr/include/gconv.h" 2 3 4 ::: 5010
#pragma line 45 "/usr/include/_G_config.h" 2 3 4 ::: 5157
#pragma line 84 "/usr/include/_G_config.h" 3 4 ::: 5177
#pragma line 33 "/usr/include/libio.h" 2 3 4 ::: 5184
#pragma line 51 "/usr/include/libio.h" 3 4 ::: 5186
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 5190
#pragma line 54 "/usr/include/libio.h" 2 3 4 ::: 5239
#pragma line 74 "/usr/include/libio.h" 3 4 ::: 5240
#pragma line 114 "/usr/include/libio.h" 3 4 ::: 5242
#pragma line 147 "/usr/include/libio.h" 3 4 ::: 5248
#pragma line 167 "/usr/include/libio.h" 3 4 ::: 5250
#pragma line 200 "/usr/include/libio.h" 3 4 ::: 5274
#pragma line 268 "/usr/include/libio.h" 3 4 ::: 5285
#pragma line 316 "/usr/include/libio.h" 3 4 ::: 5326
#pragma line 325 "/usr/include/libio.h" 3 4 ::: 5328
#pragma line 357 "/usr/include/libio.h" 3 4 ::: 5350
#pragma line 451 "/usr/include/libio.h" 3 4 ::: 5413
#pragma line 481 "/usr/include/libio.h" 3 4 ::: 5428
#pragma line 543 "/usr/include/libio.h" 3 4 ::: 5440
#pragma line 73 "/usr/include/stdio.h" 2 3 4 ::: 5442
#pragma line 1 "/usr/include/bits/stdio_lim.h" 1 3 4 ::: 5509
#pragma line 139 "/usr/include/stdio.h" 2 3 4 ::: 5527
#pragma line 181 "/usr/include/stdio.h" 3 4 ::: 5561
#pragma line 271 "/usr/include/stdio.h" 3 4 ::: 5638
#pragma line 695 "/usr/include/stdio.h" 3 4 ::: 6048
#pragma line 719 "/usr/include/stdio.h" 3 4 ::: 6059
#pragma line 1 "/usr/include/bits/sys_errlist.h" 1 3 4 ::: 6096
#pragma line 755 "/usr/include/stdio.h" 2 3 4 ::: 6129
#pragma line 832 "/usr/include/stdio.h" 3 4 ::: 6197
#pragma line 844 "/usr/include/stdio.h" 3 4 ::: 6200
#pragma line 5 "./CND.h" 2 ::: 6202
#pragma line 2 "CND.cpp" 2 ::: 6205
