lappend pragmaStatus0 {pragma "PIPELINE" source "/home/student/vff6/ece5775/assignments/HighLevelSynth/options-accel/final_design/BlackScholes_dut.cpp" location "BlackScholesWrapper/loop" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'BlackScholesWrapper' does not exist in any synthesis source file."}
lappend pragmaStatus1 {pragma "PIPELINE" source "/home/student/vff6/ece5775/assignments/HighLevelSynth/options-accel/final_design/BlackScholes_dut.cpp" location "BlackScholes" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'BlackScholes' does not exist in any synthesis source file."}
lappend pragmaStatus0 {pragma "PIPELINE" source "/home/student/vff6/ece5775/assignments/HighLevelSynth/options-accel/final_design/mt19937ar.cpp" location "BlackScholesWrapper/loop" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'BlackScholesWrapper' does not exist in any synthesis source file."}
lappend pragmaStatus1 {pragma "PIPELINE" source "/home/student/vff6/ece5775/assignments/HighLevelSynth/options-accel/final_design/mt19937ar.cpp" location "BlackScholes" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'BlackScholes' does not exist in any synthesis source file."}
lappend pragmaStatus0 {pragma "PIPELINE" source "/home/student/vff6/ece5775/assignments/HighLevelSynth/options-accel/final_design/CND.cpp" location "BlackScholesWrapper/loop" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'BlackScholesWrapper' does not exist in any synthesis source file."}
lappend pragmaStatus1 {pragma "PIPELINE" source "/home/student/vff6/ece5775/assignments/HighLevelSynth/options-accel/final_design/CND.cpp" location "BlackScholes" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'BlackScholes' does not exist in any synthesis source file."}
lappend pragmaStatus0 {pragma "PIPELINE" source "/home/student/vff6/ece5775/assignments/HighLevelSynth/options-accel/final_design/BlackScholes.cpp" location "BlackScholesWrapper/loop" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'BlackScholesWrapper' does not exist in any synthesis source file."}
lappend pragmaStatus1 {pragma "PIPELINE" source "/home/student/vff6/ece5775/assignments/HighLevelSynth/options-accel/final_design/BlackScholes.cpp" location "BlackScholes" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus0 {pragma "PIPELINE" source "/home/student/vff6/ece5775/assignments/HighLevelSynth/options-accel/final_design/BlackScholesWrapper.cpp" location "BlackScholesWrapper/loop" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus1 {pragma "PIPELINE" source "/home/student/vff6/ece5775/assignments/HighLevelSynth/options-accel/final_design/BlackScholesWrapper.cpp" location "BlackScholes" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'BlackScholes' does not exist in any synthesis source file."}
