// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.2
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _black_scholes_init_by_array_HH_
#define _black_scholes_init_by_array_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "black_scholes_mul_32s_31ns_32_6.h"
#include "black_scholes_mul_64s_21ns_64_6.h"
#include "black_scholes_mul_64s_31ns_64_6.h"

namespace ap_rtl {

struct black_scholes_init_by_array : public sc_module {
    // Port declarations 13
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<32> > mti;
    sc_out< sc_logic > mti_ap_vld;
    sc_out< sc_lv<10> > mt_address0;
    sc_out< sc_logic > mt_ce0;
    sc_out< sc_logic > mt_we0;
    sc_out< sc_lv<64> > mt_d0;
    sc_in< sc_lv<64> > mt_q0;


    // Module declarations
    black_scholes_init_by_array(sc_module_name name);
    SC_HAS_PROCESS(black_scholes_init_by_array);

    ~black_scholes_init_by_array();

    sc_trace_file* mVcdFile;

    black_scholes_mul_32s_31ns_32_6<1,6,32,31,32>* black_scholes_mul_32s_31ns_32_6_U1;
    black_scholes_mul_64s_21ns_64_6<2,6,64,21,64>* black_scholes_mul_64s_21ns_64_6_U2;
    black_scholes_mul_64s_31ns_64_6<3,6,64,31,64>* black_scholes_mul_64s_31ns_64_6_U3;
    sc_signal< sc_lv<6> > ap_CS_fsm;
    sc_signal< sc_lv<32> > tmp_1_i_cast_fu_240_p1;
    sc_signal< sc_lv<32> > tmp_1_i_cast_reg_552;
    sc_signal< sc_lv<1> > exitcond_i_fu_250_p2;
    sc_signal< sc_lv<32> > tmp_18_fu_281_p2;
    sc_signal< sc_lv<32> > tmp_18_reg_565;
    sc_signal< sc_lv<32> > tmp_9_i_cast_fu_292_p2;
    sc_signal< sc_lv<32> > tmp_9_i_cast_reg_570;
    sc_signal< sc_lv<10> > tmp_2_i_fu_306_p2;
    sc_signal< sc_lv<1> > tmp_fu_312_p2;
    sc_signal< sc_lv<64> > tmp_7_fu_333_p2;
    sc_signal< sc_lv<64> > tmp_7_reg_588;
    sc_signal< sc_lv<10> > mt_addr_reg_593;
    sc_signal< sc_lv<32> > tmp_25_fu_355_p1;
    sc_signal< sc_lv<32> > tmp_25_reg_598;
    sc_signal< sc_lv<32> > i_4_fu_431_p2;
    sc_signal< sc_lv<32> > j_1_fu_437_p2;
    sc_signal< sc_lv<32> > j_1_reg_608;
    sc_signal< sc_lv<1> > tmp_21_fu_443_p2;
    sc_signal< sc_lv<1> > tmp_21_reg_614;
    sc_signal< sc_lv<32> > p_s_fu_464_p3;
    sc_signal< sc_lv<32> > p_s_reg_618;
    sc_signal< sc_lv<10> > k_2_fu_471_p2;
    sc_signal< sc_lv<10> > k_2_reg_623;
    sc_signal< sc_lv<1> > tmp_3_fu_477_p2;
    sc_signal< sc_lv<64> > tmp_13_fu_498_p2;
    sc_signal< sc_lv<64> > tmp_13_reg_636;
    sc_signal< sc_lv<10> > mt_addr_3_reg_641;
    sc_signal< sc_lv<32> > tmp_27_fu_520_p1;
    sc_signal< sc_lv<32> > tmp_27_reg_646;
    sc_signal< sc_lv<32> > i_5_fu_534_p2;
    sc_signal< sc_lv<1> > tmp_22_fu_540_p2;
    sc_signal< sc_lv<1> > tmp_22_reg_656;
    sc_signal< sc_lv<10> > k_3_fu_546_p2;
    sc_signal< sc_lv<10> > tmp_1_i_reg_133;
    sc_signal< sc_lv<32> > i_reg_145;
    sc_signal< sc_lv<32> > j_reg_157;
    sc_signal< sc_lv<10> > k_reg_169;
    sc_signal< sc_lv<32> > i_1_reg_181;
    sc_signal< sc_lv<32> > i_3_phi_fu_221_p4;
    sc_signal< sc_lv<32> > i_2_reg_194;
    sc_signal< sc_lv<10> > k_1_reg_205;
    sc_signal< sc_lv<32> > i_3_reg_217;
    sc_signal< sc_lv<64> > tmp_4_i_fu_262_p1;
    sc_signal< sc_lv<64> > tmp_8_i_fu_297_p1;
    sc_signal< sc_lv<64> > tmp_5_fu_324_p1;
    sc_signal< sc_lv<64> > tmp_s_fu_344_p1;
    sc_signal< sc_lv<64> > tmp_11_fu_489_p1;
    sc_signal< sc_lv<64> > tmp_2_fu_509_p1;
    sc_signal< sc_lv<64> > tmp_i_cast_fu_302_p1;
    sc_signal< sc_lv<64> > tmp_20_cast_fu_426_p1;
    sc_signal< sc_lv<64> > tmp_17_cast_fu_529_p1;
    sc_signal< sc_lv<10> > tmp_3_i_fu_256_p2;
    sc_signal< sc_lv<32> > tmp_1_fu_267_p4;
    sc_signal< sc_lv<32> > tmp_17_fu_277_p1;
    sc_signal< sc_lv<32> > grp_fu_287_p0;
    sc_signal< sc_lv<31> > grp_fu_287_p1;
    sc_signal< sc_lv<32> > grp_fu_287_p2;
    sc_signal< sc_lv<32> > tmp_4_fu_318_p2;
    sc_signal< sc_lv<34> > grp_fu_230_p4;
    sc_signal< sc_lv<64> > tmp_23_fu_329_p1;
    sc_signal< sc_lv<64> > grp_fu_339_p0;
    sc_signal< sc_lv<21> > grp_fu_339_p1;
    sc_signal< sc_lv<64> > grp_fu_339_p2;
    sc_signal< sc_lv<64> > tmp_9_fu_349_p2;
    sc_signal< sc_lv<2> > tmp_24_fu_359_p1;
    sc_signal< sc_lv<1> > sel_tmp4_fu_375_p2;
    sc_signal< sc_lv<1> > sel_tmp2_fu_369_p2;
    sc_signal< sc_lv<1> > sel_tmp_fu_363_p2;
    sc_signal< sc_lv<1> > or_cond_fu_389_p2;
    sc_signal< sc_lv<11> > newSel_cast_cast_fu_381_p3;
    sc_signal< sc_lv<11> > newSel7_fu_395_p3;
    sc_signal< sc_lv<11> > newSel9_fu_403_p3;
    sc_signal< sc_lv<32> > tmp_19_fu_411_p2;
    sc_signal< sc_lv<32> > tmp_20_fu_416_p1;
    sc_signal< sc_lv<32> > tmp_19_cast_fu_420_p2;
    sc_signal< sc_lv<30> > tmp_28_fu_449_p4;
    sc_signal< sc_lv<1> > icmp_fu_458_p2;
    sc_signal< sc_lv<32> > tmp_10_fu_483_p2;
    sc_signal< sc_lv<64> > tmp_26_fu_494_p1;
    sc_signal< sc_lv<64> > grp_fu_504_p0;
    sc_signal< sc_lv<31> > grp_fu_504_p1;
    sc_signal< sc_lv<64> > grp_fu_504_p2;
    sc_signal< sc_lv<64> > tmp_15_fu_514_p2;
    sc_signal< sc_lv<32> > tmp_16_cast_fu_524_p2;
    sc_signal< sc_logic > grp_fu_287_ce;
    sc_signal< sc_logic > grp_fu_339_ce;
    sc_signal< sc_logic > grp_fu_504_ce;
    sc_signal< sc_lv<6> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<6> ap_ST_st1_fsm_0;
    static const sc_lv<6> ap_ST_st2_fsm_1;
    static const sc_lv<6> ap_ST_st3_fsm_2;
    static const sc_lv<6> ap_ST_st4_fsm_3;
    static const sc_lv<6> ap_ST_st5_fsm_4;
    static const sc_lv<6> ap_ST_st6_fsm_5;
    static const sc_lv<6> ap_ST_st7_fsm_6;
    static const sc_lv<6> ap_ST_st8_fsm_7;
    static const sc_lv<6> ap_ST_st9_fsm_8;
    static const sc_lv<6> ap_ST_st10_fsm_9;
    static const sc_lv<6> ap_ST_st11_fsm_10;
    static const sc_lv<6> ap_ST_st12_fsm_11;
    static const sc_lv<6> ap_ST_st13_fsm_12;
    static const sc_lv<6> ap_ST_st14_fsm_13;
    static const sc_lv<6> ap_ST_st15_fsm_14;
    static const sc_lv<6> ap_ST_st16_fsm_15;
    static const sc_lv<6> ap_ST_st17_fsm_16;
    static const sc_lv<6> ap_ST_st18_fsm_17;
    static const sc_lv<6> ap_ST_st19_fsm_18;
    static const sc_lv<6> ap_ST_st20_fsm_19;
    static const sc_lv<6> ap_ST_st21_fsm_20;
    static const sc_lv<6> ap_ST_st22_fsm_21;
    static const sc_lv<6> ap_ST_st23_fsm_22;
    static const sc_lv<6> ap_ST_st24_fsm_23;
    static const sc_lv<6> ap_ST_st25_fsm_24;
    static const sc_lv<6> ap_ST_st26_fsm_25;
    static const sc_lv<6> ap_ST_st27_fsm_26;
    static const sc_lv<6> ap_ST_st28_fsm_27;
    static const sc_lv<6> ap_ST_st29_fsm_28;
    static const sc_lv<6> ap_ST_st30_fsm_29;
    static const sc_lv<6> ap_ST_st31_fsm_30;
    static const sc_lv<6> ap_ST_st32_fsm_31;
    static const sc_lv<6> ap_ST_st33_fsm_32;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<10> ap_const_lv10_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<10> ap_const_lv10_270;
    static const sc_lv<10> ap_const_lv10_26F;
    static const sc_lv<64> ap_const_lv64_12BD6AA;
    static const sc_lv<64> ap_const_lv64_80000000;
    static const sc_lv<10> ap_const_lv10_0;
    static const sc_lv<32> ap_const_lv32_1E;
    static const sc_lv<32> ap_const_lv32_3F;
    static const sc_lv<10> ap_const_lv10_3FF;
    static const sc_lv<32> ap_const_lv32_3D;
    static const sc_lv<32> ap_const_lv32_6C078965;
    static const sc_lv<32> ap_const_lv32_FFFFFFFF;
    static const sc_lv<64> ap_const_lv64_19660D;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<2> ap_const_lv2_2;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<11> ap_const_lv11_123;
    static const sc_lv<11> ap_const_lv11_345;
    static const sc_lv<11> ap_const_lv11_234;
    static const sc_lv<11> ap_const_lv11_456;
    static const sc_lv<32> ap_const_lv32_26F;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<30> ap_const_lv30_1;
    static const sc_lv<64> ap_const_lv64_5D588B65;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_exitcond_i_fu_250_p2();
    void thread_grp_fu_230_p4();
    void thread_grp_fu_287_ce();
    void thread_grp_fu_287_p0();
    void thread_grp_fu_287_p1();
    void thread_grp_fu_339_ce();
    void thread_grp_fu_339_p0();
    void thread_grp_fu_339_p1();
    void thread_grp_fu_504_ce();
    void thread_grp_fu_504_p0();
    void thread_grp_fu_504_p1();
    void thread_i_3_phi_fu_221_p4();
    void thread_i_4_fu_431_p2();
    void thread_i_5_fu_534_p2();
    void thread_icmp_fu_458_p2();
    void thread_j_1_fu_437_p2();
    void thread_k_2_fu_471_p2();
    void thread_k_3_fu_546_p2();
    void thread_mt_address0();
    void thread_mt_ce0();
    void thread_mt_d0();
    void thread_mt_we0();
    void thread_mti();
    void thread_mti_ap_vld();
    void thread_newSel7_fu_395_p3();
    void thread_newSel9_fu_403_p3();
    void thread_newSel_cast_cast_fu_381_p3();
    void thread_or_cond_fu_389_p2();
    void thread_p_s_fu_464_p3();
    void thread_sel_tmp2_fu_369_p2();
    void thread_sel_tmp4_fu_375_p2();
    void thread_sel_tmp_fu_363_p2();
    void thread_tmp_10_fu_483_p2();
    void thread_tmp_11_fu_489_p1();
    void thread_tmp_13_fu_498_p2();
    void thread_tmp_15_fu_514_p2();
    void thread_tmp_16_cast_fu_524_p2();
    void thread_tmp_17_cast_fu_529_p1();
    void thread_tmp_17_fu_277_p1();
    void thread_tmp_18_fu_281_p2();
    void thread_tmp_19_cast_fu_420_p2();
    void thread_tmp_19_fu_411_p2();
    void thread_tmp_1_fu_267_p4();
    void thread_tmp_1_i_cast_fu_240_p1();
    void thread_tmp_20_cast_fu_426_p1();
    void thread_tmp_20_fu_416_p1();
    void thread_tmp_21_fu_443_p2();
    void thread_tmp_22_fu_540_p2();
    void thread_tmp_23_fu_329_p1();
    void thread_tmp_24_fu_359_p1();
    void thread_tmp_25_fu_355_p1();
    void thread_tmp_26_fu_494_p1();
    void thread_tmp_27_fu_520_p1();
    void thread_tmp_28_fu_449_p4();
    void thread_tmp_2_fu_509_p1();
    void thread_tmp_2_i_fu_306_p2();
    void thread_tmp_3_fu_477_p2();
    void thread_tmp_3_i_fu_256_p2();
    void thread_tmp_4_fu_318_p2();
    void thread_tmp_4_i_fu_262_p1();
    void thread_tmp_5_fu_324_p1();
    void thread_tmp_7_fu_333_p2();
    void thread_tmp_8_i_fu_297_p1();
    void thread_tmp_9_fu_349_p2();
    void thread_tmp_9_i_cast_fu_292_p2();
    void thread_tmp_fu_312_p2();
    void thread_tmp_i_cast_fu_302_p1();
    void thread_tmp_s_fu_344_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
