// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.2
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "black_scholes_init_by_array.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic black_scholes_init_by_array::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic black_scholes_init_by_array::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<6> black_scholes_init_by_array::ap_ST_st1_fsm_0 = "000000";
const sc_lv<6> black_scholes_init_by_array::ap_ST_st2_fsm_1 = "1";
const sc_lv<6> black_scholes_init_by_array::ap_ST_st3_fsm_2 = "10";
const sc_lv<6> black_scholes_init_by_array::ap_ST_st4_fsm_3 = "11";
const sc_lv<6> black_scholes_init_by_array::ap_ST_st5_fsm_4 = "100";
const sc_lv<6> black_scholes_init_by_array::ap_ST_st6_fsm_5 = "101";
const sc_lv<6> black_scholes_init_by_array::ap_ST_st7_fsm_6 = "110";
const sc_lv<6> black_scholes_init_by_array::ap_ST_st8_fsm_7 = "111";
const sc_lv<6> black_scholes_init_by_array::ap_ST_st9_fsm_8 = "1000";
const sc_lv<6> black_scholes_init_by_array::ap_ST_st10_fsm_9 = "1001";
const sc_lv<6> black_scholes_init_by_array::ap_ST_st11_fsm_10 = "1010";
const sc_lv<6> black_scholes_init_by_array::ap_ST_st12_fsm_11 = "1011";
const sc_lv<6> black_scholes_init_by_array::ap_ST_st13_fsm_12 = "1100";
const sc_lv<6> black_scholes_init_by_array::ap_ST_st14_fsm_13 = "1101";
const sc_lv<6> black_scholes_init_by_array::ap_ST_st15_fsm_14 = "1110";
const sc_lv<6> black_scholes_init_by_array::ap_ST_st16_fsm_15 = "1111";
const sc_lv<6> black_scholes_init_by_array::ap_ST_st17_fsm_16 = "10000";
const sc_lv<6> black_scholes_init_by_array::ap_ST_st18_fsm_17 = "10001";
const sc_lv<6> black_scholes_init_by_array::ap_ST_st19_fsm_18 = "10010";
const sc_lv<6> black_scholes_init_by_array::ap_ST_st20_fsm_19 = "10011";
const sc_lv<6> black_scholes_init_by_array::ap_ST_st21_fsm_20 = "10100";
const sc_lv<6> black_scholes_init_by_array::ap_ST_st22_fsm_21 = "10101";
const sc_lv<6> black_scholes_init_by_array::ap_ST_st23_fsm_22 = "10110";
const sc_lv<6> black_scholes_init_by_array::ap_ST_st24_fsm_23 = "10111";
const sc_lv<6> black_scholes_init_by_array::ap_ST_st25_fsm_24 = "11000";
const sc_lv<6> black_scholes_init_by_array::ap_ST_st26_fsm_25 = "11001";
const sc_lv<6> black_scholes_init_by_array::ap_ST_st27_fsm_26 = "11010";
const sc_lv<6> black_scholes_init_by_array::ap_ST_st28_fsm_27 = "11011";
const sc_lv<6> black_scholes_init_by_array::ap_ST_st29_fsm_28 = "11100";
const sc_lv<6> black_scholes_init_by_array::ap_ST_st30_fsm_29 = "11101";
const sc_lv<6> black_scholes_init_by_array::ap_ST_st31_fsm_30 = "11110";
const sc_lv<6> black_scholes_init_by_array::ap_ST_st32_fsm_31 = "11111";
const sc_lv<6> black_scholes_init_by_array::ap_ST_st33_fsm_32 = "100000";
const sc_lv<1> black_scholes_init_by_array::ap_const_lv1_0 = "0";
const sc_lv<10> black_scholes_init_by_array::ap_const_lv10_1 = "1";
const sc_lv<32> black_scholes_init_by_array::ap_const_lv32_1 = "1";
const sc_lv<32> black_scholes_init_by_array::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<10> black_scholes_init_by_array::ap_const_lv10_270 = "1001110000";
const sc_lv<10> black_scholes_init_by_array::ap_const_lv10_26F = "1001101111";
const sc_lv<64> black_scholes_init_by_array::ap_const_lv64_12BD6AA = "1001010111101011010101010";
const sc_lv<64> black_scholes_init_by_array::ap_const_lv64_80000000 = "10000000000000000000000000000000";
const sc_lv<10> black_scholes_init_by_array::ap_const_lv10_0 = "0000000000";
const sc_lv<32> black_scholes_init_by_array::ap_const_lv32_1E = "11110";
const sc_lv<32> black_scholes_init_by_array::ap_const_lv32_3F = "111111";
const sc_lv<10> black_scholes_init_by_array::ap_const_lv10_3FF = "1111111111";
const sc_lv<32> black_scholes_init_by_array::ap_const_lv32_3D = "111101";
const sc_lv<32> black_scholes_init_by_array::ap_const_lv32_6C078965 = "1101100000001111000100101100101";
const sc_lv<32> black_scholes_init_by_array::ap_const_lv32_FFFFFFFF = "11111111111111111111111111111111";
const sc_lv<64> black_scholes_init_by_array::ap_const_lv64_19660D = "110010110011000001101";
const sc_lv<2> black_scholes_init_by_array::ap_const_lv2_1 = "1";
const sc_lv<2> black_scholes_init_by_array::ap_const_lv2_2 = "10";
const sc_lv<2> black_scholes_init_by_array::ap_const_lv2_0 = "00";
const sc_lv<11> black_scholes_init_by_array::ap_const_lv11_123 = "100100011";
const sc_lv<11> black_scholes_init_by_array::ap_const_lv11_345 = "1101000101";
const sc_lv<11> black_scholes_init_by_array::ap_const_lv11_234 = "1000110100";
const sc_lv<11> black_scholes_init_by_array::ap_const_lv11_456 = "10001010110";
const sc_lv<32> black_scholes_init_by_array::ap_const_lv32_26F = "1001101111";
const sc_lv<32> black_scholes_init_by_array::ap_const_lv32_2 = "10";
const sc_lv<32> black_scholes_init_by_array::ap_const_lv32_1F = "11111";
const sc_lv<30> black_scholes_init_by_array::ap_const_lv30_1 = "1";
const sc_lv<64> black_scholes_init_by_array::ap_const_lv64_5D588B65 = "1011101010110001000101101100101";

black_scholes_init_by_array::black_scholes_init_by_array(sc_module_name name) : sc_module(name), mVcdFile(0) {
    black_scholes_mul_32s_31ns_32_6_U1 = new black_scholes_mul_32s_31ns_32_6<1,6,32,31,32>("black_scholes_mul_32s_31ns_32_6_U1");
    black_scholes_mul_32s_31ns_32_6_U1->clk(ap_clk);
    black_scholes_mul_32s_31ns_32_6_U1->reset(ap_rst);
    black_scholes_mul_32s_31ns_32_6_U1->din0(grp_fu_287_p0);
    black_scholes_mul_32s_31ns_32_6_U1->din1(grp_fu_287_p1);
    black_scholes_mul_32s_31ns_32_6_U1->ce(grp_fu_287_ce);
    black_scholes_mul_32s_31ns_32_6_U1->dout(grp_fu_287_p2);
    black_scholes_mul_64s_21ns_64_6_U2 = new black_scholes_mul_64s_21ns_64_6<2,6,64,21,64>("black_scholes_mul_64s_21ns_64_6_U2");
    black_scholes_mul_64s_21ns_64_6_U2->clk(ap_clk);
    black_scholes_mul_64s_21ns_64_6_U2->reset(ap_rst);
    black_scholes_mul_64s_21ns_64_6_U2->din0(grp_fu_339_p0);
    black_scholes_mul_64s_21ns_64_6_U2->din1(grp_fu_339_p1);
    black_scholes_mul_64s_21ns_64_6_U2->ce(grp_fu_339_ce);
    black_scholes_mul_64s_21ns_64_6_U2->dout(grp_fu_339_p2);
    black_scholes_mul_64s_31ns_64_6_U3 = new black_scholes_mul_64s_31ns_64_6<3,6,64,31,64>("black_scholes_mul_64s_31ns_64_6_U3");
    black_scholes_mul_64s_31ns_64_6_U3->clk(ap_clk);
    black_scholes_mul_64s_31ns_64_6_U3->reset(ap_rst);
    black_scholes_mul_64s_31ns_64_6_U3->din0(grp_fu_504_p0);
    black_scholes_mul_64s_31ns_64_6_U3->din1(grp_fu_504_p1);
    black_scholes_mul_64s_31ns_64_6_U3->ce(grp_fu_504_ce);
    black_scholes_mul_64s_31ns_64_6_U3->dout(grp_fu_504_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_3_fu_477_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_3_fu_477_p2 );

    SC_METHOD(thread_exitcond_i_fu_250_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_1_i_reg_133 );

    SC_METHOD(thread_grp_fu_230_p4);
    sensitive << ( mt_q0 );

    SC_METHOD(thread_grp_fu_287_ce);

    SC_METHOD(thread_grp_fu_287_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_18_reg_565 );

    SC_METHOD(thread_grp_fu_287_p1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_grp_fu_339_ce);

    SC_METHOD(thread_grp_fu_339_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_7_reg_588 );

    SC_METHOD(thread_grp_fu_339_p1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_grp_fu_504_ce);

    SC_METHOD(thread_grp_fu_504_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_13_reg_636 );

    SC_METHOD(thread_grp_fu_504_p1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_i_3_phi_fu_221_p4);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_22_reg_656 );
    sensitive << ( i_3_reg_217 );

    SC_METHOD(thread_i_4_fu_431_p2);
    sensitive << ( i_reg_145 );

    SC_METHOD(thread_i_5_fu_534_p2);
    sensitive << ( i_2_reg_194 );

    SC_METHOD(thread_icmp_fu_458_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_28_fu_449_p4 );

    SC_METHOD(thread_j_1_fu_437_p2);
    sensitive << ( j_reg_157 );

    SC_METHOD(thread_k_2_fu_471_p2);
    sensitive << ( k_reg_169 );

    SC_METHOD(thread_k_3_fu_546_p2);
    sensitive << ( k_1_reg_205 );

    SC_METHOD(thread_mt_address0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( mt_addr_reg_593 );
    sensitive << ( tmp_3_fu_477_p2 );
    sensitive << ( mt_addr_3_reg_641 );
    sensitive << ( tmp_4_i_fu_262_p1 );
    sensitive << ( tmp_8_i_fu_297_p1 );
    sensitive << ( tmp_5_fu_324_p1 );
    sensitive << ( tmp_s_fu_344_p1 );
    sensitive << ( tmp_11_fu_489_p1 );
    sensitive << ( tmp_2_fu_509_p1 );

    SC_METHOD(thread_mt_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_3_fu_477_p2 );

    SC_METHOD(thread_mt_d0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( mt_q0 );
    sensitive << ( tmp_3_fu_477_p2 );
    sensitive << ( tmp_i_cast_fu_302_p1 );
    sensitive << ( tmp_20_cast_fu_426_p1 );
    sensitive << ( tmp_17_cast_fu_529_p1 );

    SC_METHOD(thread_mt_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_21_reg_614 );
    sensitive << ( tmp_3_fu_477_p2 );
    sensitive << ( tmp_22_reg_656 );

    SC_METHOD(thread_mti);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_1_i_reg_133 );

    SC_METHOD(thread_mti_ap_vld);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_newSel7_fu_395_p3);
    sensitive << ( sel_tmp_fu_363_p2 );

    SC_METHOD(thread_newSel9_fu_403_p3);
    sensitive << ( or_cond_fu_389_p2 );
    sensitive << ( newSel_cast_cast_fu_381_p3 );
    sensitive << ( newSel7_fu_395_p3 );

    SC_METHOD(thread_newSel_cast_cast_fu_381_p3);
    sensitive << ( sel_tmp4_fu_375_p2 );

    SC_METHOD(thread_or_cond_fu_389_p2);
    sensitive << ( sel_tmp4_fu_375_p2 );
    sensitive << ( sel_tmp2_fu_369_p2 );

    SC_METHOD(thread_p_s_fu_464_p3);
    sensitive << ( j_1_reg_608 );
    sensitive << ( icmp_fu_458_p2 );

    SC_METHOD(thread_sel_tmp2_fu_369_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_24_fu_359_p1 );

    SC_METHOD(thread_sel_tmp4_fu_375_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_24_fu_359_p1 );

    SC_METHOD(thread_sel_tmp_fu_363_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_24_fu_359_p1 );

    SC_METHOD(thread_tmp_10_fu_483_p2);
    sensitive << ( i_2_reg_194 );

    SC_METHOD(thread_tmp_11_fu_489_p1);
    sensitive << ( tmp_10_fu_483_p2 );

    SC_METHOD(thread_tmp_13_fu_498_p2);
    sensitive << ( mt_q0 );
    sensitive << ( tmp_26_fu_494_p1 );

    SC_METHOD(thread_tmp_15_fu_514_p2);
    sensitive << ( mt_q0 );
    sensitive << ( grp_fu_504_p2 );

    SC_METHOD(thread_tmp_16_cast_fu_524_p2);
    sensitive << ( tmp_27_reg_646 );
    sensitive << ( i_2_reg_194 );

    SC_METHOD(thread_tmp_17_cast_fu_529_p1);
    sensitive << ( tmp_16_cast_fu_524_p2 );

    SC_METHOD(thread_tmp_17_fu_277_p1);
    sensitive << ( mt_q0 );

    SC_METHOD(thread_tmp_18_fu_281_p2);
    sensitive << ( tmp_1_fu_267_p4 );
    sensitive << ( tmp_17_fu_277_p1 );

    SC_METHOD(thread_tmp_19_cast_fu_420_p2);
    sensitive << ( tmp_19_fu_411_p2 );
    sensitive << ( tmp_20_fu_416_p1 );

    SC_METHOD(thread_tmp_19_fu_411_p2);
    sensitive << ( tmp_25_reg_598 );
    sensitive << ( j_reg_157 );

    SC_METHOD(thread_tmp_1_fu_267_p4);
    sensitive << ( mt_q0 );

    SC_METHOD(thread_tmp_1_i_cast_fu_240_p1);
    sensitive << ( tmp_1_i_reg_133 );

    SC_METHOD(thread_tmp_20_cast_fu_426_p1);
    sensitive << ( tmp_19_cast_fu_420_p2 );

    SC_METHOD(thread_tmp_20_fu_416_p1);
    sensitive << ( newSel9_fu_403_p3 );

    SC_METHOD(thread_tmp_21_fu_443_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( i_4_fu_431_p2 );

    SC_METHOD(thread_tmp_22_fu_540_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( i_5_fu_534_p2 );

    SC_METHOD(thread_tmp_23_fu_329_p1);
    sensitive << ( grp_fu_230_p4 );

    SC_METHOD(thread_tmp_24_fu_359_p1);
    sensitive << ( j_reg_157 );

    SC_METHOD(thread_tmp_25_fu_355_p1);
    sensitive << ( tmp_9_fu_349_p2 );

    SC_METHOD(thread_tmp_26_fu_494_p1);
    sensitive << ( grp_fu_230_p4 );

    SC_METHOD(thread_tmp_27_fu_520_p1);
    sensitive << ( tmp_15_fu_514_p2 );

    SC_METHOD(thread_tmp_28_fu_449_p4);
    sensitive << ( j_1_reg_608 );

    SC_METHOD(thread_tmp_2_fu_509_p1);
    sensitive << ( i_2_reg_194 );

    SC_METHOD(thread_tmp_2_i_fu_306_p2);
    sensitive << ( tmp_1_i_reg_133 );

    SC_METHOD(thread_tmp_3_fu_477_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( k_1_reg_205 );

    SC_METHOD(thread_tmp_3_i_fu_256_p2);
    sensitive << ( tmp_1_i_reg_133 );

    SC_METHOD(thread_tmp_4_fu_318_p2);
    sensitive << ( i_reg_145 );

    SC_METHOD(thread_tmp_4_i_fu_262_p1);
    sensitive << ( tmp_3_i_fu_256_p2 );

    SC_METHOD(thread_tmp_5_fu_324_p1);
    sensitive << ( tmp_4_fu_318_p2 );

    SC_METHOD(thread_tmp_7_fu_333_p2);
    sensitive << ( mt_q0 );
    sensitive << ( tmp_23_fu_329_p1 );

    SC_METHOD(thread_tmp_8_i_fu_297_p1);
    sensitive << ( tmp_1_i_reg_133 );

    SC_METHOD(thread_tmp_9_fu_349_p2);
    sensitive << ( mt_q0 );
    sensitive << ( grp_fu_339_p2 );

    SC_METHOD(thread_tmp_9_i_cast_fu_292_p2);
    sensitive << ( tmp_1_i_cast_reg_552 );
    sensitive << ( grp_fu_287_p2 );

    SC_METHOD(thread_tmp_fu_312_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( k_reg_169 );

    SC_METHOD(thread_tmp_i_cast_fu_302_p1);
    sensitive << ( tmp_9_i_cast_reg_570 );

    SC_METHOD(thread_tmp_s_fu_344_p1);
    sensitive << ( i_reg_145 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond_i_fu_250_p2 );
    sensitive << ( tmp_fu_312_p2 );
    sensitive << ( tmp_21_fu_443_p2 );
    sensitive << ( tmp_3_fu_477_p2 );
    sensitive << ( tmp_22_fu_540_p2 );

    ap_CS_fsm = "000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "black_scholes_init_by_array_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, mti, "(port)mti");
    sc_trace(mVcdFile, mti_ap_vld, "(port)mti_ap_vld");
    sc_trace(mVcdFile, mt_address0, "(port)mt_address0");
    sc_trace(mVcdFile, mt_ce0, "(port)mt_ce0");
    sc_trace(mVcdFile, mt_we0, "(port)mt_we0");
    sc_trace(mVcdFile, mt_d0, "(port)mt_d0");
    sc_trace(mVcdFile, mt_q0, "(port)mt_q0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, tmp_1_i_cast_fu_240_p1, "tmp_1_i_cast_fu_240_p1");
    sc_trace(mVcdFile, tmp_1_i_cast_reg_552, "tmp_1_i_cast_reg_552");
    sc_trace(mVcdFile, exitcond_i_fu_250_p2, "exitcond_i_fu_250_p2");
    sc_trace(mVcdFile, tmp_18_fu_281_p2, "tmp_18_fu_281_p2");
    sc_trace(mVcdFile, tmp_18_reg_565, "tmp_18_reg_565");
    sc_trace(mVcdFile, tmp_9_i_cast_fu_292_p2, "tmp_9_i_cast_fu_292_p2");
    sc_trace(mVcdFile, tmp_9_i_cast_reg_570, "tmp_9_i_cast_reg_570");
    sc_trace(mVcdFile, tmp_2_i_fu_306_p2, "tmp_2_i_fu_306_p2");
    sc_trace(mVcdFile, tmp_fu_312_p2, "tmp_fu_312_p2");
    sc_trace(mVcdFile, tmp_7_fu_333_p2, "tmp_7_fu_333_p2");
    sc_trace(mVcdFile, tmp_7_reg_588, "tmp_7_reg_588");
    sc_trace(mVcdFile, mt_addr_reg_593, "mt_addr_reg_593");
    sc_trace(mVcdFile, tmp_25_fu_355_p1, "tmp_25_fu_355_p1");
    sc_trace(mVcdFile, tmp_25_reg_598, "tmp_25_reg_598");
    sc_trace(mVcdFile, i_4_fu_431_p2, "i_4_fu_431_p2");
    sc_trace(mVcdFile, j_1_fu_437_p2, "j_1_fu_437_p2");
    sc_trace(mVcdFile, j_1_reg_608, "j_1_reg_608");
    sc_trace(mVcdFile, tmp_21_fu_443_p2, "tmp_21_fu_443_p2");
    sc_trace(mVcdFile, tmp_21_reg_614, "tmp_21_reg_614");
    sc_trace(mVcdFile, p_s_fu_464_p3, "p_s_fu_464_p3");
    sc_trace(mVcdFile, p_s_reg_618, "p_s_reg_618");
    sc_trace(mVcdFile, k_2_fu_471_p2, "k_2_fu_471_p2");
    sc_trace(mVcdFile, k_2_reg_623, "k_2_reg_623");
    sc_trace(mVcdFile, tmp_3_fu_477_p2, "tmp_3_fu_477_p2");
    sc_trace(mVcdFile, tmp_13_fu_498_p2, "tmp_13_fu_498_p2");
    sc_trace(mVcdFile, tmp_13_reg_636, "tmp_13_reg_636");
    sc_trace(mVcdFile, mt_addr_3_reg_641, "mt_addr_3_reg_641");
    sc_trace(mVcdFile, tmp_27_fu_520_p1, "tmp_27_fu_520_p1");
    sc_trace(mVcdFile, tmp_27_reg_646, "tmp_27_reg_646");
    sc_trace(mVcdFile, i_5_fu_534_p2, "i_5_fu_534_p2");
    sc_trace(mVcdFile, tmp_22_fu_540_p2, "tmp_22_fu_540_p2");
    sc_trace(mVcdFile, tmp_22_reg_656, "tmp_22_reg_656");
    sc_trace(mVcdFile, k_3_fu_546_p2, "k_3_fu_546_p2");
    sc_trace(mVcdFile, tmp_1_i_reg_133, "tmp_1_i_reg_133");
    sc_trace(mVcdFile, i_reg_145, "i_reg_145");
    sc_trace(mVcdFile, j_reg_157, "j_reg_157");
    sc_trace(mVcdFile, k_reg_169, "k_reg_169");
    sc_trace(mVcdFile, i_1_reg_181, "i_1_reg_181");
    sc_trace(mVcdFile, i_3_phi_fu_221_p4, "i_3_phi_fu_221_p4");
    sc_trace(mVcdFile, i_2_reg_194, "i_2_reg_194");
    sc_trace(mVcdFile, k_1_reg_205, "k_1_reg_205");
    sc_trace(mVcdFile, i_3_reg_217, "i_3_reg_217");
    sc_trace(mVcdFile, tmp_4_i_fu_262_p1, "tmp_4_i_fu_262_p1");
    sc_trace(mVcdFile, tmp_8_i_fu_297_p1, "tmp_8_i_fu_297_p1");
    sc_trace(mVcdFile, tmp_5_fu_324_p1, "tmp_5_fu_324_p1");
    sc_trace(mVcdFile, tmp_s_fu_344_p1, "tmp_s_fu_344_p1");
    sc_trace(mVcdFile, tmp_11_fu_489_p1, "tmp_11_fu_489_p1");
    sc_trace(mVcdFile, tmp_2_fu_509_p1, "tmp_2_fu_509_p1");
    sc_trace(mVcdFile, tmp_i_cast_fu_302_p1, "tmp_i_cast_fu_302_p1");
    sc_trace(mVcdFile, tmp_20_cast_fu_426_p1, "tmp_20_cast_fu_426_p1");
    sc_trace(mVcdFile, tmp_17_cast_fu_529_p1, "tmp_17_cast_fu_529_p1");
    sc_trace(mVcdFile, tmp_3_i_fu_256_p2, "tmp_3_i_fu_256_p2");
    sc_trace(mVcdFile, tmp_1_fu_267_p4, "tmp_1_fu_267_p4");
    sc_trace(mVcdFile, tmp_17_fu_277_p1, "tmp_17_fu_277_p1");
    sc_trace(mVcdFile, grp_fu_287_p0, "grp_fu_287_p0");
    sc_trace(mVcdFile, grp_fu_287_p1, "grp_fu_287_p1");
    sc_trace(mVcdFile, grp_fu_287_p2, "grp_fu_287_p2");
    sc_trace(mVcdFile, tmp_4_fu_318_p2, "tmp_4_fu_318_p2");
    sc_trace(mVcdFile, grp_fu_230_p4, "grp_fu_230_p4");
    sc_trace(mVcdFile, tmp_23_fu_329_p1, "tmp_23_fu_329_p1");
    sc_trace(mVcdFile, grp_fu_339_p0, "grp_fu_339_p0");
    sc_trace(mVcdFile, grp_fu_339_p1, "grp_fu_339_p1");
    sc_trace(mVcdFile, grp_fu_339_p2, "grp_fu_339_p2");
    sc_trace(mVcdFile, tmp_9_fu_349_p2, "tmp_9_fu_349_p2");
    sc_trace(mVcdFile, tmp_24_fu_359_p1, "tmp_24_fu_359_p1");
    sc_trace(mVcdFile, sel_tmp4_fu_375_p2, "sel_tmp4_fu_375_p2");
    sc_trace(mVcdFile, sel_tmp2_fu_369_p2, "sel_tmp2_fu_369_p2");
    sc_trace(mVcdFile, sel_tmp_fu_363_p2, "sel_tmp_fu_363_p2");
    sc_trace(mVcdFile, or_cond_fu_389_p2, "or_cond_fu_389_p2");
    sc_trace(mVcdFile, newSel_cast_cast_fu_381_p3, "newSel_cast_cast_fu_381_p3");
    sc_trace(mVcdFile, newSel7_fu_395_p3, "newSel7_fu_395_p3");
    sc_trace(mVcdFile, newSel9_fu_403_p3, "newSel9_fu_403_p3");
    sc_trace(mVcdFile, tmp_19_fu_411_p2, "tmp_19_fu_411_p2");
    sc_trace(mVcdFile, tmp_20_fu_416_p1, "tmp_20_fu_416_p1");
    sc_trace(mVcdFile, tmp_19_cast_fu_420_p2, "tmp_19_cast_fu_420_p2");
    sc_trace(mVcdFile, tmp_28_fu_449_p4, "tmp_28_fu_449_p4");
    sc_trace(mVcdFile, icmp_fu_458_p2, "icmp_fu_458_p2");
    sc_trace(mVcdFile, tmp_10_fu_483_p2, "tmp_10_fu_483_p2");
    sc_trace(mVcdFile, tmp_26_fu_494_p1, "tmp_26_fu_494_p1");
    sc_trace(mVcdFile, grp_fu_504_p0, "grp_fu_504_p0");
    sc_trace(mVcdFile, grp_fu_504_p1, "grp_fu_504_p1");
    sc_trace(mVcdFile, grp_fu_504_p2, "grp_fu_504_p2");
    sc_trace(mVcdFile, tmp_15_fu_514_p2, "tmp_15_fu_514_p2");
    sc_trace(mVcdFile, tmp_16_cast_fu_524_p2, "tmp_16_cast_fu_524_p2");
    sc_trace(mVcdFile, grp_fu_287_ce, "grp_fu_287_ce");
    sc_trace(mVcdFile, grp_fu_339_ce, "grp_fu_339_ce");
    sc_trace(mVcdFile, grp_fu_504_ce, "grp_fu_504_ce");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

black_scholes_init_by_array::~black_scholes_init_by_array() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete black_scholes_mul_32s_31ns_32_6_U1;
    delete black_scholes_mul_64s_21ns_64_6_U2;
    delete black_scholes_mul_64s_31ns_64_6_U3;
}

void black_scholes_init_by_array::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_st19_fsm_18, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_21_fu_443_p2.read()))) {
        i_1_reg_181 = i_4_fu_431_p2.read();
    } else if ((esl_seteq<1,6,6>(ap_ST_st21_fsm_20, ap_CS_fsm.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_21_reg_614.read()))) {
        i_1_reg_181 = ap_const_lv32_1;
    }
    if ((esl_seteq<1,6,6>(ap_ST_st11_fsm_10, ap_CS_fsm.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_fu_312_p2.read()))) {
        i_2_reg_194 = i_reg_145.read();
    } else if (esl_seteq<1,6,6>(ap_ST_st33_fsm_32, ap_CS_fsm.read())) {
        i_2_reg_194 = i_3_phi_fu_221_p4.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_st31_fsm_30, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_22_fu_540_p2.read()))) {
        i_3_reg_217 = i_5_fu_534_p2.read();
    } else if ((esl_seteq<1,6,6>(ap_ST_st33_fsm_32, ap_CS_fsm.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_22_reg_656.read()))) {
        i_3_reg_217 = ap_const_lv32_1;
    }
    if ((esl_seteq<1,6,6>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && 
         !esl_seteq<1,1,1>(exitcond_i_fu_250_p2.read(), ap_const_lv1_0))) {
        i_reg_145 = ap_const_lv32_1;
    } else if (esl_seteq<1,6,6>(ap_ST_st22_fsm_21, ap_CS_fsm.read())) {
        i_reg_145 = i_1_reg_181.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && 
         !esl_seteq<1,1,1>(exitcond_i_fu_250_p2.read(), ap_const_lv1_0))) {
        j_reg_157 = ap_const_lv32_0;
    } else if (esl_seteq<1,6,6>(ap_ST_st22_fsm_21, ap_CS_fsm.read())) {
        j_reg_157 = p_s_reg_618.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_st11_fsm_10, ap_CS_fsm.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_fu_312_p2.read()))) {
        k_1_reg_205 = ap_const_lv10_26F;
    } else if (esl_seteq<1,6,6>(ap_ST_st33_fsm_32, ap_CS_fsm.read())) {
        k_1_reg_205 = k_3_fu_546_p2.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && 
         !esl_seteq<1,1,1>(exitcond_i_fu_250_p2.read(), ap_const_lv1_0))) {
        k_reg_169 = ap_const_lv10_270;
    } else if (esl_seteq<1,6,6>(ap_ST_st22_fsm_21, ap_CS_fsm.read())) {
        k_reg_169 = k_2_reg_623.read();
    }
    if (esl_seteq<1,6,6>(ap_ST_st10_fsm_9, ap_CS_fsm.read())) {
        tmp_1_i_reg_133 = tmp_2_i_fu_306_p2.read();
    } else if ((esl_seteq<1,6,6>(ap_ST_st1_fsm_0, ap_CS_fsm.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        tmp_1_i_reg_133 = ap_const_lv10_1;
    }
    if (esl_seteq<1,6,6>(ap_ST_st19_fsm_18, ap_CS_fsm.read())) {
        j_1_reg_608 = j_1_fu_437_p2.read();
        tmp_21_reg_614 = tmp_21_fu_443_p2.read();
    }
    if (esl_seteq<1,6,6>(ap_ST_st21_fsm_20, ap_CS_fsm.read())) {
        k_2_reg_623 = k_2_fu_471_p2.read();
        p_s_reg_618 = p_s_fu_464_p3.read();
    }
    if (esl_seteq<1,6,6>(ap_ST_st29_fsm_28, ap_CS_fsm.read())) {
        mt_addr_3_reg_641 =  (sc_lv<10>) (tmp_2_fu_509_p1.read());
    }
    if (esl_seteq<1,6,6>(ap_ST_st17_fsm_16, ap_CS_fsm.read())) {
        mt_addr_reg_593 =  (sc_lv<10>) (tmp_s_fu_344_p1.read());
    }
    if (esl_seteq<1,6,6>(ap_ST_st24_fsm_23, ap_CS_fsm.read())) {
        tmp_13_reg_636 = tmp_13_fu_498_p2.read();
    }
    if (esl_seteq<1,6,6>(ap_ST_st3_fsm_2, ap_CS_fsm.read())) {
        tmp_18_reg_565 = tmp_18_fu_281_p2.read();
    }
    if (esl_seteq<1,6,6>(ap_ST_st2_fsm_1, ap_CS_fsm.read())) {
        tmp_1_i_cast_reg_552 = tmp_1_i_cast_fu_240_p1.read();
    }
    if (esl_seteq<1,6,6>(ap_ST_st31_fsm_30, ap_CS_fsm.read())) {
        tmp_22_reg_656 = tmp_22_fu_540_p2.read();
    }
    if (esl_seteq<1,6,6>(ap_ST_st18_fsm_17, ap_CS_fsm.read())) {
        tmp_25_reg_598 = tmp_25_fu_355_p1.read();
    }
    if (esl_seteq<1,6,6>(ap_ST_st30_fsm_29, ap_CS_fsm.read())) {
        tmp_27_reg_646 = tmp_27_fu_520_p1.read();
    }
    if (esl_seteq<1,6,6>(ap_ST_st12_fsm_11, ap_CS_fsm.read())) {
        tmp_7_reg_588 = tmp_7_fu_333_p2.read();
    }
    if (esl_seteq<1,6,6>(ap_ST_st9_fsm_8, ap_CS_fsm.read())) {
        tmp_9_i_cast_reg_570 = tmp_9_i_cast_fu_292_p2.read();
    }
}

void black_scholes_init_by_array::thread_ap_done() {
    if (((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
          esl_seteq<1,6,6>(ap_ST_st1_fsm_0, ap_CS_fsm.read())) || 
         (esl_seteq<1,6,6>(ap_ST_st23_fsm_22, ap_CS_fsm.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_fu_477_p2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void black_scholes_init_by_array::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,6,6>(ap_ST_st1_fsm_0, ap_CS_fsm.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void black_scholes_init_by_array::thread_ap_ready() {
    if ((esl_seteq<1,6,6>(ap_ST_st23_fsm_22, ap_CS_fsm.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_fu_477_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void black_scholes_init_by_array::thread_exitcond_i_fu_250_p2() {
    exitcond_i_fu_250_p2 = (!tmp_1_i_reg_133.read().is_01() || !ap_const_lv10_270.is_01())? sc_lv<1>(): sc_lv<1>(tmp_1_i_reg_133.read() == ap_const_lv10_270);
}

void black_scholes_init_by_array::thread_grp_fu_230_p4() {
    grp_fu_230_p4 = mt_q0.read().range(63, 30);
}

void black_scholes_init_by_array::thread_grp_fu_287_ce() {
    grp_fu_287_ce = ap_const_logic_1;
}

void black_scholes_init_by_array::thread_grp_fu_287_p0() {
    grp_fu_287_p0 = tmp_18_reg_565.read();
}

void black_scholes_init_by_array::thread_grp_fu_287_p1() {
    grp_fu_287_p1 =  (sc_lv<31>) (ap_const_lv32_6C078965);
}

void black_scholes_init_by_array::thread_grp_fu_339_ce() {
    grp_fu_339_ce = ap_const_logic_1;
}

void black_scholes_init_by_array::thread_grp_fu_339_p0() {
    grp_fu_339_p0 = tmp_7_reg_588.read();
}

void black_scholes_init_by_array::thread_grp_fu_339_p1() {
    grp_fu_339_p1 =  (sc_lv<21>) (ap_const_lv64_19660D);
}

void black_scholes_init_by_array::thread_grp_fu_504_ce() {
    grp_fu_504_ce = ap_const_logic_1;
}

void black_scholes_init_by_array::thread_grp_fu_504_p0() {
    grp_fu_504_p0 = tmp_13_reg_636.read();
}

void black_scholes_init_by_array::thread_grp_fu_504_p1() {
    grp_fu_504_p1 =  (sc_lv<31>) (ap_const_lv64_5D588B65);
}

void black_scholes_init_by_array::thread_i_3_phi_fu_221_p4() {
    if ((esl_seteq<1,6,6>(ap_ST_st33_fsm_32, ap_CS_fsm.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_22_reg_656.read()))) {
        i_3_phi_fu_221_p4 = ap_const_lv32_1;
    } else {
        i_3_phi_fu_221_p4 = i_3_reg_217.read();
    }
}

void black_scholes_init_by_array::thread_i_4_fu_431_p2() {
    i_4_fu_431_p2 = (!i_reg_145.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_bigint<32>(i_reg_145.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void black_scholes_init_by_array::thread_i_5_fu_534_p2() {
    i_5_fu_534_p2 = (!i_2_reg_194.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_bigint<32>(i_2_reg_194.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void black_scholes_init_by_array::thread_icmp_fu_458_p2() {
    icmp_fu_458_p2 = (!tmp_28_fu_449_p4.read().is_01() || !ap_const_lv30_1.is_01())? sc_lv<1>(): (sc_bigint<30>(tmp_28_fu_449_p4.read()) < sc_bigint<30>(ap_const_lv30_1));
}

void black_scholes_init_by_array::thread_j_1_fu_437_p2() {
    j_1_fu_437_p2 = (!j_reg_157.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_bigint<32>(j_reg_157.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void black_scholes_init_by_array::thread_k_2_fu_471_p2() {
    k_2_fu_471_p2 = (!k_reg_169.read().is_01() || !ap_const_lv10_3FF.is_01())? sc_lv<10>(): (sc_bigint<10>(k_reg_169.read()) + sc_biguint<10>(ap_const_lv10_3FF));
}

void black_scholes_init_by_array::thread_k_3_fu_546_p2() {
    k_3_fu_546_p2 = (!k_1_reg_205.read().is_01() || !ap_const_lv10_3FF.is_01())? sc_lv<10>(): (sc_bigint<10>(k_1_reg_205.read()) + sc_biguint<10>(ap_const_lv10_3FF));
}

void black_scholes_init_by_array::thread_mt_address0() {
    if (esl_seteq<1,6,6>(ap_ST_st31_fsm_30, ap_CS_fsm.read())) {
        mt_address0 = mt_addr_3_reg_641.read();
    } else if (esl_seteq<1,6,6>(ap_ST_st19_fsm_18, ap_CS_fsm.read())) {
        mt_address0 = mt_addr_reg_593.read();
    } else if (esl_seteq<1,6,6>(ap_ST_st10_fsm_9, ap_CS_fsm.read())) {
        mt_address0 =  (sc_lv<10>) (tmp_8_i_fu_297_p1.read());
    } else if ((esl_seteq<1,6,6>(ap_ST_st1_fsm_0, ap_CS_fsm.read()) || 
                esl_seteq<1,6,6>(ap_ST_st21_fsm_20, ap_CS_fsm.read()) || 
                esl_seteq<1,6,6>(ap_ST_st33_fsm_32, ap_CS_fsm.read()) || 
                (esl_seteq<1,6,6>(ap_ST_st23_fsm_22, ap_CS_fsm.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_fu_477_p2.read())))) {
        mt_address0 = ap_const_lv10_0;
    } else if (esl_seteq<1,6,6>(ap_ST_st29_fsm_28, ap_CS_fsm.read())) {
        mt_address0 =  (sc_lv<10>) (tmp_2_fu_509_p1.read());
    } else if ((esl_seteq<1,6,6>(ap_ST_st23_fsm_22, ap_CS_fsm.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_fu_477_p2.read()))) {
        mt_address0 =  (sc_lv<10>) (tmp_11_fu_489_p1.read());
    } else if ((esl_seteq<1,6,6>(ap_ST_st20_fsm_19, ap_CS_fsm.read()) || 
                esl_seteq<1,6,6>(ap_ST_st32_fsm_31, ap_CS_fsm.read()))) {
        mt_address0 = ap_const_lv10_26F;
    } else if (esl_seteq<1,6,6>(ap_ST_st17_fsm_16, ap_CS_fsm.read())) {
        mt_address0 =  (sc_lv<10>) (tmp_s_fu_344_p1.read());
    } else if (esl_seteq<1,6,6>(ap_ST_st11_fsm_10, ap_CS_fsm.read())) {
        mt_address0 =  (sc_lv<10>) (tmp_5_fu_324_p1.read());
    } else if (esl_seteq<1,6,6>(ap_ST_st2_fsm_1, ap_CS_fsm.read())) {
        mt_address0 =  (sc_lv<10>) (tmp_4_i_fu_262_p1.read());
    } else {
        mt_address0 = "XXXXXXXXXX";
    }
}

void black_scholes_init_by_array::thread_mt_ce0() {
    if ((esl_seteq<1,6,6>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st10_fsm_9, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st11_fsm_10, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st17_fsm_16, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st19_fsm_18, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st21_fsm_20, ap_CS_fsm.read()) || 
         (esl_seteq<1,6,6>(ap_ST_st23_fsm_22, ap_CS_fsm.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_fu_477_p2.read())) || 
         esl_seteq<1,6,6>(ap_ST_st29_fsm_28, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st31_fsm_30, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st33_fsm_32, ap_CS_fsm.read()) || 
         (esl_seteq<1,6,6>(ap_ST_st1_fsm_0, ap_CS_fsm.read()) && 
          !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) || 
         esl_seteq<1,6,6>(ap_ST_st20_fsm_19, ap_CS_fsm.read()) || 
         (esl_seteq<1,6,6>(ap_ST_st23_fsm_22, ap_CS_fsm.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_fu_477_p2.read())) || 
         esl_seteq<1,6,6>(ap_ST_st32_fsm_31, ap_CS_fsm.read()))) {
        mt_ce0 = ap_const_logic_1;
    } else {
        mt_ce0 = ap_const_logic_0;
    }
}

void black_scholes_init_by_array::thread_mt_d0() {
    if (esl_seteq<1,6,6>(ap_ST_st31_fsm_30, ap_CS_fsm.read())) {
        mt_d0 = tmp_17_cast_fu_529_p1.read();
    } else if ((esl_seteq<1,6,6>(ap_ST_st23_fsm_22, ap_CS_fsm.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_fu_477_p2.read()))) {
        mt_d0 = ap_const_lv64_80000000;
    } else if ((esl_seteq<1,6,6>(ap_ST_st21_fsm_20, ap_CS_fsm.read()) || 
                esl_seteq<1,6,6>(ap_ST_st33_fsm_32, ap_CS_fsm.read()))) {
        mt_d0 = mt_q0.read();
    } else if (esl_seteq<1,6,6>(ap_ST_st19_fsm_18, ap_CS_fsm.read())) {
        mt_d0 = tmp_20_cast_fu_426_p1.read();
    } else if (esl_seteq<1,6,6>(ap_ST_st10_fsm_9, ap_CS_fsm.read())) {
        mt_d0 = tmp_i_cast_fu_302_p1.read();
    } else if (esl_seteq<1,6,6>(ap_ST_st1_fsm_0, ap_CS_fsm.read())) {
        mt_d0 = ap_const_lv64_12BD6AA;
    } else {
        mt_d0 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void black_scholes_init_by_array::thread_mt_we0() {
    if ((esl_seteq<1,6,6>(ap_ST_st10_fsm_9, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st19_fsm_18, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st31_fsm_30, ap_CS_fsm.read()) || 
         (esl_seteq<1,6,6>(ap_ST_st1_fsm_0, ap_CS_fsm.read()) && 
          !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) || 
         (esl_seteq<1,6,6>(ap_ST_st21_fsm_20, ap_CS_fsm.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_21_reg_614.read())) || 
         (esl_seteq<1,6,6>(ap_ST_st33_fsm_32, ap_CS_fsm.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_22_reg_656.read())) || 
         (esl_seteq<1,6,6>(ap_ST_st23_fsm_22, ap_CS_fsm.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_fu_477_p2.read())))) {
        mt_we0 = ap_const_logic_1;
    } else {
        mt_we0 = ap_const_logic_0;
    }
}

void black_scholes_init_by_array::thread_mti() {
    mti = esl_zext<32,10>(tmp_1_i_reg_133.read());
}

void black_scholes_init_by_array::thread_mti_ap_vld() {
    if (esl_seteq<1,6,6>(ap_ST_st2_fsm_1, ap_CS_fsm.read())) {
        mti_ap_vld = ap_const_logic_1;
    } else {
        mti_ap_vld = ap_const_logic_0;
    }
}

void black_scholes_init_by_array::thread_newSel7_fu_395_p3() {
    newSel7_fu_395_p3 = (!sel_tmp_fu_363_p2.read()[0].is_01())? sc_lv<11>(): ((sel_tmp_fu_363_p2.read()[0].to_bool())? ap_const_lv11_234: ap_const_lv11_456);
}

void black_scholes_init_by_array::thread_newSel9_fu_403_p3() {
    newSel9_fu_403_p3 = (!or_cond_fu_389_p2.read()[0].is_01())? sc_lv<11>(): ((or_cond_fu_389_p2.read()[0].to_bool())? newSel_cast_cast_fu_381_p3.read(): newSel7_fu_395_p3.read());
}

void black_scholes_init_by_array::thread_newSel_cast_cast_fu_381_p3() {
    newSel_cast_cast_fu_381_p3 = (!sel_tmp4_fu_375_p2.read()[0].is_01())? sc_lv<11>(): ((sel_tmp4_fu_375_p2.read()[0].to_bool())? ap_const_lv11_123: ap_const_lv11_345);
}

void black_scholes_init_by_array::thread_or_cond_fu_389_p2() {
    or_cond_fu_389_p2 = (sel_tmp4_fu_375_p2.read() | sel_tmp2_fu_369_p2.read());
}

void black_scholes_init_by_array::thread_p_s_fu_464_p3() {
    p_s_fu_464_p3 = (!icmp_fu_458_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_fu_458_p2.read()[0].to_bool())? j_1_reg_608.read(): ap_const_lv32_0);
}

void black_scholes_init_by_array::thread_sel_tmp2_fu_369_p2() {
    sel_tmp2_fu_369_p2 = (!tmp_24_fu_359_p1.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(tmp_24_fu_359_p1.read() == ap_const_lv2_2);
}

void black_scholes_init_by_array::thread_sel_tmp4_fu_375_p2() {
    sel_tmp4_fu_375_p2 = (!tmp_24_fu_359_p1.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_24_fu_359_p1.read() == ap_const_lv2_0);
}

void black_scholes_init_by_array::thread_sel_tmp_fu_363_p2() {
    sel_tmp_fu_363_p2 = (!tmp_24_fu_359_p1.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(tmp_24_fu_359_p1.read() == ap_const_lv2_1);
}

void black_scholes_init_by_array::thread_tmp_10_fu_483_p2() {
    tmp_10_fu_483_p2 = (!i_2_reg_194.read().is_01() || !ap_const_lv32_FFFFFFFF.is_01())? sc_lv<32>(): (sc_bigint<32>(i_2_reg_194.read()) + sc_biguint<32>(ap_const_lv32_FFFFFFFF));
}

void black_scholes_init_by_array::thread_tmp_11_fu_489_p1() {
    tmp_11_fu_489_p1 = esl_sext<64,32>(tmp_10_fu_483_p2.read());
}

void black_scholes_init_by_array::thread_tmp_13_fu_498_p2() {
    tmp_13_fu_498_p2 = (tmp_26_fu_494_p1.read() ^ mt_q0.read());
}

void black_scholes_init_by_array::thread_tmp_15_fu_514_p2() {
    tmp_15_fu_514_p2 = (grp_fu_504_p2.read() ^ mt_q0.read());
}

void black_scholes_init_by_array::thread_tmp_16_cast_fu_524_p2() {
    tmp_16_cast_fu_524_p2 = (!tmp_27_reg_646.read().is_01() || !i_2_reg_194.read().is_01())? sc_lv<32>(): (sc_bigint<32>(tmp_27_reg_646.read()) - sc_biguint<32>(i_2_reg_194.read()));
}

void black_scholes_init_by_array::thread_tmp_17_cast_fu_529_p1() {
    tmp_17_cast_fu_529_p1 = esl_zext<64,32>(tmp_16_cast_fu_524_p2.read());
}

void black_scholes_init_by_array::thread_tmp_17_fu_277_p1() {
    tmp_17_fu_277_p1 = mt_q0.read().range(32-1, 0);
}

void black_scholes_init_by_array::thread_tmp_18_fu_281_p2() {
    tmp_18_fu_281_p2 = (tmp_1_fu_267_p4.read() ^ tmp_17_fu_277_p1.read());
}

void black_scholes_init_by_array::thread_tmp_19_cast_fu_420_p2() {
    tmp_19_cast_fu_420_p2 = (!tmp_19_fu_411_p2.read().is_01() || !tmp_20_fu_416_p1.read().is_01())? sc_lv<32>(): (sc_bigint<32>(tmp_19_fu_411_p2.read()) + sc_biguint<32>(tmp_20_fu_416_p1.read()));
}

void black_scholes_init_by_array::thread_tmp_19_fu_411_p2() {
    tmp_19_fu_411_p2 = (!tmp_25_reg_598.read().is_01() || !j_reg_157.read().is_01())? sc_lv<32>(): (sc_bigint<32>(tmp_25_reg_598.read()) + sc_biguint<32>(j_reg_157.read()));
}

void black_scholes_init_by_array::thread_tmp_1_fu_267_p4() {
    tmp_1_fu_267_p4 = mt_q0.read().range(61, 30);
}

void black_scholes_init_by_array::thread_tmp_1_i_cast_fu_240_p1() {
    tmp_1_i_cast_fu_240_p1 = esl_zext<32,10>(tmp_1_i_reg_133.read());
}

void black_scholes_init_by_array::thread_tmp_20_cast_fu_426_p1() {
    tmp_20_cast_fu_426_p1 = esl_zext<64,32>(tmp_19_cast_fu_420_p2.read());
}

void black_scholes_init_by_array::thread_tmp_20_fu_416_p1() {
    tmp_20_fu_416_p1 = esl_zext<32,11>(newSel9_fu_403_p3.read());
}

void black_scholes_init_by_array::thread_tmp_21_fu_443_p2() {
    tmp_21_fu_443_p2 = (!i_4_fu_431_p2.read().is_01() || !ap_const_lv32_26F.is_01())? sc_lv<1>(): (sc_bigint<32>(i_4_fu_431_p2.read()) > sc_bigint<32>(ap_const_lv32_26F));
}

void black_scholes_init_by_array::thread_tmp_22_fu_540_p2() {
    tmp_22_fu_540_p2 = (!i_5_fu_534_p2.read().is_01() || !ap_const_lv32_26F.is_01())? sc_lv<1>(): (sc_bigint<32>(i_5_fu_534_p2.read()) > sc_bigint<32>(ap_const_lv32_26F));
}

void black_scholes_init_by_array::thread_tmp_23_fu_329_p1() {
    tmp_23_fu_329_p1 = esl_zext<64,34>(grp_fu_230_p4.read());
}

void black_scholes_init_by_array::thread_tmp_24_fu_359_p1() {
    tmp_24_fu_359_p1 = j_reg_157.read().range(2-1, 0);
}

void black_scholes_init_by_array::thread_tmp_25_fu_355_p1() {
    tmp_25_fu_355_p1 = tmp_9_fu_349_p2.read().range(32-1, 0);
}

void black_scholes_init_by_array::thread_tmp_26_fu_494_p1() {
    tmp_26_fu_494_p1 = esl_zext<64,34>(grp_fu_230_p4.read());
}

void black_scholes_init_by_array::thread_tmp_27_fu_520_p1() {
    tmp_27_fu_520_p1 = tmp_15_fu_514_p2.read().range(32-1, 0);
}

void black_scholes_init_by_array::thread_tmp_28_fu_449_p4() {
    tmp_28_fu_449_p4 = j_1_reg_608.read().range(31, 2);
}

void black_scholes_init_by_array::thread_tmp_2_fu_509_p1() {
    tmp_2_fu_509_p1 = esl_sext<64,32>(i_2_reg_194.read());
}

void black_scholes_init_by_array::thread_tmp_2_i_fu_306_p2() {
    tmp_2_i_fu_306_p2 = (!tmp_1_i_reg_133.read().is_01() || !ap_const_lv10_1.is_01())? sc_lv<10>(): (sc_bigint<10>(tmp_1_i_reg_133.read()) + sc_biguint<10>(ap_const_lv10_1));
}

void black_scholes_init_by_array::thread_tmp_3_fu_477_p2() {
    tmp_3_fu_477_p2 = (!k_1_reg_205.read().is_01() || !ap_const_lv10_0.is_01())? sc_lv<1>(): sc_lv<1>(k_1_reg_205.read() == ap_const_lv10_0);
}

void black_scholes_init_by_array::thread_tmp_3_i_fu_256_p2() {
    tmp_3_i_fu_256_p2 = (!tmp_1_i_reg_133.read().is_01() || !ap_const_lv10_3FF.is_01())? sc_lv<10>(): (sc_bigint<10>(tmp_1_i_reg_133.read()) + sc_biguint<10>(ap_const_lv10_3FF));
}

void black_scholes_init_by_array::thread_tmp_4_fu_318_p2() {
    tmp_4_fu_318_p2 = (!i_reg_145.read().is_01() || !ap_const_lv32_FFFFFFFF.is_01())? sc_lv<32>(): (sc_bigint<32>(i_reg_145.read()) + sc_biguint<32>(ap_const_lv32_FFFFFFFF));
}

void black_scholes_init_by_array::thread_tmp_4_i_fu_262_p1() {
    tmp_4_i_fu_262_p1 = esl_zext<64,10>(tmp_3_i_fu_256_p2.read());
}

void black_scholes_init_by_array::thread_tmp_5_fu_324_p1() {
    tmp_5_fu_324_p1 = esl_sext<64,32>(tmp_4_fu_318_p2.read());
}

void black_scholes_init_by_array::thread_tmp_7_fu_333_p2() {
    tmp_7_fu_333_p2 = (tmp_23_fu_329_p1.read() ^ mt_q0.read());
}

void black_scholes_init_by_array::thread_tmp_8_i_fu_297_p1() {
    tmp_8_i_fu_297_p1 = esl_zext<64,10>(tmp_1_i_reg_133.read());
}

void black_scholes_init_by_array::thread_tmp_9_fu_349_p2() {
    tmp_9_fu_349_p2 = (grp_fu_339_p2.read() ^ mt_q0.read());
}

void black_scholes_init_by_array::thread_tmp_9_i_cast_fu_292_p2() {
    tmp_9_i_cast_fu_292_p2 = (!grp_fu_287_p2.read().is_01() || !tmp_1_i_cast_reg_552.read().is_01())? sc_lv<32>(): (sc_bigint<32>(grp_fu_287_p2.read()) + sc_biguint<32>(tmp_1_i_cast_reg_552.read()));
}

void black_scholes_init_by_array::thread_tmp_fu_312_p2() {
    tmp_fu_312_p2 = (!k_reg_169.read().is_01() || !ap_const_lv10_0.is_01())? sc_lv<1>(): sc_lv<1>(k_reg_169.read() == ap_const_lv10_0);
}

void black_scholes_init_by_array::thread_tmp_i_cast_fu_302_p1() {
    tmp_i_cast_fu_302_p1 = esl_zext<64,32>(tmp_9_i_cast_reg_570.read());
}

void black_scholes_init_by_array::thread_tmp_s_fu_344_p1() {
    tmp_s_fu_344_p1 = esl_sext<64,32>(i_reg_145.read());
}

void black_scholes_init_by_array::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 0 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 1 : 
            if (!esl_seteq<1,1,1>(exitcond_i_fu_250_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st11_fsm_10;
            } else {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_st4_fsm_3;
            break;
        case 3 : 
            ap_NS_fsm = ap_ST_st5_fsm_4;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_st6_fsm_5;
            break;
        case 5 : 
            ap_NS_fsm = ap_ST_st7_fsm_6;
            break;
        case 6 : 
            ap_NS_fsm = ap_ST_st8_fsm_7;
            break;
        case 7 : 
            ap_NS_fsm = ap_ST_st9_fsm_8;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_st10_fsm_9;
            break;
        case 9 : 
            ap_NS_fsm = ap_ST_st2_fsm_1;
            break;
        case 10 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, tmp_fu_312_p2.read())) {
                ap_NS_fsm = ap_ST_st23_fsm_22;
            } else {
                ap_NS_fsm = ap_ST_st12_fsm_11;
            }
            break;
        case 11 : 
            ap_NS_fsm = ap_ST_st13_fsm_12;
            break;
        case 12 : 
            ap_NS_fsm = ap_ST_st14_fsm_13;
            break;
        case 13 : 
            ap_NS_fsm = ap_ST_st15_fsm_14;
            break;
        case 14 : 
            ap_NS_fsm = ap_ST_st16_fsm_15;
            break;
        case 15 : 
            ap_NS_fsm = ap_ST_st17_fsm_16;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_st18_fsm_17;
            break;
        case 17 : 
            ap_NS_fsm = ap_ST_st19_fsm_18;
            break;
        case 18 : 
            if (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_21_fu_443_p2.read())) {
                ap_NS_fsm = ap_ST_st21_fsm_20;
            } else {
                ap_NS_fsm = ap_ST_st20_fsm_19;
            }
            break;
        case 19 : 
            ap_NS_fsm = ap_ST_st21_fsm_20;
            break;
        case 20 : 
            ap_NS_fsm = ap_ST_st22_fsm_21;
            break;
        case 21 : 
            ap_NS_fsm = ap_ST_st11_fsm_10;
            break;
        case 22 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_fu_477_p2.read())) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st24_fsm_23;
            }
            break;
        case 23 : 
            ap_NS_fsm = ap_ST_st25_fsm_24;
            break;
        case 24 : 
            ap_NS_fsm = ap_ST_st26_fsm_25;
            break;
        case 25 : 
            ap_NS_fsm = ap_ST_st27_fsm_26;
            break;
        case 26 : 
            ap_NS_fsm = ap_ST_st28_fsm_27;
            break;
        case 27 : 
            ap_NS_fsm = ap_ST_st29_fsm_28;
            break;
        case 28 : 
            ap_NS_fsm = ap_ST_st30_fsm_29;
            break;
        case 29 : 
            ap_NS_fsm = ap_ST_st31_fsm_30;
            break;
        case 30 : 
            if (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_22_fu_540_p2.read())) {
                ap_NS_fsm = ap_ST_st33_fsm_32;
            } else {
                ap_NS_fsm = ap_ST_st32_fsm_31;
            }
            break;
        case 31 : 
            ap_NS_fsm = ap_ST_st33_fsm_32;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_st23_fsm_22;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<6>) ("XXXXXX");
            break;
    }
}

}

