// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.2
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "BlackScholesWrapper.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic BlackScholesWrapper::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic BlackScholesWrapper::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> BlackScholesWrapper::ap_ST_st1_fsm_0 = "000";
const sc_lv<3> BlackScholesWrapper::ap_ST_pp0_stg0_fsm_1 = "1";
const sc_lv<3> BlackScholesWrapper::ap_ST_pp0_stg1_fsm_2 = "10";
const sc_lv<3> BlackScholesWrapper::ap_ST_pp0_stg2_fsm_3 = "11";
const sc_lv<3> BlackScholesWrapper::ap_ST_pp0_stg3_fsm_4 = "100";
const sc_lv<3> BlackScholesWrapper::ap_ST_st215_fsm_5 = "101";
const sc_lv<1> BlackScholesWrapper::ap_const_lv1_0 = "0";
const sc_lv<17> BlackScholesWrapper::ap_const_lv17_0 = "00000000000000000";
const sc_lv<17> BlackScholesWrapper::ap_const_lv17_186A0 = "11000011010100000";
const sc_lv<17> BlackScholesWrapper::ap_const_lv17_1 = "1";

BlackScholesWrapper::BlackScholesWrapper(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_BlackScholes_fu_129 = new BlackScholes("grp_BlackScholes_fu_129");
    grp_BlackScholes_fu_129->ap_clk(ap_clk);
    grp_BlackScholes_fu_129->ap_rst(ap_rst);
    grp_BlackScholes_fu_129->ap_start(grp_BlackScholes_fu_129_ap_start);
    grp_BlackScholes_fu_129->ap_done(grp_BlackScholes_fu_129_ap_done);
    grp_BlackScholes_fu_129->ap_idle(grp_BlackScholes_fu_129_ap_idle);
    grp_BlackScholes_fu_129->ap_ready(grp_BlackScholes_fu_129_ap_ready);
    grp_BlackScholes_fu_129->ap_ce(grp_BlackScholes_fu_129_ap_ce);
    grp_BlackScholes_fu_129->CallPutFlag(grp_BlackScholes_fu_129_CallPutFlag);
    grp_BlackScholes_fu_129->S(grp_BlackScholes_fu_129_S);
    grp_BlackScholes_fu_129->X(grp_BlackScholes_fu_129_X);
    grp_BlackScholes_fu_129->T(grp_BlackScholes_fu_129_T);
    grp_BlackScholes_fu_129->r(grp_BlackScholes_fu_129_r);
    grp_BlackScholes_fu_129->b(grp_BlackScholes_fu_129_b);
    grp_BlackScholes_fu_129->ap_return(grp_BlackScholes_fu_129_ap_return);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_a_address0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it53 );
    sensitive << ( tmp_s_fu_163_p1 );

    SC_METHOD(thread_a_ce0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it53 );

    SC_METHOD(thread_a_d0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it53 );
    sensitive << ( tmp_reg_207 );

    SC_METHOD(thread_a_we0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it53 );
    sensitive << ( ap_reg_ppstg_exitcond_reg_198_pp0_it52 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_exitcond_fu_151_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( i_phi_fu_120_p4 );

    SC_METHOD(thread_grp_BlackScholes_fu_129_CallPutFlag);
    sensitive << ( ap_CS_fsm );
    sensitive << ( CallPutFlag );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( exitcond_reg_198 );

    SC_METHOD(thread_grp_BlackScholes_fu_129_S);
    sensitive << ( ap_CS_fsm );
    sensitive << ( S );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( exitcond_reg_198 );

    SC_METHOD(thread_grp_BlackScholes_fu_129_T);
    sensitive << ( ap_CS_fsm );
    sensitive << ( T );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( exitcond_reg_198 );

    SC_METHOD(thread_grp_BlackScholes_fu_129_X);
    sensitive << ( ap_CS_fsm );
    sensitive << ( X );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( exitcond_reg_198 );

    SC_METHOD(thread_grp_BlackScholes_fu_129_ap_ce);

    SC_METHOD(thread_grp_BlackScholes_fu_129_ap_start);
    sensitive << ( grp_BlackScholes_fu_129_ap_start_ap_start_reg );

    SC_METHOD(thread_grp_BlackScholes_fu_129_b);
    sensitive << ( ap_CS_fsm );
    sensitive << ( b );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( exitcond_reg_198 );

    SC_METHOD(thread_grp_BlackScholes_fu_129_r);
    sensitive << ( ap_CS_fsm );
    sensitive << ( r );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( exitcond_reg_198 );

    SC_METHOD(thread_i_1_fu_157_p2);
    sensitive << ( i_phi_fu_120_p4 );

    SC_METHOD(thread_i_phi_fu_120_p4);
    sensitive << ( ap_CS_fsm );
    sensitive << ( i_reg_116 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( exitcond_reg_198 );
    sensitive << ( i_1_reg_202 );

    SC_METHOD(thread_tmp_s_fu_163_p1);
    sensitive << ( ap_reg_ppstg_i_reg_116_pp0_it52 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it52 );
    sensitive << ( ap_reg_ppiten_pp0_it53 );
    sensitive << ( exitcond_fu_151_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "000";
    ap_reg_ppiten_pp0_it0 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it1 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it2 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it3 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it4 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it5 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it6 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it7 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it8 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it9 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it10 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it11 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it12 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it13 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it14 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it15 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it16 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it17 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it18 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it19 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it20 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it21 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it22 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it23 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it24 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it25 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it26 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it27 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it28 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it29 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it30 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it31 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it32 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it33 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it34 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it35 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it36 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it37 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it38 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it39 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it40 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it41 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it42 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it43 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it44 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it45 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it46 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it47 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it48 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it49 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it50 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it51 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it52 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it53 = SC_LOGIC_0;
    grp_BlackScholes_fu_129_ap_start_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "BlackScholesWrapper_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, CallPutFlag, "(port)CallPutFlag");
    sc_trace(mVcdFile, S, "(port)S");
    sc_trace(mVcdFile, X, "(port)X");
    sc_trace(mVcdFile, T, "(port)T");
    sc_trace(mVcdFile, r, "(port)r");
    sc_trace(mVcdFile, b, "(port)b");
    sc_trace(mVcdFile, a_address0, "(port)a_address0");
    sc_trace(mVcdFile, a_ce0, "(port)a_ce0");
    sc_trace(mVcdFile, a_we0, "(port)a_we0");
    sc_trace(mVcdFile, a_d0, "(port)a_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, i_reg_116, "i_reg_116");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it1, "ap_reg_ppstg_i_reg_116_pp0_it1");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it0, "ap_reg_ppiten_pp0_it0");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it1, "ap_reg_ppiten_pp0_it1");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it2, "ap_reg_ppiten_pp0_it2");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it3, "ap_reg_ppiten_pp0_it3");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it4, "ap_reg_ppiten_pp0_it4");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it5, "ap_reg_ppiten_pp0_it5");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it6, "ap_reg_ppiten_pp0_it6");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it7, "ap_reg_ppiten_pp0_it7");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it8, "ap_reg_ppiten_pp0_it8");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it9, "ap_reg_ppiten_pp0_it9");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it10, "ap_reg_ppiten_pp0_it10");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it11, "ap_reg_ppiten_pp0_it11");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it12, "ap_reg_ppiten_pp0_it12");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it13, "ap_reg_ppiten_pp0_it13");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it14, "ap_reg_ppiten_pp0_it14");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it15, "ap_reg_ppiten_pp0_it15");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it16, "ap_reg_ppiten_pp0_it16");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it17, "ap_reg_ppiten_pp0_it17");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it18, "ap_reg_ppiten_pp0_it18");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it19, "ap_reg_ppiten_pp0_it19");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it20, "ap_reg_ppiten_pp0_it20");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it21, "ap_reg_ppiten_pp0_it21");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it22, "ap_reg_ppiten_pp0_it22");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it23, "ap_reg_ppiten_pp0_it23");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it24, "ap_reg_ppiten_pp0_it24");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it25, "ap_reg_ppiten_pp0_it25");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it26, "ap_reg_ppiten_pp0_it26");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it27, "ap_reg_ppiten_pp0_it27");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it28, "ap_reg_ppiten_pp0_it28");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it29, "ap_reg_ppiten_pp0_it29");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it30, "ap_reg_ppiten_pp0_it30");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it31, "ap_reg_ppiten_pp0_it31");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it32, "ap_reg_ppiten_pp0_it32");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it33, "ap_reg_ppiten_pp0_it33");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it34, "ap_reg_ppiten_pp0_it34");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it35, "ap_reg_ppiten_pp0_it35");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it36, "ap_reg_ppiten_pp0_it36");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it37, "ap_reg_ppiten_pp0_it37");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it38, "ap_reg_ppiten_pp0_it38");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it39, "ap_reg_ppiten_pp0_it39");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it40, "ap_reg_ppiten_pp0_it40");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it41, "ap_reg_ppiten_pp0_it41");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it42, "ap_reg_ppiten_pp0_it42");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it43, "ap_reg_ppiten_pp0_it43");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it44, "ap_reg_ppiten_pp0_it44");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it45, "ap_reg_ppiten_pp0_it45");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it46, "ap_reg_ppiten_pp0_it46");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it47, "ap_reg_ppiten_pp0_it47");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it48, "ap_reg_ppiten_pp0_it48");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it49, "ap_reg_ppiten_pp0_it49");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it50, "ap_reg_ppiten_pp0_it50");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it51, "ap_reg_ppiten_pp0_it51");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it52, "ap_reg_ppiten_pp0_it52");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it53, "ap_reg_ppiten_pp0_it53");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it2, "ap_reg_ppstg_i_reg_116_pp0_it2");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it3, "ap_reg_ppstg_i_reg_116_pp0_it3");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it4, "ap_reg_ppstg_i_reg_116_pp0_it4");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it5, "ap_reg_ppstg_i_reg_116_pp0_it5");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it6, "ap_reg_ppstg_i_reg_116_pp0_it6");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it7, "ap_reg_ppstg_i_reg_116_pp0_it7");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it8, "ap_reg_ppstg_i_reg_116_pp0_it8");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it9, "ap_reg_ppstg_i_reg_116_pp0_it9");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it10, "ap_reg_ppstg_i_reg_116_pp0_it10");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it11, "ap_reg_ppstg_i_reg_116_pp0_it11");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it12, "ap_reg_ppstg_i_reg_116_pp0_it12");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it13, "ap_reg_ppstg_i_reg_116_pp0_it13");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it14, "ap_reg_ppstg_i_reg_116_pp0_it14");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it15, "ap_reg_ppstg_i_reg_116_pp0_it15");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it16, "ap_reg_ppstg_i_reg_116_pp0_it16");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it17, "ap_reg_ppstg_i_reg_116_pp0_it17");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it18, "ap_reg_ppstg_i_reg_116_pp0_it18");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it19, "ap_reg_ppstg_i_reg_116_pp0_it19");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it20, "ap_reg_ppstg_i_reg_116_pp0_it20");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it21, "ap_reg_ppstg_i_reg_116_pp0_it21");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it22, "ap_reg_ppstg_i_reg_116_pp0_it22");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it23, "ap_reg_ppstg_i_reg_116_pp0_it23");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it24, "ap_reg_ppstg_i_reg_116_pp0_it24");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it25, "ap_reg_ppstg_i_reg_116_pp0_it25");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it26, "ap_reg_ppstg_i_reg_116_pp0_it26");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it27, "ap_reg_ppstg_i_reg_116_pp0_it27");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it28, "ap_reg_ppstg_i_reg_116_pp0_it28");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it29, "ap_reg_ppstg_i_reg_116_pp0_it29");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it30, "ap_reg_ppstg_i_reg_116_pp0_it30");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it31, "ap_reg_ppstg_i_reg_116_pp0_it31");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it32, "ap_reg_ppstg_i_reg_116_pp0_it32");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it33, "ap_reg_ppstg_i_reg_116_pp0_it33");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it34, "ap_reg_ppstg_i_reg_116_pp0_it34");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it35, "ap_reg_ppstg_i_reg_116_pp0_it35");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it36, "ap_reg_ppstg_i_reg_116_pp0_it36");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it37, "ap_reg_ppstg_i_reg_116_pp0_it37");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it38, "ap_reg_ppstg_i_reg_116_pp0_it38");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it39, "ap_reg_ppstg_i_reg_116_pp0_it39");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it40, "ap_reg_ppstg_i_reg_116_pp0_it40");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it41, "ap_reg_ppstg_i_reg_116_pp0_it41");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it42, "ap_reg_ppstg_i_reg_116_pp0_it42");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it43, "ap_reg_ppstg_i_reg_116_pp0_it43");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it44, "ap_reg_ppstg_i_reg_116_pp0_it44");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it45, "ap_reg_ppstg_i_reg_116_pp0_it45");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it46, "ap_reg_ppstg_i_reg_116_pp0_it46");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it47, "ap_reg_ppstg_i_reg_116_pp0_it47");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it48, "ap_reg_ppstg_i_reg_116_pp0_it48");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it49, "ap_reg_ppstg_i_reg_116_pp0_it49");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it50, "ap_reg_ppstg_i_reg_116_pp0_it50");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it51, "ap_reg_ppstg_i_reg_116_pp0_it51");
    sc_trace(mVcdFile, ap_reg_ppstg_i_reg_116_pp0_it52, "ap_reg_ppstg_i_reg_116_pp0_it52");
    sc_trace(mVcdFile, exitcond_fu_151_p2, "exitcond_fu_151_p2");
    sc_trace(mVcdFile, exitcond_reg_198, "exitcond_reg_198");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it1, "ap_reg_ppstg_exitcond_reg_198_pp0_it1");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it2, "ap_reg_ppstg_exitcond_reg_198_pp0_it2");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it3, "ap_reg_ppstg_exitcond_reg_198_pp0_it3");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it4, "ap_reg_ppstg_exitcond_reg_198_pp0_it4");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it5, "ap_reg_ppstg_exitcond_reg_198_pp0_it5");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it6, "ap_reg_ppstg_exitcond_reg_198_pp0_it6");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it7, "ap_reg_ppstg_exitcond_reg_198_pp0_it7");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it8, "ap_reg_ppstg_exitcond_reg_198_pp0_it8");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it9, "ap_reg_ppstg_exitcond_reg_198_pp0_it9");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it10, "ap_reg_ppstg_exitcond_reg_198_pp0_it10");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it11, "ap_reg_ppstg_exitcond_reg_198_pp0_it11");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it12, "ap_reg_ppstg_exitcond_reg_198_pp0_it12");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it13, "ap_reg_ppstg_exitcond_reg_198_pp0_it13");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it14, "ap_reg_ppstg_exitcond_reg_198_pp0_it14");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it15, "ap_reg_ppstg_exitcond_reg_198_pp0_it15");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it16, "ap_reg_ppstg_exitcond_reg_198_pp0_it16");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it17, "ap_reg_ppstg_exitcond_reg_198_pp0_it17");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it18, "ap_reg_ppstg_exitcond_reg_198_pp0_it18");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it19, "ap_reg_ppstg_exitcond_reg_198_pp0_it19");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it20, "ap_reg_ppstg_exitcond_reg_198_pp0_it20");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it21, "ap_reg_ppstg_exitcond_reg_198_pp0_it21");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it22, "ap_reg_ppstg_exitcond_reg_198_pp0_it22");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it23, "ap_reg_ppstg_exitcond_reg_198_pp0_it23");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it24, "ap_reg_ppstg_exitcond_reg_198_pp0_it24");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it25, "ap_reg_ppstg_exitcond_reg_198_pp0_it25");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it26, "ap_reg_ppstg_exitcond_reg_198_pp0_it26");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it27, "ap_reg_ppstg_exitcond_reg_198_pp0_it27");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it28, "ap_reg_ppstg_exitcond_reg_198_pp0_it28");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it29, "ap_reg_ppstg_exitcond_reg_198_pp0_it29");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it30, "ap_reg_ppstg_exitcond_reg_198_pp0_it30");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it31, "ap_reg_ppstg_exitcond_reg_198_pp0_it31");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it32, "ap_reg_ppstg_exitcond_reg_198_pp0_it32");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it33, "ap_reg_ppstg_exitcond_reg_198_pp0_it33");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it34, "ap_reg_ppstg_exitcond_reg_198_pp0_it34");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it35, "ap_reg_ppstg_exitcond_reg_198_pp0_it35");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it36, "ap_reg_ppstg_exitcond_reg_198_pp0_it36");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it37, "ap_reg_ppstg_exitcond_reg_198_pp0_it37");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it38, "ap_reg_ppstg_exitcond_reg_198_pp0_it38");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it39, "ap_reg_ppstg_exitcond_reg_198_pp0_it39");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it40, "ap_reg_ppstg_exitcond_reg_198_pp0_it40");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it41, "ap_reg_ppstg_exitcond_reg_198_pp0_it41");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it42, "ap_reg_ppstg_exitcond_reg_198_pp0_it42");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it43, "ap_reg_ppstg_exitcond_reg_198_pp0_it43");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it44, "ap_reg_ppstg_exitcond_reg_198_pp0_it44");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it45, "ap_reg_ppstg_exitcond_reg_198_pp0_it45");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it46, "ap_reg_ppstg_exitcond_reg_198_pp0_it46");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it47, "ap_reg_ppstg_exitcond_reg_198_pp0_it47");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it48, "ap_reg_ppstg_exitcond_reg_198_pp0_it48");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it49, "ap_reg_ppstg_exitcond_reg_198_pp0_it49");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it50, "ap_reg_ppstg_exitcond_reg_198_pp0_it50");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it51, "ap_reg_ppstg_exitcond_reg_198_pp0_it51");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_198_pp0_it52, "ap_reg_ppstg_exitcond_reg_198_pp0_it52");
    sc_trace(mVcdFile, i_1_fu_157_p2, "i_1_fu_157_p2");
    sc_trace(mVcdFile, i_1_reg_202, "i_1_reg_202");
    sc_trace(mVcdFile, grp_BlackScholes_fu_129_ap_return, "grp_BlackScholes_fu_129_ap_return");
    sc_trace(mVcdFile, tmp_reg_207, "tmp_reg_207");
    sc_trace(mVcdFile, grp_BlackScholes_fu_129_ap_start, "grp_BlackScholes_fu_129_ap_start");
    sc_trace(mVcdFile, grp_BlackScholes_fu_129_ap_done, "grp_BlackScholes_fu_129_ap_done");
    sc_trace(mVcdFile, grp_BlackScholes_fu_129_ap_idle, "grp_BlackScholes_fu_129_ap_idle");
    sc_trace(mVcdFile, grp_BlackScholes_fu_129_ap_ready, "grp_BlackScholes_fu_129_ap_ready");
    sc_trace(mVcdFile, grp_BlackScholes_fu_129_ap_ce, "grp_BlackScholes_fu_129_ap_ce");
    sc_trace(mVcdFile, grp_BlackScholes_fu_129_CallPutFlag, "grp_BlackScholes_fu_129_CallPutFlag");
    sc_trace(mVcdFile, grp_BlackScholes_fu_129_S, "grp_BlackScholes_fu_129_S");
    sc_trace(mVcdFile, grp_BlackScholes_fu_129_X, "grp_BlackScholes_fu_129_X");
    sc_trace(mVcdFile, grp_BlackScholes_fu_129_T, "grp_BlackScholes_fu_129_T");
    sc_trace(mVcdFile, grp_BlackScholes_fu_129_r, "grp_BlackScholes_fu_129_r");
    sc_trace(mVcdFile, grp_BlackScholes_fu_129_b, "grp_BlackScholes_fu_129_b");
    sc_trace(mVcdFile, i_phi_fu_120_p4, "i_phi_fu_120_p4");
    sc_trace(mVcdFile, grp_BlackScholes_fu_129_ap_start_ap_start_reg, "grp_BlackScholes_fu_129_ap_start_ap_start_reg");
    sc_trace(mVcdFile, tmp_s_fu_163_p1, "tmp_s_fu_163_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("BlackScholesWrapper.hdltvin.dat");
    mHdltvoutHandle.open("BlackScholesWrapper.hdltvout.dat");
}

BlackScholesWrapper::~BlackScholesWrapper() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete grp_BlackScholes_fu_129;
}

void BlackScholesWrapper::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,3,3>(ap_ST_pp0_stg0_fsm_1, ap_CS_fsm.read()) && 
             !esl_seteq<1,1,1>(exitcond_fu_151_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
        } else if ((esl_seteq<1,3,3>(ap_ST_st1_fsm_0, ap_CS_fsm.read()) && 
                    !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read()) && 
             esl_seteq<1,1,1>(exitcond_reg_198.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_1;
        } else if (((esl_seteq<1,3,3>(ap_ST_st1_fsm_0, ap_CS_fsm.read()) && 
                     !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) || 
                    (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read()) && 
                     !esl_seteq<1,1,1>(exitcond_reg_198.read(), ap_const_lv1_0)))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it10 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it10 = ap_reg_ppiten_pp0_it9.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it11 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it11 = ap_reg_ppiten_pp0_it10.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it12 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it12 = ap_reg_ppiten_pp0_it11.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it13 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it13 = ap_reg_ppiten_pp0_it12.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it14 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it14 = ap_reg_ppiten_pp0_it13.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it15 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it15 = ap_reg_ppiten_pp0_it14.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it16 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it16 = ap_reg_ppiten_pp0_it15.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it17 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it17 = ap_reg_ppiten_pp0_it16.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it18 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it18 = ap_reg_ppiten_pp0_it17.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it19 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it19 = ap_reg_ppiten_pp0_it18.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it2 = ap_reg_ppiten_pp0_it1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it20 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it20 = ap_reg_ppiten_pp0_it19.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it21 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it21 = ap_reg_ppiten_pp0_it20.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it22 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it22 = ap_reg_ppiten_pp0_it21.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it23 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it23 = ap_reg_ppiten_pp0_it22.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it24 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it24 = ap_reg_ppiten_pp0_it23.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it25 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it25 = ap_reg_ppiten_pp0_it24.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it26 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it26 = ap_reg_ppiten_pp0_it25.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it27 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it27 = ap_reg_ppiten_pp0_it26.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it28 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it28 = ap_reg_ppiten_pp0_it27.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it29 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it29 = ap_reg_ppiten_pp0_it28.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it3 = ap_reg_ppiten_pp0_it2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it30 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it30 = ap_reg_ppiten_pp0_it29.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it31 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it31 = ap_reg_ppiten_pp0_it30.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it32 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it32 = ap_reg_ppiten_pp0_it31.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it33 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it33 = ap_reg_ppiten_pp0_it32.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it34 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it34 = ap_reg_ppiten_pp0_it33.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it35 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it35 = ap_reg_ppiten_pp0_it34.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it36 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it36 = ap_reg_ppiten_pp0_it35.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it37 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it37 = ap_reg_ppiten_pp0_it36.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it38 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it38 = ap_reg_ppiten_pp0_it37.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it39 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it39 = ap_reg_ppiten_pp0_it38.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it4 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it4 = ap_reg_ppiten_pp0_it3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it40 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it40 = ap_reg_ppiten_pp0_it39.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it41 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it41 = ap_reg_ppiten_pp0_it40.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it42 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it42 = ap_reg_ppiten_pp0_it41.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it43 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it43 = ap_reg_ppiten_pp0_it42.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it44 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it44 = ap_reg_ppiten_pp0_it43.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it45 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it45 = ap_reg_ppiten_pp0_it44.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it46 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it46 = ap_reg_ppiten_pp0_it45.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it47 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it47 = ap_reg_ppiten_pp0_it46.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it48 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it48 = ap_reg_ppiten_pp0_it47.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it49 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it49 = ap_reg_ppiten_pp0_it48.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it5 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it5 = ap_reg_ppiten_pp0_it4.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it50 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it50 = ap_reg_ppiten_pp0_it49.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it51 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it51 = ap_reg_ppiten_pp0_it50.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it52 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it52 = ap_reg_ppiten_pp0_it51.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it53 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it53 = ap_reg_ppiten_pp0_it52.read();
        } else if ((esl_seteq<1,3,3>(ap_ST_st1_fsm_0, ap_CS_fsm.read()) && 
                    !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_reg_ppiten_pp0_it53 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it6 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it6 = ap_reg_ppiten_pp0_it5.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it7 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it7 = ap_reg_ppiten_pp0_it6.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it8 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it8 = ap_reg_ppiten_pp0_it7.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it9 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read())) {
            ap_reg_ppiten_pp0_it9 = ap_reg_ppiten_pp0_it8.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_BlackScholes_fu_129_ap_start_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,3,3>(ap_ST_pp0_stg0_fsm_1, ap_CS_fsm.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
             esl_seteq<1,1,1>(exitcond_fu_151_p2.read(), ap_const_lv1_0))) {
            grp_BlackScholes_fu_129_ap_start_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_BlackScholes_fu_129_ap_ready.read())) {
            grp_BlackScholes_fu_129_ap_start_ap_start_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,3,3>(ap_ST_pp0_stg0_fsm_1, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond_reg_198.read(), ap_const_lv1_0))) {
        i_reg_116 = i_1_reg_202.read();
    } else if ((esl_seteq<1,3,3>(ap_ST_st1_fsm_0, ap_CS_fsm.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        i_reg_116 = ap_const_lv17_0;
    }
    if (esl_seteq<1,3,3>(ap_ST_pp0_stg0_fsm_1, ap_CS_fsm.read())) {
        ap_reg_ppstg_exitcond_reg_198_pp0_it1 = exitcond_reg_198.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it10 = ap_reg_ppstg_exitcond_reg_198_pp0_it9.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it11 = ap_reg_ppstg_exitcond_reg_198_pp0_it10.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it12 = ap_reg_ppstg_exitcond_reg_198_pp0_it11.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it13 = ap_reg_ppstg_exitcond_reg_198_pp0_it12.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it14 = ap_reg_ppstg_exitcond_reg_198_pp0_it13.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it15 = ap_reg_ppstg_exitcond_reg_198_pp0_it14.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it16 = ap_reg_ppstg_exitcond_reg_198_pp0_it15.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it17 = ap_reg_ppstg_exitcond_reg_198_pp0_it16.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it18 = ap_reg_ppstg_exitcond_reg_198_pp0_it17.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it19 = ap_reg_ppstg_exitcond_reg_198_pp0_it18.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it2 = ap_reg_ppstg_exitcond_reg_198_pp0_it1.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it20 = ap_reg_ppstg_exitcond_reg_198_pp0_it19.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it21 = ap_reg_ppstg_exitcond_reg_198_pp0_it20.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it22 = ap_reg_ppstg_exitcond_reg_198_pp0_it21.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it23 = ap_reg_ppstg_exitcond_reg_198_pp0_it22.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it24 = ap_reg_ppstg_exitcond_reg_198_pp0_it23.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it25 = ap_reg_ppstg_exitcond_reg_198_pp0_it24.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it26 = ap_reg_ppstg_exitcond_reg_198_pp0_it25.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it27 = ap_reg_ppstg_exitcond_reg_198_pp0_it26.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it28 = ap_reg_ppstg_exitcond_reg_198_pp0_it27.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it29 = ap_reg_ppstg_exitcond_reg_198_pp0_it28.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it3 = ap_reg_ppstg_exitcond_reg_198_pp0_it2.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it30 = ap_reg_ppstg_exitcond_reg_198_pp0_it29.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it31 = ap_reg_ppstg_exitcond_reg_198_pp0_it30.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it32 = ap_reg_ppstg_exitcond_reg_198_pp0_it31.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it33 = ap_reg_ppstg_exitcond_reg_198_pp0_it32.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it34 = ap_reg_ppstg_exitcond_reg_198_pp0_it33.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it35 = ap_reg_ppstg_exitcond_reg_198_pp0_it34.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it36 = ap_reg_ppstg_exitcond_reg_198_pp0_it35.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it37 = ap_reg_ppstg_exitcond_reg_198_pp0_it36.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it38 = ap_reg_ppstg_exitcond_reg_198_pp0_it37.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it39 = ap_reg_ppstg_exitcond_reg_198_pp0_it38.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it4 = ap_reg_ppstg_exitcond_reg_198_pp0_it3.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it40 = ap_reg_ppstg_exitcond_reg_198_pp0_it39.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it41 = ap_reg_ppstg_exitcond_reg_198_pp0_it40.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it42 = ap_reg_ppstg_exitcond_reg_198_pp0_it41.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it43 = ap_reg_ppstg_exitcond_reg_198_pp0_it42.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it44 = ap_reg_ppstg_exitcond_reg_198_pp0_it43.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it45 = ap_reg_ppstg_exitcond_reg_198_pp0_it44.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it46 = ap_reg_ppstg_exitcond_reg_198_pp0_it45.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it47 = ap_reg_ppstg_exitcond_reg_198_pp0_it46.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it48 = ap_reg_ppstg_exitcond_reg_198_pp0_it47.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it49 = ap_reg_ppstg_exitcond_reg_198_pp0_it48.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it5 = ap_reg_ppstg_exitcond_reg_198_pp0_it4.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it50 = ap_reg_ppstg_exitcond_reg_198_pp0_it49.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it51 = ap_reg_ppstg_exitcond_reg_198_pp0_it50.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it52 = ap_reg_ppstg_exitcond_reg_198_pp0_it51.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it6 = ap_reg_ppstg_exitcond_reg_198_pp0_it5.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it7 = ap_reg_ppstg_exitcond_reg_198_pp0_it6.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it8 = ap_reg_ppstg_exitcond_reg_198_pp0_it7.read();
        ap_reg_ppstg_exitcond_reg_198_pp0_it9 = ap_reg_ppstg_exitcond_reg_198_pp0_it8.read();
        ap_reg_ppstg_i_reg_116_pp0_it1 = i_reg_116.read();
        ap_reg_ppstg_i_reg_116_pp0_it10 = ap_reg_ppstg_i_reg_116_pp0_it9.read();
        ap_reg_ppstg_i_reg_116_pp0_it11 = ap_reg_ppstg_i_reg_116_pp0_it10.read();
        ap_reg_ppstg_i_reg_116_pp0_it12 = ap_reg_ppstg_i_reg_116_pp0_it11.read();
        ap_reg_ppstg_i_reg_116_pp0_it13 = ap_reg_ppstg_i_reg_116_pp0_it12.read();
        ap_reg_ppstg_i_reg_116_pp0_it14 = ap_reg_ppstg_i_reg_116_pp0_it13.read();
        ap_reg_ppstg_i_reg_116_pp0_it15 = ap_reg_ppstg_i_reg_116_pp0_it14.read();
        ap_reg_ppstg_i_reg_116_pp0_it16 = ap_reg_ppstg_i_reg_116_pp0_it15.read();
        ap_reg_ppstg_i_reg_116_pp0_it17 = ap_reg_ppstg_i_reg_116_pp0_it16.read();
        ap_reg_ppstg_i_reg_116_pp0_it18 = ap_reg_ppstg_i_reg_116_pp0_it17.read();
        ap_reg_ppstg_i_reg_116_pp0_it19 = ap_reg_ppstg_i_reg_116_pp0_it18.read();
        ap_reg_ppstg_i_reg_116_pp0_it2 = ap_reg_ppstg_i_reg_116_pp0_it1.read();
        ap_reg_ppstg_i_reg_116_pp0_it20 = ap_reg_ppstg_i_reg_116_pp0_it19.read();
        ap_reg_ppstg_i_reg_116_pp0_it21 = ap_reg_ppstg_i_reg_116_pp0_it20.read();
        ap_reg_ppstg_i_reg_116_pp0_it22 = ap_reg_ppstg_i_reg_116_pp0_it21.read();
        ap_reg_ppstg_i_reg_116_pp0_it23 = ap_reg_ppstg_i_reg_116_pp0_it22.read();
        ap_reg_ppstg_i_reg_116_pp0_it24 = ap_reg_ppstg_i_reg_116_pp0_it23.read();
        ap_reg_ppstg_i_reg_116_pp0_it25 = ap_reg_ppstg_i_reg_116_pp0_it24.read();
        ap_reg_ppstg_i_reg_116_pp0_it26 = ap_reg_ppstg_i_reg_116_pp0_it25.read();
        ap_reg_ppstg_i_reg_116_pp0_it27 = ap_reg_ppstg_i_reg_116_pp0_it26.read();
        ap_reg_ppstg_i_reg_116_pp0_it28 = ap_reg_ppstg_i_reg_116_pp0_it27.read();
        ap_reg_ppstg_i_reg_116_pp0_it29 = ap_reg_ppstg_i_reg_116_pp0_it28.read();
        ap_reg_ppstg_i_reg_116_pp0_it3 = ap_reg_ppstg_i_reg_116_pp0_it2.read();
        ap_reg_ppstg_i_reg_116_pp0_it30 = ap_reg_ppstg_i_reg_116_pp0_it29.read();
        ap_reg_ppstg_i_reg_116_pp0_it31 = ap_reg_ppstg_i_reg_116_pp0_it30.read();
        ap_reg_ppstg_i_reg_116_pp0_it32 = ap_reg_ppstg_i_reg_116_pp0_it31.read();
        ap_reg_ppstg_i_reg_116_pp0_it33 = ap_reg_ppstg_i_reg_116_pp0_it32.read();
        ap_reg_ppstg_i_reg_116_pp0_it34 = ap_reg_ppstg_i_reg_116_pp0_it33.read();
        ap_reg_ppstg_i_reg_116_pp0_it35 = ap_reg_ppstg_i_reg_116_pp0_it34.read();
        ap_reg_ppstg_i_reg_116_pp0_it36 = ap_reg_ppstg_i_reg_116_pp0_it35.read();
        ap_reg_ppstg_i_reg_116_pp0_it37 = ap_reg_ppstg_i_reg_116_pp0_it36.read();
        ap_reg_ppstg_i_reg_116_pp0_it38 = ap_reg_ppstg_i_reg_116_pp0_it37.read();
        ap_reg_ppstg_i_reg_116_pp0_it39 = ap_reg_ppstg_i_reg_116_pp0_it38.read();
        ap_reg_ppstg_i_reg_116_pp0_it4 = ap_reg_ppstg_i_reg_116_pp0_it3.read();
        ap_reg_ppstg_i_reg_116_pp0_it40 = ap_reg_ppstg_i_reg_116_pp0_it39.read();
        ap_reg_ppstg_i_reg_116_pp0_it41 = ap_reg_ppstg_i_reg_116_pp0_it40.read();
        ap_reg_ppstg_i_reg_116_pp0_it42 = ap_reg_ppstg_i_reg_116_pp0_it41.read();
        ap_reg_ppstg_i_reg_116_pp0_it43 = ap_reg_ppstg_i_reg_116_pp0_it42.read();
        ap_reg_ppstg_i_reg_116_pp0_it44 = ap_reg_ppstg_i_reg_116_pp0_it43.read();
        ap_reg_ppstg_i_reg_116_pp0_it45 = ap_reg_ppstg_i_reg_116_pp0_it44.read();
        ap_reg_ppstg_i_reg_116_pp0_it46 = ap_reg_ppstg_i_reg_116_pp0_it45.read();
        ap_reg_ppstg_i_reg_116_pp0_it47 = ap_reg_ppstg_i_reg_116_pp0_it46.read();
        ap_reg_ppstg_i_reg_116_pp0_it48 = ap_reg_ppstg_i_reg_116_pp0_it47.read();
        ap_reg_ppstg_i_reg_116_pp0_it49 = ap_reg_ppstg_i_reg_116_pp0_it48.read();
        ap_reg_ppstg_i_reg_116_pp0_it5 = ap_reg_ppstg_i_reg_116_pp0_it4.read();
        ap_reg_ppstg_i_reg_116_pp0_it50 = ap_reg_ppstg_i_reg_116_pp0_it49.read();
        ap_reg_ppstg_i_reg_116_pp0_it51 = ap_reg_ppstg_i_reg_116_pp0_it50.read();
        ap_reg_ppstg_i_reg_116_pp0_it52 = ap_reg_ppstg_i_reg_116_pp0_it51.read();
        ap_reg_ppstg_i_reg_116_pp0_it6 = ap_reg_ppstg_i_reg_116_pp0_it5.read();
        ap_reg_ppstg_i_reg_116_pp0_it7 = ap_reg_ppstg_i_reg_116_pp0_it6.read();
        ap_reg_ppstg_i_reg_116_pp0_it8 = ap_reg_ppstg_i_reg_116_pp0_it7.read();
        ap_reg_ppstg_i_reg_116_pp0_it9 = ap_reg_ppstg_i_reg_116_pp0_it8.read();
    }
    if ((esl_seteq<1,3,3>(ap_ST_pp0_stg0_fsm_1, ap_CS_fsm.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()))) {
        exitcond_reg_198 = exitcond_fu_151_p2.read();
        i_1_reg_202 = i_1_fu_157_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it52.read()) && esl_seteq<1,3,3>(ap_ST_pp0_stg3_fsm_4, ap_CS_fsm.read()) && esl_seteq<1,1,1>(ap_reg_ppstg_exitcond_reg_198_pp0_it52.read(), ap_const_lv1_0))) {
        tmp_reg_207 = grp_BlackScholes_fu_129_ap_return.read();
    }
}

void BlackScholesWrapper::thread_a_address0() {
    a_address0 =  (sc_lv<17>) (tmp_s_fu_163_p1.read());
}

void BlackScholesWrapper::thread_a_ce0() {
    if ((esl_seteq<1,3,3>(ap_ST_pp0_stg0_fsm_1, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it53.read()))) {
        a_ce0 = ap_const_logic_1;
    } else {
        a_ce0 = ap_const_logic_0;
    }
}

void BlackScholesWrapper::thread_a_d0() {
    a_d0 = tmp_reg_207.read();
}

void BlackScholesWrapper::thread_a_we0() {
    if (((esl_seteq<1,3,3>(ap_ST_pp0_stg0_fsm_1, ap_CS_fsm.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it53.read()) && 
          esl_seteq<1,1,1>(ap_reg_ppstg_exitcond_reg_198_pp0_it52.read(), ap_const_lv1_0)))) {
        a_we0 = ap_const_logic_1;
    } else {
        a_we0 = ap_const_logic_0;
    }
}

void BlackScholesWrapper::thread_ap_done() {
    if (esl_seteq<1,3,3>(ap_ST_st215_fsm_5, ap_CS_fsm.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void BlackScholesWrapper::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,3,3>(ap_ST_st1_fsm_0, ap_CS_fsm.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void BlackScholesWrapper::thread_ap_ready() {
    if (esl_seteq<1,3,3>(ap_ST_st215_fsm_5, ap_CS_fsm.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void BlackScholesWrapper::thread_exitcond_fu_151_p2() {
    exitcond_fu_151_p2 = (!i_phi_fu_120_p4.read().is_01() || !ap_const_lv17_186A0.is_01())? sc_lv<1>(): sc_lv<1>(i_phi_fu_120_p4.read() == ap_const_lv17_186A0);
}

void BlackScholesWrapper::thread_grp_BlackScholes_fu_129_CallPutFlag() {
    grp_BlackScholes_fu_129_CallPutFlag = CallPutFlag.read();
}

void BlackScholesWrapper::thread_grp_BlackScholes_fu_129_S() {
    grp_BlackScholes_fu_129_S = S.read();
}

void BlackScholesWrapper::thread_grp_BlackScholes_fu_129_T() {
    grp_BlackScholes_fu_129_T = T.read();
}

void BlackScholesWrapper::thread_grp_BlackScholes_fu_129_X() {
    grp_BlackScholes_fu_129_X = X.read();
}

void BlackScholesWrapper::thread_grp_BlackScholes_fu_129_ap_ce() {
    grp_BlackScholes_fu_129_ap_ce = ap_const_logic_1;
}

void BlackScholesWrapper::thread_grp_BlackScholes_fu_129_ap_start() {
    grp_BlackScholes_fu_129_ap_start = grp_BlackScholes_fu_129_ap_start_ap_start_reg.read();
}

void BlackScholesWrapper::thread_grp_BlackScholes_fu_129_b() {
    grp_BlackScholes_fu_129_b = b.read();
}

void BlackScholesWrapper::thread_grp_BlackScholes_fu_129_r() {
    grp_BlackScholes_fu_129_r = r.read();
}

void BlackScholesWrapper::thread_i_1_fu_157_p2() {
    i_1_fu_157_p2 = (!i_phi_fu_120_p4.read().is_01() || !ap_const_lv17_1.is_01())? sc_lv<17>(): (sc_bigint<17>(i_phi_fu_120_p4.read()) + sc_biguint<17>(ap_const_lv17_1));
}

void BlackScholesWrapper::thread_i_phi_fu_120_p4() {
    if ((esl_seteq<1,3,3>(ap_ST_pp0_stg0_fsm_1, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond_reg_198.read(), ap_const_lv1_0))) {
        i_phi_fu_120_p4 = i_1_reg_202.read();
    } else {
        i_phi_fu_120_p4 = i_reg_116.read();
    }
}

void BlackScholesWrapper::thread_tmp_s_fu_163_p1() {
    tmp_s_fu_163_p1 = esl_zext<64,17>(ap_reg_ppstg_i_reg_116_pp0_it52.read());
}

void BlackScholesWrapper::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 0 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 1 : 
            if ((!(esl_seteq<1,3,3>(ap_ST_pp0_stg0_fsm_1, ap_CS_fsm.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it53.read()) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it52.read())) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !esl_seteq<1,1,1>(exitcond_fu_151_p2.read(), ap_const_lv1_0) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
                ap_NS_fsm = ap_ST_pp0_stg1_fsm_2;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !esl_seteq<1,1,1>(exitcond_fu_151_p2.read(), ap_const_lv1_0) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()))) {
                ap_NS_fsm = ap_ST_st215_fsm_5;
            } else {
                ap_NS_fsm = ap_ST_st215_fsm_5;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_pp0_stg2_fsm_3;
            break;
        case 3 : 
            ap_NS_fsm = ap_ST_pp0_stg3_fsm_4;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            break;
        case 5 : 
            ap_NS_fsm = ap_ST_st1_fsm_0;
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

void BlackScholesWrapper::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"CallPutFlag\" :  \"" << CallPutFlag.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"S\" :  \"" << S.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"X\" :  \"" << X.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"T\" :  \"" << T.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"r\" :  \"" << r.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"b\" :  \"" << b.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"a_address0\" :  \"" << a_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"a_ce0\" :  \"" << a_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"a_we0\" :  \"" << a_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"a_d0\" :  \"" << a_d0.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

