// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.2
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _BlackScholes_HH_
#define _BlackScholes_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "rand_uint32.h"

namespace ap_rtl {

struct BlackScholes : public sc_module {
    // Port declarations 7
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_logic > ap_ce;


    // Module declarations
    BlackScholes(sc_module_name name);
    SC_HAS_PROCESS(BlackScholes);

    ~BlackScholes();

    sc_trace_file* mVcdFile;

    rand_uint32* grp_rand_uint32_fu_25;
    sc_signal< sc_lv<2> > ap_CS_fsm;
    sc_signal< sc_logic > grp_rand_uint32_fu_25_ap_start;
    sc_signal< sc_logic > grp_rand_uint32_fu_25_ap_done;
    sc_signal< sc_logic > grp_rand_uint32_fu_25_ap_idle;
    sc_signal< sc_logic > grp_rand_uint32_fu_25_ap_ready;
    sc_signal< sc_logic > grp_rand_uint32_fu_25_ap_ce;
    sc_signal< sc_lv<2> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<2> ap_ST_st1_fsm_0;
    static const sc_lv<2> ap_ST_st2_fsm_1;
    static const sc_lv<2> ap_ST_st3_fsm_2;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_grp_rand_uint32_fu_25_ap_ce();
    void thread_grp_rand_uint32_fu_25_ap_start();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
