#pragma line 1 "black_scholes2.c" ::: 0
#pragma line 1 "black_scholes2.c" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 149 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 12
#pragma line 278 "/opt/xilinx/Vivado_HLS/2014.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 65
#pragma line 8 "<command line>" 2 ::: 191
#pragma line 1 "<built-in>" 2 ::: 192
#pragma line 1 "black_scholes2.c" 2 ::: 193
#pragma line 1 "./black_scholes2.h" 1 ::: 194
#pragma line 1 "/usr/include/math.h" 1 3 4 ::: 198
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 227
#pragma line 115 "/usr/include/features.h" 3 4 ::: 320
#pragma line 139 "/usr/include/features.h" 3 4 ::: 337
#pragma line 169 "/usr/include/features.h" 3 4 ::: 347
#pragma line 179 "/usr/include/features.h" 3 4 ::: 350
#pragma line 294 "/usr/include/features.h" 3 4 ::: 362
#pragma line 1 "/usr/include/sys/cdefs.h" 1 3 4 ::: 399
#pragma line 72 "/usr/include/sys/cdefs.h" 3 4 ::: 445
#pragma line 98 "/usr/include/sys/cdefs.h" 3 4 ::: 463
#pragma line 111 "/usr/include/sys/cdefs.h" 3 4 ::: 469
#pragma line 123 "/usr/include/sys/cdefs.h" 3 4 ::: 473
#pragma line 155 "/usr/include/sys/cdefs.h" 3 4 ::: 491
#pragma line 178 "/usr/include/sys/cdefs.h" 3 4 ::: 501
#pragma line 222 "/usr/include/sys/cdefs.h" 3 4 ::: 538
#pragma line 275 "/usr/include/sys/cdefs.h" 3 4 ::: 579
#pragma line 313 "/usr/include/sys/cdefs.h" 3 4 ::: 603
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 604
#pragma line 314 "/usr/include/sys/cdefs.h" 2 3 4 ::: 606
#pragma line 330 "/usr/include/features.h" 2 3 4 ::: 607
#pragma line 1 "/usr/include/gnu/stubs.h" 1 3 4 ::: 631
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 636
#pragma line 5 "/usr/include/gnu/stubs.h" 2 3 4 ::: 638
#pragma line 1 "/usr/include/gnu/stubs-64.h" 1 3 4 ::: 643
#pragma line 10 "/usr/include/gnu/stubs.h" 2 3 4 ::: 648
#pragma line 353 "/usr/include/features.h" 2 3 4 ::: 649
#pragma line 29 "/usr/include/math.h" 2 3 4 ::: 650
#pragma line 1 "/usr/include/bits/huge_val.h" 1 3 4 ::: 657
#pragma line 35 "/usr/include/math.h" 2 3 4 ::: 684
#pragma line 46 "/usr/include/math.h" 3 4 ::: 685
#pragma line 1 "/usr/include/bits/mathdef.h" 1 3 4 ::: 688
#pragma line 48 "/usr/include/math.h" 2 3 4 ::: 706
#pragma line 71 "/usr/include/math.h" 3 4 ::: 712
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 713
#pragma line 88 "/usr/include/bits/mathcalls.h" 3 4 ::: 791
#pragma line 128 "/usr/include/bits/mathcalls.h" 3 4 ::: 821
#pragma line 150 "/usr/include/bits/mathcalls.h" 3 4 ::: 830
#pragma line 230 "/usr/include/bits/mathcalls.h" 3 4 ::: 900
#pragma line 264 "/usr/include/bits/mathcalls.h" 3 4 ::: 924
#pragma line 363 "/usr/include/bits/mathcalls.h" 3 4 ::: 959
#pragma line 72 "/usr/include/math.h" 2 3 4 ::: 962
#pragma line 94 "/usr/include/math.h" 3 4 ::: 973
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 974
#pragma line 88 "/usr/include/bits/mathcalls.h" 3 4 ::: 1052
#pragma line 128 "/usr/include/bits/mathcalls.h" 3 4 ::: 1082
#pragma line 150 "/usr/include/bits/mathcalls.h" 3 4 ::: 1091
#pragma line 230 "/usr/include/bits/mathcalls.h" 3 4 ::: 1161
#pragma line 264 "/usr/include/bits/mathcalls.h" 3 4 ::: 1185
#pragma line 363 "/usr/include/bits/mathcalls.h" 3 4 ::: 1220
#pragma line 95 "/usr/include/math.h" 2 3 4 ::: 1223
#pragma line 141 "/usr/include/math.h" 3 4 ::: 1224
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 1225
#pragma line 88 "/usr/include/bits/mathcalls.h" 3 4 ::: 1303
#pragma line 128 "/usr/include/bits/mathcalls.h" 3 4 ::: 1333
#pragma line 150 "/usr/include/bits/mathcalls.h" 3 4 ::: 1342
#pragma line 230 "/usr/include/bits/mathcalls.h" 3 4 ::: 1412
#pragma line 264 "/usr/include/bits/mathcalls.h" 3 4 ::: 1436
#pragma line 363 "/usr/include/bits/mathcalls.h" 3 4 ::: 1471
#pragma line 142 "/usr/include/math.h" 2 3 4 ::: 1474
#pragma line 156 "/usr/include/math.h" 3 4 ::: 1475
#pragma line 283 "/usr/include/math.h" 3 4 ::: 1482
#pragma line 348 "/usr/include/math.h" 3 4 ::: 1536
#pragma line 365 "/usr/include/math.h" 3 4 ::: 1538
#pragma line 385 "/usr/include/math.h" 3 4 ::: 1542
#pragma line 407 "/usr/include/math.h" 3 4 ::: 1546
#pragma line 5 "./black_scholes2.h" 2 ::: 1548
#pragma line 1 "./util.h" 1 ::: 1549
#pragma line 6 "./black_scholes2.h" 2 ::: 1599
#pragma line 1 "/usr/include/assert.h" 1 3 4 ::: 1600
#pragma line 44 "/usr/include/assert.h" 3 4 ::: 1622
#pragma line 67 "/usr/include/assert.h" 3 4 ::: 1627
#pragma line 101 "/usr/include/assert.h" 3 4 ::: 1644
#pragma line 7 "./black_scholes2.h" 2 ::: 1650
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 1651
#pragma line 34 "/usr/include/stdio.h" 3 4 ::: 1674
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1675
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1716
#pragma line 35 "/usr/include/stdio.h" 2 3 4 ::: 1719
#pragma line 1 "/usr/include/bits/types.h" 1 3 4 ::: 1721
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 1750
#pragma line 29 "/usr/include/bits/types.h" 2 3 4 ::: 1752
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1755
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1780
#pragma line 32 "/usr/include/bits/types.h" 2 3 4 ::: 1783
#pragma line 73 "/usr/include/bits/types.h" 3 4 ::: 1810
#pragma line 129 "/usr/include/bits/types.h" 3 4 ::: 1839
#pragma line 1 "/usr/include/bits/typesizes.h" 1 3 4 ::: 1846
#pragma line 27 "/usr/include/bits/typesizes.h" 3 4 ::: 1865
#pragma line 62 "/usr/include/bits/typesizes.h" 3 4 ::: 1868
#pragma line 135 "/usr/include/bits/types.h" 2 3 4 ::: 1870
#pragma line 37 "/usr/include/stdio.h" 2 3 4 ::: 1932
#pragma line 61 "/usr/include/stdio.h" 3 4 ::: 1943
#pragma line 72 "/usr/include/stdio.h" 3 4 ::: 1946
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 1947
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 1980
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1995
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2020
#pragma line 15 "/usr/include/_G_config.h" 2 3 4 ::: 2027
#pragma line 24 "/usr/include/_G_config.h" 3 4 ::: 2028
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 2029
#pragma line 48 "/usr/include/wchar.h" 3 4 ::: 2052
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2053
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2078
#pragma line 49 "/usr/include/wchar.h" 2 3 4 ::: 2081
#pragma line 1 "/usr/include/bits/wchar.h" 1 3 4 ::: 2083
#pragma line 51 "/usr/include/wchar.h" 2 3 4 ::: 2102
#pragma line 62 "/usr/include/wchar.h" 3 4 ::: 2106
#pragma line 75 "/usr/include/wchar.h" 3 4 ::: 2109
#pragma line 25 "/usr/include/_G_config.h" 2 3 4 ::: 2126
#pragma line 44 "/usr/include/_G_config.h" 3 4 ::: 2138
#pragma line 1 "/usr/include/gconv.h" 1 3 4 ::: 2139
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 2168
#pragma line 48 "/usr/include/wchar.h" 3 4 ::: 2191
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2192
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2217
#pragma line 49 "/usr/include/wchar.h" 2 3 4 ::: 2220
#pragma line 62 "/usr/include/wchar.h" 3 4 ::: 2226
#pragma line 89 "/usr/include/wchar.h" 3 4 ::: 2229
#pragma line 29 "/usr/include/gconv.h" 2 3 4 ::: 2232
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2235
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2260
#pragma line 32 "/usr/include/gconv.h" 2 3 4 ::: 2263
#pragma line 45 "/usr/include/_G_config.h" 2 3 4 ::: 2410
#pragma line 84 "/usr/include/_G_config.h" 3 4 ::: 2430
#pragma line 33 "/usr/include/libio.h" 2 3 4 ::: 2437
#pragma line 51 "/usr/include/libio.h" 3 4 ::: 2439
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 2443
#pragma line 54 "/usr/include/libio.h" 2 3 4 ::: 2492
#pragma line 74 "/usr/include/libio.h" 3 4 ::: 2493
#pragma line 114 "/usr/include/libio.h" 3 4 ::: 2495
#pragma line 147 "/usr/include/libio.h" 3 4 ::: 2501
#pragma line 167 "/usr/include/libio.h" 3 4 ::: 2503
#pragma line 200 "/usr/include/libio.h" 3 4 ::: 2527
#pragma line 268 "/usr/include/libio.h" 3 4 ::: 2538
#pragma line 316 "/usr/include/libio.h" 3 4 ::: 2579
#pragma line 325 "/usr/include/libio.h" 3 4 ::: 2581
#pragma line 357 "/usr/include/libio.h" 3 4 ::: 2603
#pragma line 413 "/usr/include/libio.h" 3 4 ::: 2629
#pragma line 451 "/usr/include/libio.h" 3 4 ::: 2636
#pragma line 481 "/usr/include/libio.h" 3 4 ::: 2651
#pragma line 73 "/usr/include/stdio.h" 2 3 4 ::: 2663
#pragma line 85 "/usr/include/stdio.h" 3 4 ::: 2664
#pragma line 97 "/usr/include/stdio.h" 3 4 ::: 2669
#pragma line 1 "/usr/include/bits/stdio_lim.h" 1 3 4 ::: 2712
#pragma line 139 "/usr/include/stdio.h" 2 3 4 ::: 2730
#pragma line 166 "/usr/include/stdio.h" 3 4 ::: 2749
#pragma line 184 "/usr/include/stdio.h" 3 4 ::: 2756
#pragma line 244 "/usr/include/stdio.h" 3 4 ::: 2802
#pragma line 279 "/usr/include/stdio.h" 3 4 ::: 2816
#pragma line 301 "/usr/include/stdio.h" 3 4 ::: 2819
#pragma line 395 "/usr/include/stdio.h" 3 4 ::: 2883
#pragma line 437 "/usr/include/stdio.h" 3 4 ::: 2898
#pragma line 586 "/usr/include/stdio.h" 3 4 ::: 3003
#pragma line 632 "/usr/include/stdio.h" 3 4 ::: 3036
#pragma line 695 "/usr/include/stdio.h" 3 4 ::: 3085
#pragma line 726 "/usr/include/stdio.h" 3 4 ::: 3096
#pragma line 1 "/usr/include/bits/sys_errlist.h" 1 3 4 ::: 3126
#pragma line 755 "/usr/include/stdio.h" 2 3 4 ::: 3155
#pragma line 811 "/usr/include/stdio.h" 3 4 ::: 3188
#pragma line 832 "/usr/include/stdio.h" 3 4 ::: 3200
#pragma line 8 "./black_scholes2.h" 2 ::: 3203
#pragma line 1 "/usr/include/stdlib.h" 1 3 4 ::: 3204
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3238
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3263
#pragma line 34 "/usr/include/stdlib.h" 2 3 4 ::: 3266
#pragma line 97 "/usr/include/stdlib.h" 3 4 ::: 3267
#pragma line 128 "/usr/include/stdlib.h" 3 4 ::: 3282
#pragma line 183 "/usr/include/stdlib.h" 3 4 ::: 3323
#pragma line 276 "/usr/include/stdlib.h" 3 4 ::: 3359
#pragma line 426 "/usr/include/stdlib.h" 3 4 ::: 3403
#pragma line 1 "/usr/include/sys/types.h" 1 3 4 ::: 3417
#pragma line 35 "/usr/include/sys/types.h" 3 4 ::: 3440
#pragma line 62 "/usr/include/sys/types.h" 3 4 ::: 3457
#pragma line 100 "/usr/include/sys/types.h" 3 4 ::: 3485
#pragma line 133 "/usr/include/sys/types.h" 3 4 ::: 3510
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 3511
#pragma line 76 "/usr/include/time.h" 3 4 ::: 3534
#pragma line 92 "/usr/include/time.h" 3 4 ::: 3537
#pragma line 104 "/usr/include/time.h" 3 4 ::: 3540
#pragma line 134 "/usr/include/sys/types.h" 2 3 4 ::: 3543
#pragma line 147 "/usr/include/sys/types.h" 3 4 ::: 3544
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3545
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3570
#pragma line 148 "/usr/include/sys/types.h" 2 3 4 ::: 3573
#pragma line 187 "/usr/include/sys/types.h" 3 4 ::: 3583
#pragma line 1 "/usr/include/endian.h" 1 3 4 ::: 3615
#pragma line 1 "/usr/include/bits/endian.h" 1 3 4 ::: 3653
#pragma line 38 "/usr/include/endian.h" 2 3 4 ::: 3655
#pragma line 218 "/usr/include/sys/types.h" 2 3 4 ::: 3659
#pragma line 1 "/usr/include/sys/select.h" 1 3 4 ::: 3663
#pragma line 1 "/usr/include/bits/select.h" 1 3 4 ::: 3695
#pragma line 32 "/usr/include/sys/select.h" 2 3 4 ::: 3721
#pragma line 1 "/usr/include/bits/sigset.h" 1 3 4 ::: 3725
#pragma line 35 "/usr/include/sys/select.h" 2 3 4 ::: 3766
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 3777
#pragma line 119 "/usr/include/time.h" 3 4 ::: 3800
#pragma line 45 "/usr/include/sys/select.h" 2 3 4 ::: 3808
#pragma line 1 "/usr/include/bits/time.h" 1 3 4 ::: 3810
#pragma line 67 "/usr/include/bits/time.h" 3 4 ::: 3833
#pragma line 47 "/usr/include/sys/select.h" 2 3 4 ::: 3841
#pragma line 101 "/usr/include/sys/select.h" 3 4 ::: 3888
#pragma line 221 "/usr/include/sys/types.h" 2 3 4 ::: 3914
#pragma line 1 "/usr/include/sys/sysmacros.h" 1 3 4 ::: 3918
#pragma line 224 "/usr/include/sys/types.h" 2 3 4 ::: 3982
#pragma line 268 "/usr/include/sys/types.h" 3 4 ::: 4003
#pragma line 1 "/usr/include/bits/pthreadtypes.h" 1 3 4 ::: 4007
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 4031
#pragma line 24 "/usr/include/bits/pthreadtypes.h" 2 3 4 ::: 4033
#pragma line 48 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 4034
#pragma line 74 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 4053
#pragma line 101 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 4072
#pragma line 187 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 4141
#pragma line 271 "/usr/include/sys/types.h" 2 3 4 ::: 4172
#pragma line 439 "/usr/include/stdlib.h" 2 3 4 ::: 4173
#pragma line 588 "/usr/include/stdlib.h" 3 4 ::: 4315
#pragma line 1 "/usr/include/alloca.h" 1 3 4 ::: 4341
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 4367
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 4392
#pragma line 26 "/usr/include/alloca.h" 2 3 4 ::: 4395
#pragma line 613 "/usr/include/stdlib.h" 2 3 4 ::: 4404
#pragma line 659 "/usr/include/stdlib.h" 3 4 ::: 4439
#pragma line 724 "/usr/include/stdlib.h" 3 4 ::: 4491
#pragma line 751 "/usr/include/stdlib.h" 3 4 ::: 4507
#pragma line 796 "/usr/include/stdlib.h" 3 4 ::: 4544
#pragma line 815 "/usr/include/stdlib.h" 3 4 ::: 4552
#pragma line 922 "/usr/include/stdlib.h" 3 4 ::: 4637
#pragma line 958 "/usr/include/stdlib.h" 3 4 ::: 4643
#pragma line 9 "./black_scholes2.h" 2 ::: 4653
#pragma line 2 "black_scholes2.c" 2 ::: 4681
#pragma line 1 "./gaussian.h" 1 ::: 4682
#pragma line 3 "black_scholes2.c" 2 ::: 4716
#pragma line 1 "/usr/include/assert.h" 1 3 4 ::: 4718
#pragma line 44 "/usr/include/assert.h" 3 4 ::: 4740
#pragma line 67 "/usr/include/assert.h" 3 4 ::: 4745
#pragma line 101 "/usr/include/assert.h" 3 4 ::: 4762
#pragma line 5 "black_scholes2.c" 2 ::: 4768
