#pragma line 1 "black_scholes2.c" ::: -10
#pragma line 1 "black_scholes2.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 149 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 2
#pragma line 278 "/opt/xilinx/Vivado_HLS/2014.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 55
#pragma line 8 "<command line>" 2 ::: 181
#pragma line 1 "<built-in>" 2 ::: 182
#pragma line 1 "black_scholes2.c" 2 ::: 183
#pragma line 1 "./black_scholes2.h" 1 ::: 184
#pragma line 1 "/usr/include/math.h" 1 3 4 ::: 188
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 217
#pragma line 115 "/usr/include/features.h" 3 4 ::: 310
#pragma line 139 "/usr/include/features.h" 3 4 ::: 327
#pragma line 169 "/usr/include/features.h" 3 4 ::: 337
#pragma line 179 "/usr/include/features.h" 3 4 ::: 340
#pragma line 294 "/usr/include/features.h" 3 4 ::: 352
#pragma line 1 "/usr/include/sys/cdefs.h" 1 3 4 ::: 389
#pragma line 72 "/usr/include/sys/cdefs.h" 3 4 ::: 435
#pragma line 98 "/usr/include/sys/cdefs.h" 3 4 ::: 453
#pragma line 111 "/usr/include/sys/cdefs.h" 3 4 ::: 459
#pragma line 123 "/usr/include/sys/cdefs.h" 3 4 ::: 463
#pragma line 155 "/usr/include/sys/cdefs.h" 3 4 ::: 481
#pragma line 178 "/usr/include/sys/cdefs.h" 3 4 ::: 491
#pragma line 222 "/usr/include/sys/cdefs.h" 3 4 ::: 528
#pragma line 275 "/usr/include/sys/cdefs.h" 3 4 ::: 569
#pragma line 313 "/usr/include/sys/cdefs.h" 3 4 ::: 593
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 594
#pragma line 314 "/usr/include/sys/cdefs.h" 2 3 4 ::: 596
#pragma line 330 "/usr/include/features.h" 2 3 4 ::: 597
#pragma line 1 "/usr/include/gnu/stubs.h" 1 3 4 ::: 621
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 626
#pragma line 5 "/usr/include/gnu/stubs.h" 2 3 4 ::: 628
#pragma line 1 "/usr/include/gnu/stubs-64.h" 1 3 4 ::: 633
#pragma line 10 "/usr/include/gnu/stubs.h" 2 3 4 ::: 638
#pragma line 353 "/usr/include/features.h" 2 3 4 ::: 639
#pragma line 29 "/usr/include/math.h" 2 3 4 ::: 640
#pragma line 1 "/usr/include/bits/huge_val.h" 1 3 4 ::: 647
#pragma line 35 "/usr/include/math.h" 2 3 4 ::: 674
#pragma line 46 "/usr/include/math.h" 3 4 ::: 675
#pragma line 1 "/usr/include/bits/mathdef.h" 1 3 4 ::: 678
#pragma line 48 "/usr/include/math.h" 2 3 4 ::: 696
#pragma line 71 "/usr/include/math.h" 3 4 ::: 702
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 703
#pragma line 88 "/usr/include/bits/mathcalls.h" 3 4 ::: 781
#pragma line 128 "/usr/include/bits/mathcalls.h" 3 4 ::: 811
#pragma line 150 "/usr/include/bits/mathcalls.h" 3 4 ::: 820
#pragma line 230 "/usr/include/bits/mathcalls.h" 3 4 ::: 890
#pragma line 264 "/usr/include/bits/mathcalls.h" 3 4 ::: 914
#pragma line 363 "/usr/include/bits/mathcalls.h" 3 4 ::: 949
#pragma line 72 "/usr/include/math.h" 2 3 4 ::: 952
#pragma line 94 "/usr/include/math.h" 3 4 ::: 963
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 964
#pragma line 88 "/usr/include/bits/mathcalls.h" 3 4 ::: 1042
#pragma line 128 "/usr/include/bits/mathcalls.h" 3 4 ::: 1072
#pragma line 150 "/usr/include/bits/mathcalls.h" 3 4 ::: 1081
#pragma line 230 "/usr/include/bits/mathcalls.h" 3 4 ::: 1151
#pragma line 264 "/usr/include/bits/mathcalls.h" 3 4 ::: 1175
#pragma line 363 "/usr/include/bits/mathcalls.h" 3 4 ::: 1210
#pragma line 95 "/usr/include/math.h" 2 3 4 ::: 1213
#pragma line 141 "/usr/include/math.h" 3 4 ::: 1214
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 1215
#pragma line 88 "/usr/include/bits/mathcalls.h" 3 4 ::: 1293
#pragma line 128 "/usr/include/bits/mathcalls.h" 3 4 ::: 1323
#pragma line 150 "/usr/include/bits/mathcalls.h" 3 4 ::: 1332
#pragma line 230 "/usr/include/bits/mathcalls.h" 3 4 ::: 1402
#pragma line 264 "/usr/include/bits/mathcalls.h" 3 4 ::: 1426
#pragma line 363 "/usr/include/bits/mathcalls.h" 3 4 ::: 1461
#pragma line 142 "/usr/include/math.h" 2 3 4 ::: 1464
#pragma line 156 "/usr/include/math.h" 3 4 ::: 1465
#pragma line 283 "/usr/include/math.h" 3 4 ::: 1472
#pragma line 348 "/usr/include/math.h" 3 4 ::: 1526
#pragma line 365 "/usr/include/math.h" 3 4 ::: 1528
#pragma line 385 "/usr/include/math.h" 3 4 ::: 1532
#pragma line 407 "/usr/include/math.h" 3 4 ::: 1536
#pragma line 5 "./black_scholes2.h" 2 ::: 1538
#pragma line 1 "./util.h" 1 ::: 1539
#pragma line 6 "./black_scholes2.h" 2 ::: 1589
#pragma line 1 "/usr/include/assert.h" 1 3 4 ::: 1590
#pragma line 44 "/usr/include/assert.h" 3 4 ::: 1612
#pragma line 67 "/usr/include/assert.h" 3 4 ::: 1617
#pragma line 101 "/usr/include/assert.h" 3 4 ::: 1634
#pragma line 7 "./black_scholes2.h" 2 ::: 1640
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 1641
#pragma line 34 "/usr/include/stdio.h" 3 4 ::: 1664
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1665
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1706
#pragma line 35 "/usr/include/stdio.h" 2 3 4 ::: 1709
#pragma line 1 "/usr/include/bits/types.h" 1 3 4 ::: 1711
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 1740
#pragma line 29 "/usr/include/bits/types.h" 2 3 4 ::: 1742
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1745
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1770
#pragma line 32 "/usr/include/bits/types.h" 2 3 4 ::: 1773
#pragma line 73 "/usr/include/bits/types.h" 3 4 ::: 1800
#pragma line 129 "/usr/include/bits/types.h" 3 4 ::: 1829
#pragma line 1 "/usr/include/bits/typesizes.h" 1 3 4 ::: 1836
#pragma line 27 "/usr/include/bits/typesizes.h" 3 4 ::: 1855
#pragma line 62 "/usr/include/bits/typesizes.h" 3 4 ::: 1858
#pragma line 135 "/usr/include/bits/types.h" 2 3 4 ::: 1860
#pragma line 37 "/usr/include/stdio.h" 2 3 4 ::: 1922
#pragma line 61 "/usr/include/stdio.h" 3 4 ::: 1933
#pragma line 72 "/usr/include/stdio.h" 3 4 ::: 1936
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 1937
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 1970
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1985
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2010
#pragma line 15 "/usr/include/_G_config.h" 2 3 4 ::: 2017
#pragma line 24 "/usr/include/_G_config.h" 3 4 ::: 2018
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 2019
#pragma line 48 "/usr/include/wchar.h" 3 4 ::: 2042
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2043
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2068
#pragma line 49 "/usr/include/wchar.h" 2 3 4 ::: 2071
#pragma line 1 "/usr/include/bits/wchar.h" 1 3 4 ::: 2073
#pragma line 51 "/usr/include/wchar.h" 2 3 4 ::: 2092
#pragma line 62 "/usr/include/wchar.h" 3 4 ::: 2096
#pragma line 75 "/usr/include/wchar.h" 3 4 ::: 2099
#pragma line 25 "/usr/include/_G_config.h" 2 3 4 ::: 2116
#pragma line 44 "/usr/include/_G_config.h" 3 4 ::: 2128
#pragma line 1 "/usr/include/gconv.h" 1 3 4 ::: 2129
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 2158
#pragma line 48 "/usr/include/wchar.h" 3 4 ::: 2181
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2182
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2207
#pragma line 49 "/usr/include/wchar.h" 2 3 4 ::: 2210
#pragma line 62 "/usr/include/wchar.h" 3 4 ::: 2216
#pragma line 89 "/usr/include/wchar.h" 3 4 ::: 2219
#pragma line 29 "/usr/include/gconv.h" 2 3 4 ::: 2222
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2225
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2250
#pragma line 32 "/usr/include/gconv.h" 2 3 4 ::: 2253
#pragma line 45 "/usr/include/_G_config.h" 2 3 4 ::: 2400
#pragma line 84 "/usr/include/_G_config.h" 3 4 ::: 2420
#pragma line 33 "/usr/include/libio.h" 2 3 4 ::: 2427
#pragma line 51 "/usr/include/libio.h" 3 4 ::: 2429
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 2433
#pragma line 54 "/usr/include/libio.h" 2 3 4 ::: 2482
#pragma line 74 "/usr/include/libio.h" 3 4 ::: 2483
#pragma line 114 "/usr/include/libio.h" 3 4 ::: 2485
#pragma line 147 "/usr/include/libio.h" 3 4 ::: 2491
#pragma line 167 "/usr/include/libio.h" 3 4 ::: 2493
#pragma line 200 "/usr/include/libio.h" 3 4 ::: 2517
#pragma line 268 "/usr/include/libio.h" 3 4 ::: 2528
#pragma line 316 "/usr/include/libio.h" 3 4 ::: 2569
#pragma line 325 "/usr/include/libio.h" 3 4 ::: 2571
#pragma line 357 "/usr/include/libio.h" 3 4 ::: 2593
#pragma line 413 "/usr/include/libio.h" 3 4 ::: 2619
#pragma line 451 "/usr/include/libio.h" 3 4 ::: 2626
#pragma line 481 "/usr/include/libio.h" 3 4 ::: 2641
#pragma line 73 "/usr/include/stdio.h" 2 3 4 ::: 2653
#pragma line 85 "/usr/include/stdio.h" 3 4 ::: 2654
#pragma line 97 "/usr/include/stdio.h" 3 4 ::: 2659
#pragma line 1 "/usr/include/bits/stdio_lim.h" 1 3 4 ::: 2702
#pragma line 139 "/usr/include/stdio.h" 2 3 4 ::: 2720
#pragma line 166 "/usr/include/stdio.h" 3 4 ::: 2739
#pragma line 184 "/usr/include/stdio.h" 3 4 ::: 2746
#pragma line 244 "/usr/include/stdio.h" 3 4 ::: 2792
#pragma line 279 "/usr/include/stdio.h" 3 4 ::: 2806
#pragma line 301 "/usr/include/stdio.h" 3 4 ::: 2809
#pragma line 395 "/usr/include/stdio.h" 3 4 ::: 2873
#pragma line 437 "/usr/include/stdio.h" 3 4 ::: 2888
#pragma line 586 "/usr/include/stdio.h" 3 4 ::: 2993
#pragma line 632 "/usr/include/stdio.h" 3 4 ::: 3026
#pragma line 695 "/usr/include/stdio.h" 3 4 ::: 3075
#pragma line 726 "/usr/include/stdio.h" 3 4 ::: 3086
#pragma line 1 "/usr/include/bits/sys_errlist.h" 1 3 4 ::: 3116
#pragma line 755 "/usr/include/stdio.h" 2 3 4 ::: 3145
#pragma line 811 "/usr/include/stdio.h" 3 4 ::: 3178
#pragma line 832 "/usr/include/stdio.h" 3 4 ::: 3190
#pragma line 8 "./black_scholes2.h" 2 ::: 3193
#pragma line 1 "/usr/include/stdlib.h" 1 3 4 ::: 3194
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3228
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3253
#pragma line 34 "/usr/include/stdlib.h" 2 3 4 ::: 3256
#pragma line 97 "/usr/include/stdlib.h" 3 4 ::: 3257
#pragma line 128 "/usr/include/stdlib.h" 3 4 ::: 3272
#pragma line 183 "/usr/include/stdlib.h" 3 4 ::: 3313
#pragma line 276 "/usr/include/stdlib.h" 3 4 ::: 3349
#pragma line 426 "/usr/include/stdlib.h" 3 4 ::: 3393
#pragma line 1 "/usr/include/sys/types.h" 1 3 4 ::: 3407
#pragma line 35 "/usr/include/sys/types.h" 3 4 ::: 3430
#pragma line 62 "/usr/include/sys/types.h" 3 4 ::: 3447
#pragma line 100 "/usr/include/sys/types.h" 3 4 ::: 3475
#pragma line 133 "/usr/include/sys/types.h" 3 4 ::: 3500
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 3501
#pragma line 76 "/usr/include/time.h" 3 4 ::: 3524
#pragma line 92 "/usr/include/time.h" 3 4 ::: 3527
#pragma line 104 "/usr/include/time.h" 3 4 ::: 3530
#pragma line 134 "/usr/include/sys/types.h" 2 3 4 ::: 3533
#pragma line 147 "/usr/include/sys/types.h" 3 4 ::: 3534
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3535
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3560
#pragma line 148 "/usr/include/sys/types.h" 2 3 4 ::: 3563
#pragma line 187 "/usr/include/sys/types.h" 3 4 ::: 3573
#pragma line 1 "/usr/include/endian.h" 1 3 4 ::: 3605
#pragma line 1 "/usr/include/bits/endian.h" 1 3 4 ::: 3643
#pragma line 38 "/usr/include/endian.h" 2 3 4 ::: 3645
#pragma line 218 "/usr/include/sys/types.h" 2 3 4 ::: 3649
#pragma line 1 "/usr/include/sys/select.h" 1 3 4 ::: 3653
#pragma line 1 "/usr/include/bits/select.h" 1 3 4 ::: 3685
#pragma line 32 "/usr/include/sys/select.h" 2 3 4 ::: 3711
#pragma line 1 "/usr/include/bits/sigset.h" 1 3 4 ::: 3715
#pragma line 35 "/usr/include/sys/select.h" 2 3 4 ::: 3756
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 3767
#pragma line 119 "/usr/include/time.h" 3 4 ::: 3790
#pragma line 45 "/usr/include/sys/select.h" 2 3 4 ::: 3798
#pragma line 1 "/usr/include/bits/time.h" 1 3 4 ::: 3800
#pragma line 67 "/usr/include/bits/time.h" 3 4 ::: 3823
#pragma line 47 "/usr/include/sys/select.h" 2 3 4 ::: 3831
#pragma line 101 "/usr/include/sys/select.h" 3 4 ::: 3878
#pragma line 221 "/usr/include/sys/types.h" 2 3 4 ::: 3904
#pragma line 1 "/usr/include/sys/sysmacros.h" 1 3 4 ::: 3908
#pragma line 224 "/usr/include/sys/types.h" 2 3 4 ::: 3972
#pragma line 268 "/usr/include/sys/types.h" 3 4 ::: 3993
#pragma line 1 "/usr/include/bits/pthreadtypes.h" 1 3 4 ::: 3997
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 4021
#pragma line 24 "/usr/include/bits/pthreadtypes.h" 2 3 4 ::: 4023
#pragma line 48 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 4024
#pragma line 74 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 4043
#pragma line 101 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 4062
#pragma line 187 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 4131
#pragma line 271 "/usr/include/sys/types.h" 2 3 4 ::: 4162
#pragma line 439 "/usr/include/stdlib.h" 2 3 4 ::: 4163
#pragma line 588 "/usr/include/stdlib.h" 3 4 ::: 4305
#pragma line 1 "/usr/include/alloca.h" 1 3 4 ::: 4331
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 4357
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 4382
#pragma line 26 "/usr/include/alloca.h" 2 3 4 ::: 4385
#pragma line 613 "/usr/include/stdlib.h" 2 3 4 ::: 4394
#pragma line 659 "/usr/include/stdlib.h" 3 4 ::: 4429
#pragma line 724 "/usr/include/stdlib.h" 3 4 ::: 4481
#pragma line 751 "/usr/include/stdlib.h" 3 4 ::: 4497
#pragma line 796 "/usr/include/stdlib.h" 3 4 ::: 4534
#pragma line 815 "/usr/include/stdlib.h" 3 4 ::: 4542
#pragma line 922 "/usr/include/stdlib.h" 3 4 ::: 4627
#pragma line 958 "/usr/include/stdlib.h" 3 4 ::: 4633
#pragma line 9 "./black_scholes2.h" 2 ::: 4643
#pragma line 2 "black_scholes2.c" 2 ::: 4671
#pragma line 1 "./gaussian.h" 1 ::: 4672
#pragma line 3 "black_scholes2.c" 2 ::: 4706
#pragma line 1 "/usr/include/assert.h" 1 3 4 ::: 4708
#pragma line 44 "/usr/include/assert.h" 3 4 ::: 4730
#pragma line 67 "/usr/include/assert.h" 3 4 ::: 4735
#pragma line 101 "/usr/include/assert.h" 3 4 ::: 4752
#pragma line 5 "black_scholes2.c" 2 ::: 4758
