#pragma line 1 "black_scholes2_loop.c" ::: -10
#pragma line 1 "black_scholes2_loop.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 149 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 2
#pragma line 278 "/opt/xilinx/Vivado_HLS/2014.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 55
#pragma line 8 "<command line>" 2 ::: 181
#pragma line 1 "<built-in>" 2 ::: 182
#pragma line 1 "black_scholes2_loop.c" 2 ::: 183
#pragma line 1 "/usr/include/assert.h" 1 3 4 ::: 186
#pragma line 36 "/usr/include/assert.h" 3 4 ::: 208
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 209
#pragma line 115 "/usr/include/features.h" 3 4 ::: 302
#pragma line 139 "/usr/include/features.h" 3 4 ::: 319
#pragma line 169 "/usr/include/features.h" 3 4 ::: 329
#pragma line 179 "/usr/include/features.h" 3 4 ::: 332
#pragma line 294 "/usr/include/features.h" 3 4 ::: 344
#pragma line 1 "/usr/include/sys/cdefs.h" 1 3 4 ::: 381
#pragma line 72 "/usr/include/sys/cdefs.h" 3 4 ::: 427
#pragma line 98 "/usr/include/sys/cdefs.h" 3 4 ::: 445
#pragma line 111 "/usr/include/sys/cdefs.h" 3 4 ::: 451
#pragma line 123 "/usr/include/sys/cdefs.h" 3 4 ::: 455
#pragma line 155 "/usr/include/sys/cdefs.h" 3 4 ::: 473
#pragma line 178 "/usr/include/sys/cdefs.h" 3 4 ::: 483
#pragma line 222 "/usr/include/sys/cdefs.h" 3 4 ::: 520
#pragma line 275 "/usr/include/sys/cdefs.h" 3 4 ::: 561
#pragma line 313 "/usr/include/sys/cdefs.h" 3 4 ::: 585
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 586
#pragma line 314 "/usr/include/sys/cdefs.h" 2 3 4 ::: 588
#pragma line 330 "/usr/include/features.h" 2 3 4 ::: 589
#pragma line 1 "/usr/include/gnu/stubs.h" 1 3 4 ::: 613
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 618
#pragma line 5 "/usr/include/gnu/stubs.h" 2 3 4 ::: 620
#pragma line 1 "/usr/include/gnu/stubs-64.h" 1 3 4 ::: 625
#pragma line 10 "/usr/include/gnu/stubs.h" 2 3 4 ::: 630
#pragma line 353 "/usr/include/features.h" 2 3 4 ::: 631
#pragma line 37 "/usr/include/assert.h" 2 3 4 ::: 632
#pragma line 67 "/usr/include/assert.h" 3 4 ::: 644
#pragma line 101 "/usr/include/assert.h" 3 4 ::: 661
#pragma line 4 "black_scholes2_loop.c" 2 ::: 667
#pragma line 1 "/usr/include/math.h" 1 3 4 ::: 668
#pragma line 32 "/usr/include/math.h" 3 4 ::: 692
#pragma line 1 "/usr/include/bits/huge_val.h" 1 3 4 ::: 696
#pragma line 35 "/usr/include/math.h" 2 3 4 ::: 723
#pragma line 46 "/usr/include/math.h" 3 4 ::: 724
#pragma line 1 "/usr/include/bits/mathdef.h" 1 3 4 ::: 727
#pragma line 48 "/usr/include/math.h" 2 3 4 ::: 745
#pragma line 71 "/usr/include/math.h" 3 4 ::: 751
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 752
#pragma line 88 "/usr/include/bits/mathcalls.h" 3 4 ::: 830
#pragma line 128 "/usr/include/bits/mathcalls.h" 3 4 ::: 860
#pragma line 150 "/usr/include/bits/mathcalls.h" 3 4 ::: 869
#pragma line 230 "/usr/include/bits/mathcalls.h" 3 4 ::: 939
#pragma line 264 "/usr/include/bits/mathcalls.h" 3 4 ::: 963
#pragma line 363 "/usr/include/bits/mathcalls.h" 3 4 ::: 998
#pragma line 72 "/usr/include/math.h" 2 3 4 ::: 1001
#pragma line 94 "/usr/include/math.h" 3 4 ::: 1012
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 1013
#pragma line 88 "/usr/include/bits/mathcalls.h" 3 4 ::: 1091
#pragma line 128 "/usr/include/bits/mathcalls.h" 3 4 ::: 1121
#pragma line 150 "/usr/include/bits/mathcalls.h" 3 4 ::: 1130
#pragma line 230 "/usr/include/bits/mathcalls.h" 3 4 ::: 1200
#pragma line 264 "/usr/include/bits/mathcalls.h" 3 4 ::: 1224
#pragma line 363 "/usr/include/bits/mathcalls.h" 3 4 ::: 1259
#pragma line 95 "/usr/include/math.h" 2 3 4 ::: 1262
#pragma line 141 "/usr/include/math.h" 3 4 ::: 1263
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 1264
#pragma line 88 "/usr/include/bits/mathcalls.h" 3 4 ::: 1342
#pragma line 128 "/usr/include/bits/mathcalls.h" 3 4 ::: 1372
#pragma line 150 "/usr/include/bits/mathcalls.h" 3 4 ::: 1381
#pragma line 230 "/usr/include/bits/mathcalls.h" 3 4 ::: 1451
#pragma line 264 "/usr/include/bits/mathcalls.h" 3 4 ::: 1475
#pragma line 363 "/usr/include/bits/mathcalls.h" 3 4 ::: 1510
#pragma line 142 "/usr/include/math.h" 2 3 4 ::: 1513
#pragma line 156 "/usr/include/math.h" 3 4 ::: 1514
#pragma line 283 "/usr/include/math.h" 3 4 ::: 1521
#pragma line 348 "/usr/include/math.h" 3 4 ::: 1575
#pragma line 365 "/usr/include/math.h" 3 4 ::: 1577
#pragma line 385 "/usr/include/math.h" 3 4 ::: 1581
#pragma line 407 "/usr/include/math.h" 3 4 ::: 1585
#pragma line 5 "black_scholes2_loop.c" 2 ::: 1587
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 1588
#pragma line 34 "/usr/include/stdio.h" 3 4 ::: 1611
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1612
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1653
#pragma line 35 "/usr/include/stdio.h" 2 3 4 ::: 1656
#pragma line 1 "/usr/include/bits/types.h" 1 3 4 ::: 1658
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 1687
#pragma line 29 "/usr/include/bits/types.h" 2 3 4 ::: 1689
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1692
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1717
#pragma line 32 "/usr/include/bits/types.h" 2 3 4 ::: 1720
#pragma line 73 "/usr/include/bits/types.h" 3 4 ::: 1747
#pragma line 129 "/usr/include/bits/types.h" 3 4 ::: 1776
#pragma line 1 "/usr/include/bits/typesizes.h" 1 3 4 ::: 1783
#pragma line 27 "/usr/include/bits/typesizes.h" 3 4 ::: 1802
#pragma line 62 "/usr/include/bits/typesizes.h" 3 4 ::: 1805
#pragma line 135 "/usr/include/bits/types.h" 2 3 4 ::: 1807
#pragma line 37 "/usr/include/stdio.h" 2 3 4 ::: 1869
#pragma line 61 "/usr/include/stdio.h" 3 4 ::: 1880
#pragma line 72 "/usr/include/stdio.h" 3 4 ::: 1883
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 1884
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 1917
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1932
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1957
#pragma line 15 "/usr/include/_G_config.h" 2 3 4 ::: 1964
#pragma line 24 "/usr/include/_G_config.h" 3 4 ::: 1965
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 1966
#pragma line 48 "/usr/include/wchar.h" 3 4 ::: 1989
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1990
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2015
#pragma line 49 "/usr/include/wchar.h" 2 3 4 ::: 2018
#pragma line 1 "/usr/include/bits/wchar.h" 1 3 4 ::: 2020
#pragma line 51 "/usr/include/wchar.h" 2 3 4 ::: 2039
#pragma line 62 "/usr/include/wchar.h" 3 4 ::: 2043
#pragma line 75 "/usr/include/wchar.h" 3 4 ::: 2046
#pragma line 25 "/usr/include/_G_config.h" 2 3 4 ::: 2063
#pragma line 44 "/usr/include/_G_config.h" 3 4 ::: 2075
#pragma line 1 "/usr/include/gconv.h" 1 3 4 ::: 2076
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 2105
#pragma line 48 "/usr/include/wchar.h" 3 4 ::: 2128
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2129
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2154
#pragma line 49 "/usr/include/wchar.h" 2 3 4 ::: 2157
#pragma line 62 "/usr/include/wchar.h" 3 4 ::: 2163
#pragma line 89 "/usr/include/wchar.h" 3 4 ::: 2166
#pragma line 29 "/usr/include/gconv.h" 2 3 4 ::: 2169
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2172
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2197
#pragma line 32 "/usr/include/gconv.h" 2 3 4 ::: 2200
#pragma line 45 "/usr/include/_G_config.h" 2 3 4 ::: 2347
#pragma line 84 "/usr/include/_G_config.h" 3 4 ::: 2367
#pragma line 33 "/usr/include/libio.h" 2 3 4 ::: 2374
#pragma line 51 "/usr/include/libio.h" 3 4 ::: 2376
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 2380
#pragma line 54 "/usr/include/libio.h" 2 3 4 ::: 2429
#pragma line 74 "/usr/include/libio.h" 3 4 ::: 2430
#pragma line 114 "/usr/include/libio.h" 3 4 ::: 2432
#pragma line 147 "/usr/include/libio.h" 3 4 ::: 2438
#pragma line 167 "/usr/include/libio.h" 3 4 ::: 2440
#pragma line 200 "/usr/include/libio.h" 3 4 ::: 2464
#pragma line 268 "/usr/include/libio.h" 3 4 ::: 2475
#pragma line 316 "/usr/include/libio.h" 3 4 ::: 2516
#pragma line 325 "/usr/include/libio.h" 3 4 ::: 2518
#pragma line 357 "/usr/include/libio.h" 3 4 ::: 2540
#pragma line 413 "/usr/include/libio.h" 3 4 ::: 2566
#pragma line 451 "/usr/include/libio.h" 3 4 ::: 2573
#pragma line 481 "/usr/include/libio.h" 3 4 ::: 2588
#pragma line 73 "/usr/include/stdio.h" 2 3 4 ::: 2600
#pragma line 85 "/usr/include/stdio.h" 3 4 ::: 2601
#pragma line 97 "/usr/include/stdio.h" 3 4 ::: 2606
#pragma line 1 "/usr/include/bits/stdio_lim.h" 1 3 4 ::: 2649
#pragma line 139 "/usr/include/stdio.h" 2 3 4 ::: 2667
#pragma line 166 "/usr/include/stdio.h" 3 4 ::: 2686
#pragma line 184 "/usr/include/stdio.h" 3 4 ::: 2693
#pragma line 244 "/usr/include/stdio.h" 3 4 ::: 2739
#pragma line 279 "/usr/include/stdio.h" 3 4 ::: 2753
#pragma line 301 "/usr/include/stdio.h" 3 4 ::: 2756
#pragma line 395 "/usr/include/stdio.h" 3 4 ::: 2820
#pragma line 437 "/usr/include/stdio.h" 3 4 ::: 2835
#pragma line 586 "/usr/include/stdio.h" 3 4 ::: 2940
#pragma line 632 "/usr/include/stdio.h" 3 4 ::: 2973
#pragma line 695 "/usr/include/stdio.h" 3 4 ::: 3022
#pragma line 726 "/usr/include/stdio.h" 3 4 ::: 3033
#pragma line 1 "/usr/include/bits/sys_errlist.h" 1 3 4 ::: 3063
#pragma line 755 "/usr/include/stdio.h" 2 3 4 ::: 3092
#pragma line 811 "/usr/include/stdio.h" 3 4 ::: 3125
#pragma line 832 "/usr/include/stdio.h" 3 4 ::: 3137
#pragma line 6 "black_scholes2_loop.c" 2 ::: 3140
#pragma line 1 "/usr/include/stdlib.h" 1 3 4 ::: 3141
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3175
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3200
#pragma line 34 "/usr/include/stdlib.h" 2 3 4 ::: 3203
#pragma line 97 "/usr/include/stdlib.h" 3 4 ::: 3204
#pragma line 128 "/usr/include/stdlib.h" 3 4 ::: 3219
#pragma line 183 "/usr/include/stdlib.h" 3 4 ::: 3260
#pragma line 276 "/usr/include/stdlib.h" 3 4 ::: 3296
#pragma line 426 "/usr/include/stdlib.h" 3 4 ::: 3340
#pragma line 1 "/usr/include/sys/types.h" 1 3 4 ::: 3354
#pragma line 35 "/usr/include/sys/types.h" 3 4 ::: 3377
#pragma line 62 "/usr/include/sys/types.h" 3 4 ::: 3394
#pragma line 100 "/usr/include/sys/types.h" 3 4 ::: 3422
#pragma line 133 "/usr/include/sys/types.h" 3 4 ::: 3447
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 3448
#pragma line 76 "/usr/include/time.h" 3 4 ::: 3471
#pragma line 92 "/usr/include/time.h" 3 4 ::: 3474
#pragma line 104 "/usr/include/time.h" 3 4 ::: 3477
#pragma line 134 "/usr/include/sys/types.h" 2 3 4 ::: 3480
#pragma line 147 "/usr/include/sys/types.h" 3 4 ::: 3481
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3482
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3507
#pragma line 148 "/usr/include/sys/types.h" 2 3 4 ::: 3510
#pragma line 187 "/usr/include/sys/types.h" 3 4 ::: 3520
#pragma line 1 "/usr/include/endian.h" 1 3 4 ::: 3552
#pragma line 1 "/usr/include/bits/endian.h" 1 3 4 ::: 3590
#pragma line 38 "/usr/include/endian.h" 2 3 4 ::: 3592
#pragma line 218 "/usr/include/sys/types.h" 2 3 4 ::: 3596
#pragma line 1 "/usr/include/sys/select.h" 1 3 4 ::: 3600
#pragma line 1 "/usr/include/bits/select.h" 1 3 4 ::: 3632
#pragma line 32 "/usr/include/sys/select.h" 2 3 4 ::: 3658
#pragma line 1 "/usr/include/bits/sigset.h" 1 3 4 ::: 3662
#pragma line 35 "/usr/include/sys/select.h" 2 3 4 ::: 3703
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 3714
#pragma line 119 "/usr/include/time.h" 3 4 ::: 3737
#pragma line 45 "/usr/include/sys/select.h" 2 3 4 ::: 3745
#pragma line 1 "/usr/include/bits/time.h" 1 3 4 ::: 3747
#pragma line 67 "/usr/include/bits/time.h" 3 4 ::: 3770
#pragma line 47 "/usr/include/sys/select.h" 2 3 4 ::: 3778
#pragma line 101 "/usr/include/sys/select.h" 3 4 ::: 3825
#pragma line 221 "/usr/include/sys/types.h" 2 3 4 ::: 3851
#pragma line 1 "/usr/include/sys/sysmacros.h" 1 3 4 ::: 3855
#pragma line 224 "/usr/include/sys/types.h" 2 3 4 ::: 3919
#pragma line 268 "/usr/include/sys/types.h" 3 4 ::: 3940
#pragma line 1 "/usr/include/bits/pthreadtypes.h" 1 3 4 ::: 3944
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 3968
#pragma line 24 "/usr/include/bits/pthreadtypes.h" 2 3 4 ::: 3970
#pragma line 48 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 3971
#pragma line 74 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 3990
#pragma line 101 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 4009
#pragma line 187 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 4078
#pragma line 271 "/usr/include/sys/types.h" 2 3 4 ::: 4109
#pragma line 439 "/usr/include/stdlib.h" 2 3 4 ::: 4110
#pragma line 588 "/usr/include/stdlib.h" 3 4 ::: 4252
#pragma line 1 "/usr/include/alloca.h" 1 3 4 ::: 4278
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 4304
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 4329
#pragma line 26 "/usr/include/alloca.h" 2 3 4 ::: 4332
#pragma line 613 "/usr/include/stdlib.h" 2 3 4 ::: 4341
#pragma line 659 "/usr/include/stdlib.h" 3 4 ::: 4376
#pragma line 724 "/usr/include/stdlib.h" 3 4 ::: 4428
#pragma line 751 "/usr/include/stdlib.h" 3 4 ::: 4444
#pragma line 796 "/usr/include/stdlib.h" 3 4 ::: 4481
#pragma line 815 "/usr/include/stdlib.h" 3 4 ::: 4489
#pragma line 922 "/usr/include/stdlib.h" 3 4 ::: 4574
#pragma line 958 "/usr/include/stdlib.h" 3 4 ::: 4580
#pragma line 7 "black_scholes2_loop.c" 2 ::: 4590
