#pragma line 1 "black_scholes.c" ::: -10
#pragma line 1 "black_scholes.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 149 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 2
#pragma line 278 "/opt/xilinx/Vivado_HLS/2014.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 55
#pragma line 8 "<command line>" 2 ::: 181
#pragma line 1 "<built-in>" 2 ::: 182
#pragma line 1 "black_scholes.c" 2 ::: 183
#pragma line 1 "./black_scholes.h" 1 ::: 184
#pragma line 1 "/usr/include/math.h" 1 3 4 ::: 188
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 217
#pragma line 115 "/usr/include/features.h" 3 4 ::: 310
#pragma line 139 "/usr/include/features.h" 3 4 ::: 327
#pragma line 169 "/usr/include/features.h" 3 4 ::: 337
#pragma line 179 "/usr/include/features.h" 3 4 ::: 340
#pragma line 294 "/usr/include/features.h" 3 4 ::: 352
#pragma line 1 "/usr/include/sys/cdefs.h" 1 3 4 ::: 389
#pragma line 72 "/usr/include/sys/cdefs.h" 3 4 ::: 435
#pragma line 98 "/usr/include/sys/cdefs.h" 3 4 ::: 453
#pragma line 111 "/usr/include/sys/cdefs.h" 3 4 ::: 459
#pragma line 123 "/usr/include/sys/cdefs.h" 3 4 ::: 463
#pragma line 155 "/usr/include/sys/cdefs.h" 3 4 ::: 481
#pragma line 178 "/usr/include/sys/cdefs.h" 3 4 ::: 491
#pragma line 222 "/usr/include/sys/cdefs.h" 3 4 ::: 528
#pragma line 275 "/usr/include/sys/cdefs.h" 3 4 ::: 569
#pragma line 313 "/usr/include/sys/cdefs.h" 3 4 ::: 593
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 594
#pragma line 314 "/usr/include/sys/cdefs.h" 2 3 4 ::: 596
#pragma line 330 "/usr/include/features.h" 2 3 4 ::: 597
#pragma line 1 "/usr/include/gnu/stubs.h" 1 3 4 ::: 621
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 626
#pragma line 5 "/usr/include/gnu/stubs.h" 2 3 4 ::: 628
#pragma line 1 "/usr/include/gnu/stubs-64.h" 1 3 4 ::: 633
#pragma line 10 "/usr/include/gnu/stubs.h" 2 3 4 ::: 638
#pragma line 353 "/usr/include/features.h" 2 3 4 ::: 639
#pragma line 29 "/usr/include/math.h" 2 3 4 ::: 640
#pragma line 1 "/usr/include/bits/huge_val.h" 1 3 4 ::: 647
#pragma line 35 "/usr/include/math.h" 2 3 4 ::: 674
#pragma line 46 "/usr/include/math.h" 3 4 ::: 675
#pragma line 1 "/usr/include/bits/mathdef.h" 1 3 4 ::: 678
#pragma line 48 "/usr/include/math.h" 2 3 4 ::: 696
#pragma line 71 "/usr/include/math.h" 3 4 ::: 702
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 703
#pragma line 88 "/usr/include/bits/mathcalls.h" 3 4 ::: 781
#pragma line 128 "/usr/include/bits/mathcalls.h" 3 4 ::: 811
#pragma line 150 "/usr/include/bits/mathcalls.h" 3 4 ::: 820
#pragma line 230 "/usr/include/bits/mathcalls.h" 3 4 ::: 890
#pragma line 264 "/usr/include/bits/mathcalls.h" 3 4 ::: 914
#pragma line 363 "/usr/include/bits/mathcalls.h" 3 4 ::: 949
#pragma line 72 "/usr/include/math.h" 2 3 4 ::: 952
#pragma line 94 "/usr/include/math.h" 3 4 ::: 963
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 964
#pragma line 88 "/usr/include/bits/mathcalls.h" 3 4 ::: 1042
#pragma line 128 "/usr/include/bits/mathcalls.h" 3 4 ::: 1072
#pragma line 150 "/usr/include/bits/mathcalls.h" 3 4 ::: 1081
#pragma line 230 "/usr/include/bits/mathcalls.h" 3 4 ::: 1151
#pragma line 264 "/usr/include/bits/mathcalls.h" 3 4 ::: 1175
#pragma line 363 "/usr/include/bits/mathcalls.h" 3 4 ::: 1210
#pragma line 95 "/usr/include/math.h" 2 3 4 ::: 1213
#pragma line 141 "/usr/include/math.h" 3 4 ::: 1214
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 1215
#pragma line 88 "/usr/include/bits/mathcalls.h" 3 4 ::: 1293
#pragma line 128 "/usr/include/bits/mathcalls.h" 3 4 ::: 1323
#pragma line 150 "/usr/include/bits/mathcalls.h" 3 4 ::: 1332
#pragma line 230 "/usr/include/bits/mathcalls.h" 3 4 ::: 1402
#pragma line 264 "/usr/include/bits/mathcalls.h" 3 4 ::: 1426
#pragma line 363 "/usr/include/bits/mathcalls.h" 3 4 ::: 1461
#pragma line 142 "/usr/include/math.h" 2 3 4 ::: 1464
#pragma line 156 "/usr/include/math.h" 3 4 ::: 1465
#pragma line 283 "/usr/include/math.h" 3 4 ::: 1472
#pragma line 348 "/usr/include/math.h" 3 4 ::: 1526
#pragma line 365 "/usr/include/math.h" 3 4 ::: 1528
#pragma line 385 "/usr/include/math.h" 3 4 ::: 1532
#pragma line 407 "/usr/include/math.h" 3 4 ::: 1536
#pragma line 5 "./black_scholes.h" 2 ::: 1538
#pragma line 2 "black_scholes.c" 2 ::: 1626
#pragma line 1 "./gaussian.h" 1 ::: 1627
#pragma line 1 "./util.h" 1 ::: 1640
#pragma line 13 "./gaussian.h" 2 ::: 1690
#pragma line 3 "black_scholes.c" 2 ::: 1712
#pragma line 1 "/usr/include/assert.h" 1 3 4 ::: 1715
#pragma line 44 "/usr/include/assert.h" 3 4 ::: 1737
#pragma line 67 "/usr/include/assert.h" 3 4 ::: 1742
#pragma line 101 "/usr/include/assert.h" 3 4 ::: 1759
#pragma line 6 "black_scholes.c" 2 ::: 1765
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 1767
#pragma line 34 "/usr/include/stdio.h" 3 4 ::: 1790
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1791
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1832
#pragma line 35 "/usr/include/stdio.h" 2 3 4 ::: 1835
#pragma line 1 "/usr/include/bits/types.h" 1 3 4 ::: 1837
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 1866
#pragma line 29 "/usr/include/bits/types.h" 2 3 4 ::: 1868
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1871
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1896
#pragma line 32 "/usr/include/bits/types.h" 2 3 4 ::: 1899
#pragma line 73 "/usr/include/bits/types.h" 3 4 ::: 1926
#pragma line 129 "/usr/include/bits/types.h" 3 4 ::: 1955
#pragma line 1 "/usr/include/bits/typesizes.h" 1 3 4 ::: 1962
#pragma line 27 "/usr/include/bits/typesizes.h" 3 4 ::: 1981
#pragma line 62 "/usr/include/bits/typesizes.h" 3 4 ::: 1984
#pragma line 135 "/usr/include/bits/types.h" 2 3 4 ::: 1986
#pragma line 37 "/usr/include/stdio.h" 2 3 4 ::: 2048
#pragma line 61 "/usr/include/stdio.h" 3 4 ::: 2059
#pragma line 72 "/usr/include/stdio.h" 3 4 ::: 2062
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 2063
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 2096
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2111
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2136
#pragma line 15 "/usr/include/_G_config.h" 2 3 4 ::: 2143
#pragma line 24 "/usr/include/_G_config.h" 3 4 ::: 2144
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 2145
#pragma line 48 "/usr/include/wchar.h" 3 4 ::: 2168
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2169
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2194
#pragma line 49 "/usr/include/wchar.h" 2 3 4 ::: 2197
#pragma line 1 "/usr/include/bits/wchar.h" 1 3 4 ::: 2199
#pragma line 51 "/usr/include/wchar.h" 2 3 4 ::: 2218
#pragma line 62 "/usr/include/wchar.h" 3 4 ::: 2222
#pragma line 75 "/usr/include/wchar.h" 3 4 ::: 2225
#pragma line 25 "/usr/include/_G_config.h" 2 3 4 ::: 2242
#pragma line 44 "/usr/include/_G_config.h" 3 4 ::: 2254
#pragma line 1 "/usr/include/gconv.h" 1 3 4 ::: 2255
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 2284
#pragma line 48 "/usr/include/wchar.h" 3 4 ::: 2307
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2308
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2333
#pragma line 49 "/usr/include/wchar.h" 2 3 4 ::: 2336
#pragma line 62 "/usr/include/wchar.h" 3 4 ::: 2342
#pragma line 89 "/usr/include/wchar.h" 3 4 ::: 2345
#pragma line 29 "/usr/include/gconv.h" 2 3 4 ::: 2348
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2351
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2376
#pragma line 32 "/usr/include/gconv.h" 2 3 4 ::: 2379
#pragma line 45 "/usr/include/_G_config.h" 2 3 4 ::: 2526
#pragma line 84 "/usr/include/_G_config.h" 3 4 ::: 2546
#pragma line 33 "/usr/include/libio.h" 2 3 4 ::: 2553
#pragma line 51 "/usr/include/libio.h" 3 4 ::: 2555
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 2559
#pragma line 54 "/usr/include/libio.h" 2 3 4 ::: 2608
#pragma line 74 "/usr/include/libio.h" 3 4 ::: 2609
#pragma line 114 "/usr/include/libio.h" 3 4 ::: 2611
#pragma line 147 "/usr/include/libio.h" 3 4 ::: 2617
#pragma line 167 "/usr/include/libio.h" 3 4 ::: 2619
#pragma line 200 "/usr/include/libio.h" 3 4 ::: 2643
#pragma line 268 "/usr/include/libio.h" 3 4 ::: 2654
#pragma line 316 "/usr/include/libio.h" 3 4 ::: 2695
#pragma line 325 "/usr/include/libio.h" 3 4 ::: 2697
#pragma line 357 "/usr/include/libio.h" 3 4 ::: 2719
#pragma line 413 "/usr/include/libio.h" 3 4 ::: 2745
#pragma line 451 "/usr/include/libio.h" 3 4 ::: 2752
#pragma line 481 "/usr/include/libio.h" 3 4 ::: 2767
#pragma line 73 "/usr/include/stdio.h" 2 3 4 ::: 2779
#pragma line 85 "/usr/include/stdio.h" 3 4 ::: 2780
#pragma line 97 "/usr/include/stdio.h" 3 4 ::: 2785
#pragma line 1 "/usr/include/bits/stdio_lim.h" 1 3 4 ::: 2828
#pragma line 139 "/usr/include/stdio.h" 2 3 4 ::: 2846
#pragma line 166 "/usr/include/stdio.h" 3 4 ::: 2865
#pragma line 184 "/usr/include/stdio.h" 3 4 ::: 2872
#pragma line 244 "/usr/include/stdio.h" 3 4 ::: 2918
#pragma line 279 "/usr/include/stdio.h" 3 4 ::: 2932
#pragma line 301 "/usr/include/stdio.h" 3 4 ::: 2935
#pragma line 395 "/usr/include/stdio.h" 3 4 ::: 2999
#pragma line 437 "/usr/include/stdio.h" 3 4 ::: 3014
#pragma line 586 "/usr/include/stdio.h" 3 4 ::: 3119
#pragma line 632 "/usr/include/stdio.h" 3 4 ::: 3152
#pragma line 695 "/usr/include/stdio.h" 3 4 ::: 3201
#pragma line 726 "/usr/include/stdio.h" 3 4 ::: 3212
#pragma line 1 "/usr/include/bits/sys_errlist.h" 1 3 4 ::: 3242
#pragma line 755 "/usr/include/stdio.h" 2 3 4 ::: 3271
#pragma line 811 "/usr/include/stdio.h" 3 4 ::: 3304
#pragma line 832 "/usr/include/stdio.h" 3 4 ::: 3316
#pragma line 8 "black_scholes.c" 2 ::: 3319
#pragma line 1 "/usr/include/stdlib.h" 1 3 4 ::: 3320
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3354
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3379
#pragma line 34 "/usr/include/stdlib.h" 2 3 4 ::: 3382
#pragma line 97 "/usr/include/stdlib.h" 3 4 ::: 3383
#pragma line 128 "/usr/include/stdlib.h" 3 4 ::: 3398
#pragma line 183 "/usr/include/stdlib.h" 3 4 ::: 3439
#pragma line 276 "/usr/include/stdlib.h" 3 4 ::: 3475
#pragma line 426 "/usr/include/stdlib.h" 3 4 ::: 3519
#pragma line 1 "/usr/include/sys/types.h" 1 3 4 ::: 3533
#pragma line 35 "/usr/include/sys/types.h" 3 4 ::: 3556
#pragma line 62 "/usr/include/sys/types.h" 3 4 ::: 3573
#pragma line 100 "/usr/include/sys/types.h" 3 4 ::: 3601
#pragma line 133 "/usr/include/sys/types.h" 3 4 ::: 3626
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 3627
#pragma line 76 "/usr/include/time.h" 3 4 ::: 3650
#pragma line 92 "/usr/include/time.h" 3 4 ::: 3653
#pragma line 104 "/usr/include/time.h" 3 4 ::: 3656
#pragma line 134 "/usr/include/sys/types.h" 2 3 4 ::: 3659
#pragma line 147 "/usr/include/sys/types.h" 3 4 ::: 3660
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3661
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3686
#pragma line 148 "/usr/include/sys/types.h" 2 3 4 ::: 3689
#pragma line 187 "/usr/include/sys/types.h" 3 4 ::: 3699
#pragma line 1 "/usr/include/endian.h" 1 3 4 ::: 3731
#pragma line 1 "/usr/include/bits/endian.h" 1 3 4 ::: 3769
#pragma line 38 "/usr/include/endian.h" 2 3 4 ::: 3771
#pragma line 218 "/usr/include/sys/types.h" 2 3 4 ::: 3775
#pragma line 1 "/usr/include/sys/select.h" 1 3 4 ::: 3779
#pragma line 1 "/usr/include/bits/select.h" 1 3 4 ::: 3811
#pragma line 32 "/usr/include/sys/select.h" 2 3 4 ::: 3837
#pragma line 1 "/usr/include/bits/sigset.h" 1 3 4 ::: 3841
#pragma line 35 "/usr/include/sys/select.h" 2 3 4 ::: 3882
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 3893
#pragma line 119 "/usr/include/time.h" 3 4 ::: 3916
#pragma line 45 "/usr/include/sys/select.h" 2 3 4 ::: 3924
#pragma line 1 "/usr/include/bits/time.h" 1 3 4 ::: 3926
#pragma line 67 "/usr/include/bits/time.h" 3 4 ::: 3949
#pragma line 47 "/usr/include/sys/select.h" 2 3 4 ::: 3957
#pragma line 101 "/usr/include/sys/select.h" 3 4 ::: 4004
#pragma line 221 "/usr/include/sys/types.h" 2 3 4 ::: 4030
#pragma line 1 "/usr/include/sys/sysmacros.h" 1 3 4 ::: 4034
#pragma line 224 "/usr/include/sys/types.h" 2 3 4 ::: 4098
#pragma line 268 "/usr/include/sys/types.h" 3 4 ::: 4119
#pragma line 1 "/usr/include/bits/pthreadtypes.h" 1 3 4 ::: 4123
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 4147
#pragma line 24 "/usr/include/bits/pthreadtypes.h" 2 3 4 ::: 4149
#pragma line 48 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 4150
#pragma line 74 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 4169
#pragma line 101 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 4188
#pragma line 187 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 4257
#pragma line 271 "/usr/include/sys/types.h" 2 3 4 ::: 4288
#pragma line 439 "/usr/include/stdlib.h" 2 3 4 ::: 4289
#pragma line 588 "/usr/include/stdlib.h" 3 4 ::: 4431
#pragma line 1 "/usr/include/alloca.h" 1 3 4 ::: 4457
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 4483
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 4508
#pragma line 26 "/usr/include/alloca.h" 2 3 4 ::: 4511
#pragma line 613 "/usr/include/stdlib.h" 2 3 4 ::: 4520
#pragma line 659 "/usr/include/stdlib.h" 3 4 ::: 4555
#pragma line 724 "/usr/include/stdlib.h" 3 4 ::: 4607
#pragma line 751 "/usr/include/stdlib.h" 3 4 ::: 4623
#pragma line 796 "/usr/include/stdlib.h" 3 4 ::: 4660
#pragma line 815 "/usr/include/stdlib.h" 3 4 ::: 4668
#pragma line 922 "/usr/include/stdlib.h" 3 4 ::: 4753
#pragma line 958 "/usr/include/stdlib.h" 3 4 ::: 4759
#pragma line 9 "black_scholes.c" 2 ::: 4769
