#pragma line 1 "black_scholes.c" ::: 0
#pragma line 1 "black_scholes.c" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 149 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 12
#pragma line 278 "/opt/xilinx/Vivado_HLS/2014.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 65
#pragma line 8 "<command line>" 2 ::: 191
#pragma line 1 "<built-in>" 2 ::: 192
#pragma line 1 "black_scholes.c" 2 ::: 193
#pragma line 1 "./black_scholes.h" 1 ::: 194
#pragma line 1 "/usr/include/math.h" 1 3 4 ::: 198
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 227
#pragma line 115 "/usr/include/features.h" 3 4 ::: 320
#pragma line 139 "/usr/include/features.h" 3 4 ::: 337
#pragma line 169 "/usr/include/features.h" 3 4 ::: 347
#pragma line 179 "/usr/include/features.h" 3 4 ::: 350
#pragma line 294 "/usr/include/features.h" 3 4 ::: 362
#pragma line 1 "/usr/include/sys/cdefs.h" 1 3 4 ::: 399
#pragma line 72 "/usr/include/sys/cdefs.h" 3 4 ::: 445
#pragma line 98 "/usr/include/sys/cdefs.h" 3 4 ::: 463
#pragma line 111 "/usr/include/sys/cdefs.h" 3 4 ::: 469
#pragma line 123 "/usr/include/sys/cdefs.h" 3 4 ::: 473
#pragma line 155 "/usr/include/sys/cdefs.h" 3 4 ::: 491
#pragma line 178 "/usr/include/sys/cdefs.h" 3 4 ::: 501
#pragma line 222 "/usr/include/sys/cdefs.h" 3 4 ::: 538
#pragma line 275 "/usr/include/sys/cdefs.h" 3 4 ::: 579
#pragma line 313 "/usr/include/sys/cdefs.h" 3 4 ::: 603
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 604
#pragma line 314 "/usr/include/sys/cdefs.h" 2 3 4 ::: 606
#pragma line 330 "/usr/include/features.h" 2 3 4 ::: 607
#pragma line 1 "/usr/include/gnu/stubs.h" 1 3 4 ::: 631
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 636
#pragma line 5 "/usr/include/gnu/stubs.h" 2 3 4 ::: 638
#pragma line 1 "/usr/include/gnu/stubs-64.h" 1 3 4 ::: 643
#pragma line 10 "/usr/include/gnu/stubs.h" 2 3 4 ::: 648
#pragma line 353 "/usr/include/features.h" 2 3 4 ::: 649
#pragma line 29 "/usr/include/math.h" 2 3 4 ::: 650
#pragma line 1 "/usr/include/bits/huge_val.h" 1 3 4 ::: 657
#pragma line 35 "/usr/include/math.h" 2 3 4 ::: 684
#pragma line 46 "/usr/include/math.h" 3 4 ::: 685
#pragma line 1 "/usr/include/bits/mathdef.h" 1 3 4 ::: 688
#pragma line 48 "/usr/include/math.h" 2 3 4 ::: 706
#pragma line 71 "/usr/include/math.h" 3 4 ::: 712
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 713
#pragma line 88 "/usr/include/bits/mathcalls.h" 3 4 ::: 791
#pragma line 128 "/usr/include/bits/mathcalls.h" 3 4 ::: 821
#pragma line 150 "/usr/include/bits/mathcalls.h" 3 4 ::: 830
#pragma line 230 "/usr/include/bits/mathcalls.h" 3 4 ::: 900
#pragma line 264 "/usr/include/bits/mathcalls.h" 3 4 ::: 924
#pragma line 363 "/usr/include/bits/mathcalls.h" 3 4 ::: 959
#pragma line 72 "/usr/include/math.h" 2 3 4 ::: 962
#pragma line 94 "/usr/include/math.h" 3 4 ::: 973
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 974
#pragma line 88 "/usr/include/bits/mathcalls.h" 3 4 ::: 1052
#pragma line 128 "/usr/include/bits/mathcalls.h" 3 4 ::: 1082
#pragma line 150 "/usr/include/bits/mathcalls.h" 3 4 ::: 1091
#pragma line 230 "/usr/include/bits/mathcalls.h" 3 4 ::: 1161
#pragma line 264 "/usr/include/bits/mathcalls.h" 3 4 ::: 1185
#pragma line 363 "/usr/include/bits/mathcalls.h" 3 4 ::: 1220
#pragma line 95 "/usr/include/math.h" 2 3 4 ::: 1223
#pragma line 141 "/usr/include/math.h" 3 4 ::: 1224
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 1225
#pragma line 88 "/usr/include/bits/mathcalls.h" 3 4 ::: 1303
#pragma line 128 "/usr/include/bits/mathcalls.h" 3 4 ::: 1333
#pragma line 150 "/usr/include/bits/mathcalls.h" 3 4 ::: 1342
#pragma line 230 "/usr/include/bits/mathcalls.h" 3 4 ::: 1412
#pragma line 264 "/usr/include/bits/mathcalls.h" 3 4 ::: 1436
#pragma line 363 "/usr/include/bits/mathcalls.h" 3 4 ::: 1471
#pragma line 142 "/usr/include/math.h" 2 3 4 ::: 1474
#pragma line 156 "/usr/include/math.h" 3 4 ::: 1475
#pragma line 283 "/usr/include/math.h" 3 4 ::: 1482
#pragma line 348 "/usr/include/math.h" 3 4 ::: 1536
#pragma line 365 "/usr/include/math.h" 3 4 ::: 1538
#pragma line 385 "/usr/include/math.h" 3 4 ::: 1542
#pragma line 407 "/usr/include/math.h" 3 4 ::: 1546
#pragma line 5 "./black_scholes.h" 2 ::: 1548
#pragma line 2 "black_scholes.c" 2 ::: 1636
#pragma line 1 "./gaussian.h" 1 ::: 1637
#pragma line 1 "./util.h" 1 ::: 1650
#pragma line 13 "./gaussian.h" 2 ::: 1700
#pragma line 3 "black_scholes.c" 2 ::: 1722
#pragma line 1 "/usr/include/assert.h" 1 3 4 ::: 1725
#pragma line 44 "/usr/include/assert.h" 3 4 ::: 1747
#pragma line 67 "/usr/include/assert.h" 3 4 ::: 1752
#pragma line 101 "/usr/include/assert.h" 3 4 ::: 1769
#pragma line 6 "black_scholes.c" 2 ::: 1775
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 1777
#pragma line 34 "/usr/include/stdio.h" 3 4 ::: 1800
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1801
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1842
#pragma line 35 "/usr/include/stdio.h" 2 3 4 ::: 1845
#pragma line 1 "/usr/include/bits/types.h" 1 3 4 ::: 1847
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 1876
#pragma line 29 "/usr/include/bits/types.h" 2 3 4 ::: 1878
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1881
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1906
#pragma line 32 "/usr/include/bits/types.h" 2 3 4 ::: 1909
#pragma line 73 "/usr/include/bits/types.h" 3 4 ::: 1936
#pragma line 129 "/usr/include/bits/types.h" 3 4 ::: 1965
#pragma line 1 "/usr/include/bits/typesizes.h" 1 3 4 ::: 1972
#pragma line 27 "/usr/include/bits/typesizes.h" 3 4 ::: 1991
#pragma line 62 "/usr/include/bits/typesizes.h" 3 4 ::: 1994
#pragma line 135 "/usr/include/bits/types.h" 2 3 4 ::: 1996
#pragma line 37 "/usr/include/stdio.h" 2 3 4 ::: 2058
#pragma line 61 "/usr/include/stdio.h" 3 4 ::: 2069
#pragma line 72 "/usr/include/stdio.h" 3 4 ::: 2072
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 2073
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 2106
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2121
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2146
#pragma line 15 "/usr/include/_G_config.h" 2 3 4 ::: 2153
#pragma line 24 "/usr/include/_G_config.h" 3 4 ::: 2154
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 2155
#pragma line 48 "/usr/include/wchar.h" 3 4 ::: 2178
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2179
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2204
#pragma line 49 "/usr/include/wchar.h" 2 3 4 ::: 2207
#pragma line 1 "/usr/include/bits/wchar.h" 1 3 4 ::: 2209
#pragma line 51 "/usr/include/wchar.h" 2 3 4 ::: 2228
#pragma line 62 "/usr/include/wchar.h" 3 4 ::: 2232
#pragma line 75 "/usr/include/wchar.h" 3 4 ::: 2235
#pragma line 25 "/usr/include/_G_config.h" 2 3 4 ::: 2252
#pragma line 44 "/usr/include/_G_config.h" 3 4 ::: 2264
#pragma line 1 "/usr/include/gconv.h" 1 3 4 ::: 2265
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 2294
#pragma line 48 "/usr/include/wchar.h" 3 4 ::: 2317
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2318
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2343
#pragma line 49 "/usr/include/wchar.h" 2 3 4 ::: 2346
#pragma line 62 "/usr/include/wchar.h" 3 4 ::: 2352
#pragma line 89 "/usr/include/wchar.h" 3 4 ::: 2355
#pragma line 29 "/usr/include/gconv.h" 2 3 4 ::: 2358
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2361
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2386
#pragma line 32 "/usr/include/gconv.h" 2 3 4 ::: 2389
#pragma line 45 "/usr/include/_G_config.h" 2 3 4 ::: 2536
#pragma line 84 "/usr/include/_G_config.h" 3 4 ::: 2556
#pragma line 33 "/usr/include/libio.h" 2 3 4 ::: 2563
#pragma line 51 "/usr/include/libio.h" 3 4 ::: 2565
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 2569
#pragma line 54 "/usr/include/libio.h" 2 3 4 ::: 2618
#pragma line 74 "/usr/include/libio.h" 3 4 ::: 2619
#pragma line 114 "/usr/include/libio.h" 3 4 ::: 2621
#pragma line 147 "/usr/include/libio.h" 3 4 ::: 2627
#pragma line 167 "/usr/include/libio.h" 3 4 ::: 2629
#pragma line 200 "/usr/include/libio.h" 3 4 ::: 2653
#pragma line 268 "/usr/include/libio.h" 3 4 ::: 2664
#pragma line 316 "/usr/include/libio.h" 3 4 ::: 2705
#pragma line 325 "/usr/include/libio.h" 3 4 ::: 2707
#pragma line 357 "/usr/include/libio.h" 3 4 ::: 2729
#pragma line 413 "/usr/include/libio.h" 3 4 ::: 2755
#pragma line 451 "/usr/include/libio.h" 3 4 ::: 2762
#pragma line 481 "/usr/include/libio.h" 3 4 ::: 2777
#pragma line 73 "/usr/include/stdio.h" 2 3 4 ::: 2789
#pragma line 85 "/usr/include/stdio.h" 3 4 ::: 2790
#pragma line 97 "/usr/include/stdio.h" 3 4 ::: 2795
#pragma line 1 "/usr/include/bits/stdio_lim.h" 1 3 4 ::: 2838
#pragma line 139 "/usr/include/stdio.h" 2 3 4 ::: 2856
#pragma line 166 "/usr/include/stdio.h" 3 4 ::: 2875
#pragma line 184 "/usr/include/stdio.h" 3 4 ::: 2882
#pragma line 244 "/usr/include/stdio.h" 3 4 ::: 2928
#pragma line 279 "/usr/include/stdio.h" 3 4 ::: 2942
#pragma line 301 "/usr/include/stdio.h" 3 4 ::: 2945
#pragma line 395 "/usr/include/stdio.h" 3 4 ::: 3009
#pragma line 437 "/usr/include/stdio.h" 3 4 ::: 3024
#pragma line 586 "/usr/include/stdio.h" 3 4 ::: 3129
#pragma line 632 "/usr/include/stdio.h" 3 4 ::: 3162
#pragma line 695 "/usr/include/stdio.h" 3 4 ::: 3211
#pragma line 726 "/usr/include/stdio.h" 3 4 ::: 3222
#pragma line 1 "/usr/include/bits/sys_errlist.h" 1 3 4 ::: 3252
#pragma line 755 "/usr/include/stdio.h" 2 3 4 ::: 3281
#pragma line 811 "/usr/include/stdio.h" 3 4 ::: 3314
#pragma line 832 "/usr/include/stdio.h" 3 4 ::: 3326
#pragma line 8 "black_scholes.c" 2 ::: 3329
#pragma line 1 "/usr/include/stdlib.h" 1 3 4 ::: 3330
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3364
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3389
#pragma line 34 "/usr/include/stdlib.h" 2 3 4 ::: 3392
#pragma line 97 "/usr/include/stdlib.h" 3 4 ::: 3393
#pragma line 128 "/usr/include/stdlib.h" 3 4 ::: 3408
#pragma line 183 "/usr/include/stdlib.h" 3 4 ::: 3449
#pragma line 276 "/usr/include/stdlib.h" 3 4 ::: 3485
#pragma line 426 "/usr/include/stdlib.h" 3 4 ::: 3529
#pragma line 1 "/usr/include/sys/types.h" 1 3 4 ::: 3543
#pragma line 35 "/usr/include/sys/types.h" 3 4 ::: 3566
#pragma line 62 "/usr/include/sys/types.h" 3 4 ::: 3583
#pragma line 100 "/usr/include/sys/types.h" 3 4 ::: 3611
#pragma line 133 "/usr/include/sys/types.h" 3 4 ::: 3636
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 3637
#pragma line 76 "/usr/include/time.h" 3 4 ::: 3660
#pragma line 92 "/usr/include/time.h" 3 4 ::: 3663
#pragma line 104 "/usr/include/time.h" 3 4 ::: 3666
#pragma line 134 "/usr/include/sys/types.h" 2 3 4 ::: 3669
#pragma line 147 "/usr/include/sys/types.h" 3 4 ::: 3670
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3671
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3696
#pragma line 148 "/usr/include/sys/types.h" 2 3 4 ::: 3699
#pragma line 187 "/usr/include/sys/types.h" 3 4 ::: 3709
#pragma line 1 "/usr/include/endian.h" 1 3 4 ::: 3741
#pragma line 1 "/usr/include/bits/endian.h" 1 3 4 ::: 3779
#pragma line 38 "/usr/include/endian.h" 2 3 4 ::: 3781
#pragma line 218 "/usr/include/sys/types.h" 2 3 4 ::: 3785
#pragma line 1 "/usr/include/sys/select.h" 1 3 4 ::: 3789
#pragma line 1 "/usr/include/bits/select.h" 1 3 4 ::: 3821
#pragma line 32 "/usr/include/sys/select.h" 2 3 4 ::: 3847
#pragma line 1 "/usr/include/bits/sigset.h" 1 3 4 ::: 3851
#pragma line 35 "/usr/include/sys/select.h" 2 3 4 ::: 3892
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 3903
#pragma line 119 "/usr/include/time.h" 3 4 ::: 3926
#pragma line 45 "/usr/include/sys/select.h" 2 3 4 ::: 3934
#pragma line 1 "/usr/include/bits/time.h" 1 3 4 ::: 3936
#pragma line 67 "/usr/include/bits/time.h" 3 4 ::: 3959
#pragma line 47 "/usr/include/sys/select.h" 2 3 4 ::: 3967
#pragma line 101 "/usr/include/sys/select.h" 3 4 ::: 4014
#pragma line 221 "/usr/include/sys/types.h" 2 3 4 ::: 4040
#pragma line 1 "/usr/include/sys/sysmacros.h" 1 3 4 ::: 4044
#pragma line 224 "/usr/include/sys/types.h" 2 3 4 ::: 4108
#pragma line 268 "/usr/include/sys/types.h" 3 4 ::: 4129
#pragma line 1 "/usr/include/bits/pthreadtypes.h" 1 3 4 ::: 4133
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 4157
#pragma line 24 "/usr/include/bits/pthreadtypes.h" 2 3 4 ::: 4159
#pragma line 48 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 4160
#pragma line 74 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 4179
#pragma line 101 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 4198
#pragma line 187 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 4267
#pragma line 271 "/usr/include/sys/types.h" 2 3 4 ::: 4298
#pragma line 439 "/usr/include/stdlib.h" 2 3 4 ::: 4299
#pragma line 588 "/usr/include/stdlib.h" 3 4 ::: 4441
#pragma line 1 "/usr/include/alloca.h" 1 3 4 ::: 4467
#pragma line 1 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 4493
#pragma line 56 "/opt/xilinx/Vivado_HLS/2014.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 4518
#pragma line 26 "/usr/include/alloca.h" 2 3 4 ::: 4521
#pragma line 613 "/usr/include/stdlib.h" 2 3 4 ::: 4530
#pragma line 659 "/usr/include/stdlib.h" 3 4 ::: 4565
#pragma line 724 "/usr/include/stdlib.h" 3 4 ::: 4617
#pragma line 751 "/usr/include/stdlib.h" 3 4 ::: 4633
#pragma line 796 "/usr/include/stdlib.h" 3 4 ::: 4670
#pragma line 815 "/usr/include/stdlib.h" 3 4 ::: 4678
#pragma line 922 "/usr/include/stdlib.h" 3 4 ::: 4763
#pragma line 958 "/usr/include/stdlib.h" 3 4 ::: 4769
#pragma line 9 "black_scholes.c" 2 ::: 4779
